### ISSUE TITLE
Adapter and quality trimming recommended?

### ISSUE THREAD

**Issue by jelber2** [voichek/kmersGWAS#1]
Do you recommend adapter and quality trimming, just adapter trimming, or use only raw reads as input?

**Comment by voichek** [comment]
I would recommend adaptor trimming - most of the data I worked with was trimmed before.

Regarding trimming for quality, I didn't try this. I would guess, at least for extreme cases, it might help. However, I would try to start without it and only start to play with these parameters if I have indication for high level of noise in the k-mers table. You can get an initial indication by looking at the kinship matrix and if it makes sense.
