### ISSUE TITLE
kmers_add_strand_information output

### ISSUE THREAD

**Issue by atwiersma** [voichek/kmersGWAS#10]
Output from kmers_add_strand_information indicates counts for Flag 0, 1, 2, 3. What do flag 0, 1, 2, 3 mean?

**Comment by voichek** [comment]
Thanks for the interest in our work!

A _k_-mer and it's reverse-complement are supposed to have the same chance to appear in a samples' sequencing data. However, technical reason can create a bias to one of the forms for some _k_-mer. Therefore we try to collect also the information of the form in which each k-mers appeared. For every _k_-mer we also save a flag that can take the values, 0,1,2,3 or in binary 00,01,10,11 which mean if in this sample: it appeared only in it's canonized form (**flag 01**) or only in it's non-canonized form (**flag 10**) or in both forms (**flag 11**). The **flag 00** is not supposed to occur, and if it does it means some went wrong technically. 

In the log files from _kmers_add_strand_information_ you see the total number of _k_-mers in this sample that had any of this 4 flags. You would expect that the number of flags 01 and 10 would be the same, and that 00 would have no k-mers.

Hope it makes things clearer

**Comment by Statekeylablin** [comment]
What's the meaning of canonized form and non-canonized form? kmer and its reverse complement? Thanks

**Comment by voichek** [comment]
There is a section about it in the end of the manual.
If something is not clear please let me know.

**Comment by U-di-Lan** [comment]
Hi Yoav,
Can you explain more on how you use the two counts? 
Also, in the manual you wrote that the 'ci' parameter is related to the sequencing coverage. in what way?
Tahnk you 
Udi
