### ISSUE TITLE
The order of the accessions of the kinship matrix

### ISSUE THREAD

**Issue by akcorut** [voichek/kmersGWAS#100]
Dear @voichek,

I hope everything is well. I have a question regarding to kinship matrix. If you use a kinship matrix in which order of accessions is not the same as in` kmers_table.names` as an input in kmersGWAS pipeline, does the pipeline give any warnings or does it somehow change (using `align_kinship_phenotype.py` perhaps?) the order of the matrix? Shortly, how the pipeline makes sure that everything in the same order if I feed the pipeline with a custom kinship matrix that are generated by an external software (from k-mers)?

**Comment by voichek** [comment]
Hi,

This is a good comment, for know it works as GEMMA and assume it is in the right order. As the format of the kinship does not contain the accessions/strains name it can not detect this. Therefore, you will need to make sure the kinship order is the same as in the `kmers_table.names`...

Best,
Yoav

**Comment by akcorut** [comment]
Hi @voichek,

Thanks for your reply. I understand why currently it is not possible to check the order. It would be a nice improvement though, in my opinion, if there is any way to make sure everything in the same order. 

Thank you for your time.

Best,
Kivanc

**Comment by voichek** [comment]
Hi Kivanc,

I agree, it is up on my list for things to improve, but for now I don't find time to do it.

Best,
Yoav
