### ISSUE TITLE
flag 00 should be equal to zero.

### ISSUE THREAD

**Issue by Jiny000** [voichek/kmersGWAS#101]
Hi,
I am very interested in your tool and performed kmer gwas as your guide for 520 samples.
```sh

#Count kmers
for sample in `cat ../sample.list`
do
mkdir $sample
echo "/01.raw_data/${sample}_1.fq.gz" >>${sample}/${sample}.fastq.path
echo "/01.raw_data/${sample}_2.fq.gz" >>${sample}/${sample}.fastq.path
bsub -e $sample/$sample.err -o $sample/$sample.out -J canon-$sample -q fatA -n4 "kmc -t4 -k31 -ci2 @$sample/$sample.fastq.path $sample/${sample}_kmc_canon $sample >$sample/$sample.KMC.canon.out"
bsub -e $sample/$sample.err -o $sample/$sample.out -J KMC-$sample -q fatA -n4 "kmc -t4 -k31 -ci0 -b @$sample/$sample.fastq.path $sample/${sample}_kmc_all $sample >$sample/$sample.KMC.all.out"
fi
done

#Combine the information
for sample in `cat ../sample.list`
do
bsub -e $sample/$sample.err -o $sample/$sample.out -J merge-$sample -q fat A "kmers_add_strand_information -c $sample/${sample}_kmc_canon -n $sample/${sample}_kmc_all -k 31 -o $sample/${sample}.kmers_with_strand"
done
```
However,I met some problems at combine the information step.Some samples were successful to get the result file,while other went wrong as:
```sh
Error: flag 00 should be equal to zero.
This is likely due to running the KMC non-canonized with -ci not 1
```
I wonder why this problem occurred by chance and how to solve it.
Thank you.

**Comment by voichek** [comment]
Dear Jiny,

Getting flag 00 is surprising, unless there is a very complex bug I would guess that the KMC counts were entered wrong. 

1. First, can you try to run my example script from the e. coli resistence? this should work.
2. Try to make an example of a specific sample, running the commands not as part of a script as maybe there is some more complex mix up.

Best,
Yoav

**Comment by Jiny000** [comment]
> Dear Jiny,
> 
> Getting flag 00 is surprising, unless there is a very complex bug I would guess that the KMC counts were entered wrong.
> 
> 1. First, can you try to run my example script from the e. coli resistence? this should work.
> 2. Try to make an example of a specific sample, running the commands not as part of a script as maybe there is some more complex mix up.
> 
> Best,
> Yoav

Thanks for your reply.I wonder the version of KMC in your pipeline.I used the 3.1.1 version.

**Comment by voichek** [comment]
I would be surprised if this due to a version change in KMC.

Did you try the two things I suggested?

**Comment by voichek** [comment]
Can I close this issue?

**Comment by GeertvanGeest** [comment]
This might have to do with the fact that you're using a job scheduler. `kmc` might tell your job scheduler that it's finished, but it might still be writing output files (file latency). I ran into the same issue while using this software with `nextflow`. If this applies to you, you could simply solve it with telling your job/pipeline scheduler to wait for a bit after command completion. This solved it for me:

```sh
kmc -t4 -k31 -ci2 \
@infiles.txt \
kmc_canon \
./

# sleep 20 seconds for file latency
sleep 20
```

**Comment by voichek** [comment]
Thank you for this info! 
I have to say, I didn't think that this can happen in Nextflow.

**Comment by GeertvanGeest** [comment]
No, it shouldn't. I didn't get to the bottom of it, but in my case it seems it has to do with the setup of the job scheduler or the cluster and how nextflow interacts with it.

**Comment by nirwan1265** [comment]
This occurs when you use different "k" in the combine KMC step. hth

**Comment by weiluwl** [comment]
> This might have to do with the fact that you're using a job scheduler. `kmc` might tell your job scheduler that it's finished, but it might still be writing output files (file latency). I ran into the same issue while using this software with `nextflow`. If this applies to you, you could simply solve it with telling your job/pipeline scheduler to wait for a bit after command completion. This solved it for me:
> 
> kmc -t4 -k31 -ci2 \
> @infiles.txt \
> kmc_canon \
> ./
> 
> # sleep 20 seconds for file latency
> sleep 20

Thanks for the solution! I have encountered the same error when running kmer merge step. The error will randomly appear in different samples during different runs. It was finally solved by adding sleep in the rule.
