### ISSUE TITLE
Best tool and command for mapping kmers to genome

### ISSUE THREAD

**Issue by caonetto** [voichek/kmersGWAS#102]
Hi,
Thanks for creating this pipeline.
Is there a recommended approach for mapping the selected kmers to a genomes, in the paper you describe you used
bowtie but is there any chance you could specify the details on the command chosen for the mapping of the kmers?

Thanks.

**Comment by voichek** [comment]
Dear Caonetto,

The parameters for running bowtie 1 to map is as written in the paper: "k-mers were aligned to the genome using bowtie v1.2.2 with the `-best -all -strata` parameter". As explained in the paper, there are couple of approached to identify the genomic context of a k-mer, all parameters used are explained in our method section.

Best,
Yoav
