### ISSUE TITLE
PAV table txt format - how to get list of kmers

### ISSUE THREAD

**Issue by laurenhamm** [voichek/kmersGWAS#103]
The manual suggests that to output the presence/absence pattern of a list of k -mers in textual format, you need to input the PAVtable results as well as a file with k -mers (each k -mer in a seperate line). Is there a way to output this from an earlier step?

**Comment by voichek** [comment]
Dear Laure(?),

I don't understand what you mean by an earlier step. To output the presence/absence pattern of _k-mers_ in textual format you first need to have it in binary format (i.e. have a _k-mers_-table). 

Please clarify, 
Best,
Yoav

**Comment by laurenhamm** [comment]
Yoav,
The code for getting the textual format (<KMERS-GWAS-PATH>/bin/filter_kmers -t kmers_table -k kmers_list.txt -o output.txt) has two inputs: -t (the binary k-mers table) and -k (a file with the kmers, one per line). I am having trouble with the latter. I thought that the combined "kmers_to_use" file would suffice as this input, but I recieve this error: "terminate called after throwing an instance of 'std::logic_error'
  what():  Ilegal kmer".

Is there a way to create a kmer list file from a previous step that I am overlooking?

**Comment by voichek** [comment]
`kmers_to_use` is a binary file, you need to provide here a textual file, you can read [this previous issue](https://github.com/voichek/kmersGWAS/issues/62) for more information.

**Comment by voichek** [comment]
I am closing this issue, please reopen if something is still not clear.
