### ISSUE TITLE
The order of accessions in kmers_to_use.shareness table

### ISSUE THREAD

**Issue by akcorut** [voichek/kmersGWAS#104]
Dear @voichek,

I have a quick question regarding to `kmers_to_use.shareness` file that is generated after running `list_kmers_found_in_multiple_samples`. Is the order of accessions in the `kmers_to_use.shareness` file same as the order in `kmers_list_paths.txt`? I couldn't find the exact information on that so I'm sorry if it is explained somewhere and I missed it.

Thank you for your time.
Kivanc

**Comment by voichek** [comment]
Dear Kivanc,

The order of accessions do not affect the `kmers_to_use.shareness` file. This file is just an histogram of the different allele counts in your table. So how many k-mers apeared in 0,1,2,....,n of your accessions. The first few values should be 0 if you had some filtering for MAC or MAF when creating the k-mers table. Then you should also have many k-mers which appear in almost all of your ecotypes.

With the information in this file you can create [this type of figures](https://www.nature.com/articles/s41588-020-0612-7/figures/10)
Best,
Yoav

**Comment by voichek** [comment]
I am closing the issue, please reopen if needed.

Best,
Yoav
