### ISSUE TITLE
Error in eigen(x, only.values = TRUE):

### ISSUE THREAD

**Issue by ChenSh1ne** [voichek/kmersGWAS#105]
Hi, voichek,
I got errors when run the following step using the example data (1000G_A_thaliana_kmers):

[ccc@login1 kmerGWAS]$ Rscript /home/chens/software/kmerGWAS/src/R/transform_and_permute_phenotypes.R run_GWAS_FT10/pheno.phenotypes run_GWAS_FT10/pheno.kinship 100 run_GWAS_FT10/pheno.phenotypes_and_permutations run_GWAS_FT10/pheno.phenotypes_permuted_transformed run_GWAS_FT10/EMMA_perm.log > run_GWAS_FT10/phenotypes_transformation_permutation.log
Error in eigen(x, only.values = TRUE) : 
  error code 1 from Lapack routine 'dsyevr'
Calls: is.positive.semi.definite -> eigen
Execution halted

what is matter with it, How to fix it?

regards,

SChen

**Comment by voichek** [comment]
Hi SChen,

1. Did you make sure the libraries needed in R are installed properly?
2. Just to make sure, you didn't change anything in the files used for the example, right?

Best,
Yoav

**Comment by ChenSh1ne** [comment]
> Hi SChen,
> 
> 1. Did you make sure the libraries needed in R are installed properly?
> 2. Just to make sure, you didn't change anything in the files used for the example, right?
> 
> Best,
> Yoav

Hi, voichek, 

Thanks for your quick replay, I make sure all the R libraries needed were installed, This is followed by my error message:

[chens@login1 kmerGWAS]$ python2.7 ~/software/kmerGWAS/kmers_gwas.py --pheno FT10.pheno --kmers_table A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 1 --outdir run_GWAS_FT10
Error in eigen(x, only.values = TRUE) : 
  error code 1 from Lapack routine 'dsyevr'
Calls: is.positive.semi.definite -> eigen
Execution halted
Traceback (most recent call last):
  File "/home/chenshuai/software/kmerGWAS/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/chenshuai/software/kmerGWAS/kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'run_GWAS_FT10/pheno.phenotypes_and_permutations'

chens

**Comment by voichek** [comment]
Dear Chens,

There seem to be a problem with the function 'is.positive.semi.definite' from the library `matrixcalc` in R.

Can you please open R and try to use this function and see if it works, maybe there is an issue with the installation of this library?

Best,
Yoav

**Comment by ChenSh1ne** [comment]
> Dear Chens,
> 
> There seem to be a problem with the function `is.positive.semi.definite` from the library `matrixcalc` in R.
> 
> Can you please open R and try to use this function and see if it works, maybe there is an issue with the installation of this library?
> 
> Best,
> Yoav

Hi, Voichek,

After I changed the R versions and it works, thanks for your reply!

Best


Chens

**Comment by viannam** [comment]
@Sh1ne111 Which R version are you using?
