### ISSUE TITLE
GWAS for tetraploid spp

### ISSUE THREAD

**Issue by cdanmaigona** [voichek/kmersGWAS#109]
Can this pipeline be used for tetraploid species?

**Comment by voichek** [comment]
Hi,

Short answer is that I have never tried, and therefore can't say exactly how will it work and what are the constrains or sequence depth requirements.

The idea that k-mers tag different variants should still work, and if a variant like SNP homo- or heterozygous is in the data some k-mers should tag it.

Best wishes,
Yoav
