### ISSUE TITLE
KeyError: 'P1'

### ISSUE THREAD

**Issue by JinkwanJo** [voichek/kmersGWAS#110]
Dear voichek. I have same issue with a below link. I downloaded v.0.2 version and tried again. but It's not solution for me.  https://githubmemory.com/repo/voichek/kmersGWAS/issues/92

Hear the message I've got.
This is the running of example which is flowering_time_arabidopsis
"""
python2.7 ../../kmers_gwas.py --pheno FT10.pheno --kmers_table A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 8 --outdir run_GWAS_FT10
"""

\## number of total individuals = 876
\## number of analyzed individuals = 876
\## number of covariates = 1
\## number of phenotypes = 1
\## number of total SNPs = 10001
\## number of analyzed SNPs = 10001
Start Eigen-Decomposition...
Start Eigen-Decomposition...
Start Eigen-Decomposition...
Start Eigen-Decomposition...
Start Eigen-Decomposition...
Traceback (most recent call last):
  File "/data/tools/kmersGWAS/kmers_gwas.py", line 278, in <module>
    main()
  File "/data/tools/kmersGWAS/kmers_gwas.py", line 247, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/data/tools/kmersGWAS/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'

**Comment by voichek** [comment]
Can you check if the GEMMA used, works in your system?

**Comment by JinkwanJo** [comment]
Yes, I tested Gemma using only gemma -h, and it worked.
However, I followed the link "https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460" below.
The gemma version should then be changed.
But I'm still wondering if there are any other outcomes.
Have a wonderful holiday season.

**Comment by voichek** [comment]
Hi,

Sorry for the late reply, I am on holiday, but I'm still trying to be available.

Is this still an issue? now it works for you with GEMMA 0.98, no?

What do you mean by any other outcome?

Happy new year,
Yoav

**Comment by Daluser1** [comment]
Dear Yoav,

I have the same problem. I replaced the files kmers gwas.py and functions.py (https://github.com/voichek/kmersGWAS/files/5282436/replacement.zip), and run it using  0.98.1. However, I got this error:

Traceback (most recent call last):
  File "/.../.../src/py/kmers_gwas.py", line 45, in <module>
    execfile(paths["gen_script"])
IOError: [Errno 2] No such file or directory: '/.../.../src/py/src/py/functions.py'

I would appreciate any advice on what is the issue and how can I solve it?

**Comment by Daluser1** [comment]
Dear Yoav,

I have the same problem. I replaced the files kmers gwas.py and functions.py (https://github.com/voichek/kmersGWAS/files/5282436/replacement.zip), and run it using  0.98.1. However, I got this error:

Traceback (most recent call last):
  File "/.../.../src/py/kmers_gwas.py", line 45, in <module>
    execfile(paths["gen_script"])
IOError: [Errno 2] No such file or directory: '/.../.../src/py/functions.py'

I would appreciate any advice on what is the issue and how can I solve it?

**Comment by JinkwanJo** [comment]
> Hi,
> 
> Sorry for the late reply, I am on holiday, but I'm still trying to be available.
> 
> Is this still an issue? now it works for you with GEMMA 0.98, no?
> 
> What do you mean by any other outcome?
> 
> Happy new year, Yoav

Now it works with GEMMA 0.98.

I mean I wonder the results of 0.96 or 0.98 is same.

Thank you, Happy new year!

Jinkwan

**Comment by voichek** [comment]
The results for 0.96 and 0.98 should be exactly the same. At least this was true for all my tests.

Best,
Yoav
