### ISSUE TITLE
Error When Running on Arabidopsis Flowering Time Example

### ISSUE THREAD

**Issue by Daluser1** [voichek/kmersGWAS#111]
Hi Dr. Voichek,

I have been testing the kmersGWAS pipeline on the example flowering time arabidopsis. This is the code that I used:

 python2.7 /scratch/SVV/kmers_gwas.py --pheno /scratch/SVV/examples/flowering_time_arabidopsis/FT10.pheno --kmers_table "/scratch/SVV/examples/flowering_time_arabidopsis/A_thaliana_1001G_kmers_table/kmers_table.kinship" -l 31 -p 32 --outdir run_GWAS_FT10

and this is the error message:
File "/scratch/SVV/kmers_gwas.py", line 278, in <module>
    main()
  File "/scratch/SVV/kmers_gwas.py", line 55, in main
    create_dir(args.outdir)
  File "/scratch/SVV/src/py/functions.py", line 49, in create_dir
    raise Exception(err_msg)
Exception: directory allready exist run_GWAS_FT10

I would appreciate it if you have any thoughts on what might be the issues and how can I fix them?

Best Regards,
SV

**Comment by voichek** [comment]
Dear SV,

The error message says "directory already exist run_GWAS_FT10", remove the directory and try again.


Best,
Yoav

**Comment by Daluser1** [comment]
Dear Voichek,

Thank you for prompt response. I removed the directory and run the code again. However, I still get an error message:
sh: Rscript: command not found
Traceback (most recent call last):
  File "/scratch/SVV/kmers_gwas.py", line 278, in <module>
    main()
  File "/scratch/SVV/kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: '/scratch/SVV/examples/flowering_time_arabidopsis/run_GWAS_FT10/pheno.phenotypes_and_permutations'

**Comment by xbarvazx** [comment]
I get the same error, was this solved?

**Comment by voichek** [comment]
The issue above is two different, non-connected issue. The first is that the directory of output already exist and the second is that Rscript, that is R, cannot be found.

If you have an issue you need help with, please open a new issue and describe the specific problem you are having.
