### ISSUE TITLE
GEMMA bslmm

### ISSUE THREAD

**Issue by viannam** [voichek/kmersGWAS#112]
Dear Voichek,

Thank you for making this pipeline available.

I am trying to run GEMMA bslmm instead of lmm for the kmers gwas analyse, but I got the same error message that you got here: [https://github.com/genetics-statistics/GEMMA/issues/182] using gemma/0.98. How did you overcome this issue? Also, is there a way that you suggest modifying the kmers_gwas.py pipeline to use the gemma bslmm model?

Thank you very much,

**Comment by voichek** [comment]
Dear Mariana,

The issue with the gemma/0.98 is that the column which has the p-value in the GEMMA output is different from the 0.96 output. This is likely the same issue as running bslmm. You can see the changes I've made to kmers_gwas.py (very minor) and change it to the right column for the p-value of the bslmm.

Let me know if this solve your problem,
Best,
Yoav

**Comment by voichek** [comment]
Dear Mariana,

Can we close this issue?

Best,
Yoav
