### ISSUE TITLE
How to create a Q-Q plot?

### ISSUE THREAD

**Issue by soungalo** [voichek/kmersGWAS#114]
I see in the manuscript as well as some issues here that you recommend to create Q-Q plots to QA GWAS results. However, I'm not sure how this should be done in the context of the pipeline. Where should I take the p-values from? We have the file `GWAS/kmers/output/phenotype_value.assoc.txt` (with the `p_lrt` column), but it only lists p-values for the best k-mers (10001 by default), and using only these p-values results in a very strange Q-Q plots starting e.g. in (0,5). Does this mean that in order to produce a Q-Q plot one needs to avoid any filtration in the first step and compute p-values for all k-mers? Is this even possible? Am I missing something?

**Comment by voichek** [comment]
Hi Lior,

You are right, one cannot plot the QQ-plot from the output of the pipeline. This is as a main optimization step is to avoid calculating the exact p-value for variants which are clearly not significant.

To plot a QQ plot you will need the accurate p-values for all variants, you can do this using the `kmers_table_to_bed` functionality and then running it with an outside GWAS program. I used GEMMA as the other input to it is already in your output directory from the k-mers-GWAS run. 

This was also discussed here:
https://github.com/voichek/kmersGWAS/issues/94

Hope it helps,
Best (and congratulations!)
Yoav

**Comment by soungalo** [comment]
Thanks Yoav.
1. Do you think this approach is feasible for a large data set with 6.3 billion k-mers? Maybe some subsampling strategy is required.
2. Is it possible to get the p-values (or some other measure) computed in the first filtration step? I know they are not so accurate, but maybe they are good enough to produce a QQ plot?
