### ISSUE TITLE
No output in pass_threshold_5per with even example data

### ISSUE THREAD

**Issue by vinod1981** [voichek/kmersGWAS#116]
Dear Voichek,
I want to try kmer_gwas pipeline for a highly heterozygous plant species. 
Bit I am not getting any results in these files
 best_pvals                       Contains only '0'
 pass_threshold_5per        Only header
 pass_threshold_10pe        Only header

Even I tried it with A. thaliana flowering time example data and still these files are empty. Output contains GEMMA GWAS results. 

The only thing I changed, I am using  GEMMA' recent version (0.98.5). Why I am missing the significance level?

In some earlier issues, you suggested to change kmers_gwas.py if people use a different version of GEMMA. Is it still applicable or that is not necessary with current kmers_gwas.py.   

Commands are like this:

```
python /vol/cluster-data/vkumar/miniconda3/bin/kmer_gwas//kmers_gwas.py --pheno /vol/cluster-data/vkumar/miniconda3/bin/kmer_gwas/examples/flowering_time_arabidopsis/FT10.pheno --kmers_table /prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 8 --gemma_path /prj/pflaphy-robot/software/gemma-0.98.5-linux-static-AMD64 --outdir /prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table//gwas_results >>/prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table//gwas_run.log.txt 2>&1

/prj/pflaphy-robot/software/gemma-0.98.5-linux-static-AMD64 -bfile /prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table//gwas_results/kmers/pheno.0.phenotype_value -lmm 2 -k /prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table//gwas_results/pheno.kinship -outdir /prj/pflaphy-robot/kmer_gwas/atha/A_thaliana_1001G_kmers_table//gwas_results/kmers/output -o phenotype_value -maf 0.050000 -miss 0.
5

```
Your time is appreciated.

Thanks,

Vinod,

**Comment by voichek** [comment]
Dear Vinod,

Yes, as I mentioned before, if you change the GEMMA version the pipeline will not work. If you update it to the version I indicated before, [the patch](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) I put should work.

In any case, make sure the flowering time example work before you try on your own data.

And there is no reason to write me an email if you open an issue, I am very responsive here.

Best,
Yoav

**Comment by vinod1981** [comment]
Dear Voicheck,
Thanks for a quick response.
I'll try it and post here the closing reply.
Thanks,
Vinod,
