### ISSUE TITLE
Difefrent subsets of a large panel

### ISSUE THREAD

**Issue by vinod1981** [voichek/kmersGWAS#117]
Dear Voichek,
I have a large gwas panel on which I ran the kmer_gwas pipeline. But I also want to perform it on different sub-populations of the same panel. Do I need to repeat the kmers_table step for all the sub-populations separately or just providing a sub-population-wise phenotypes file is sufficient to subset everything automatically by the script.
QQ-plot from my data for one trait with full kmers set is a bit weird at the end, population seems to be well controlled as lambda is close to 1. I found a high correlation (r=0.96) between SNP- and kmers-based matrices. A bit confused if the inflation is coming because of true variants or I need to modify something.    

 
![kerms_qqplot_kinship_full_matrix_gemma_2](https://user-images.githubusercontent.com/4056044/177186934-cdcf509f-a29b-4a1c-90fa-2ead0c4f5802.jpeg)

Another question: Did you perform a separate analysis for different traits (_A. thaliana_) with full model (including all kmers) in GEMMA to see test-statistics using QQ-plot or just having look at one trait is more or less sufficient?
Because performing gemma with full set of kmers can take a lot of time with more than 100 traits.

Thanks,

Vinod,

**Comment by voichek** [comment]
Dear Vinod,

1. No, you do not need to prepare separate kmers-tables. Just give sub-population-wise phenotypes and the program will subset the kmers-table itself.
2. This QQ-plot doesn't look inflated, 0.9999 of your variants have p-values as expected (and therefore the lambda value). It might be that many k-mers tag the exact same variant, as they have the same p-value. In any case, it looks interesting, but it is biology, the statistics looks good to me.
3. I've done the full model as control for a few phenotypes, like I am showing with the flowering time in the paper. But there is no need to do it with all... the all purpose of this library is to avoid this and make the computations faster/feasible. I would recommend to do it only as a control for some phenotypes. For example, the QQ-plot you showed above should give you a good feeling regarding the population-correction for this kmers-table, in my opinion.

Hope it helps,
Best,
Yoav

**Comment by vinod1981** [comment]
Dear Voichek,
Thanks for the replies.
Vinod
