### ISSUE TITLE
General question: How kmers are indexed in fetched reads?

### ISSUE THREAD

**Issue by vinod1981** [voichek/kmersGWAS#118]
Dear Voichek,
I could fetch the kmers containing reads using fetch_reads_with_kmers and mapped them against reference genome using BWA mem.  
But one thing I am missing is how to track aligned reads back to the kmers and give kmers a genomic position so I can use them finally in Manhattan plot. My kmers are mapped to many genomic locations.
I don't know:
Which kmer occurs in which read?
In how many reads it occur?
What is the occurrence position?

Is kmers name somehow indexed in the reads fetched using fetch_reads_with_kmers which I am missing completely?
Because I can see them in IGV but can't assign a position to the pass_threshold_5per table to mark them in Manhattan plot.
Thanks,

Vinod,

**Comment by voichek** [comment]
Dear Vinod,

This functionalities are not part of this and the fetch_reads_with_kmers libraries. 

Finding the positioning of all k-mers is not something that you can do systematically, at least not in an easy way. The idea behind this library is to find the associations which are hard to position in the genome. 

If you want to only look at the k-mers which are associated above the threshold, I would recommend to break them to clusters, based on LD, like I did in the tomato example. Then find all reads associated with each cluster and show this position on the genome. 

Hope it helps,
Yoav

**Comment by voichek** [comment]
Can we close this issue?
