### ISSUE TITLE
error! fail to open .bim/.bed

### ISSUE THREAD

**Issue by guidopuccetti** [voichek/kmersGWAS#119]
Dear voichek,
thanks for developing this pipeline!  

I have an annoying error when I try to run kmers_gwas.py for comparing to SNP-based GWAS.
I get the snps directory with all the subdirectories, but many files are empty.

I get this error message although the script runs smoothly.
```
error! fail to open .bim file: snps/snps/snps.plink.bim
error! fail to open .bed file: snps/snps/snps.plink.bed
Loading snps information
snps.plink      (snps,samples) = 58152303, 151
MAF = 0.05 n_sample = 151
Minor allele count  = 8
Associating phenotypes
```
The script I am running is the following 

python2.7 $Kmer_GWAS/kmers_gwas.py
--pheno resistence.pheno
--dont_run_on_kmers
--run_on_snps_two_steps
--snp_matrix snps.plink
--snps_number 20000
--kinship_snps
--kmer_len 25
--kmers_table kmers_table
--gemma_path$path_gemma/external_programs/gemma_0_96
 --outdir snps"
### Further information
I generated the --kinship_snps as follow (emma_kinship snps.plink > snps.plink.kinship)
I generated the --snp_matrix as follow (kmers_table_to_bed -t kmers_table -k 25 -p resistence.pheno --maf 0.05 --mac 5 -b 500000000 -o snps.plink)
The order and the number of the isolates in resistence.pheno is the same as kmers_table.name
I guess the error comes from the kmers_table_to_bed but I am not fully sure how to fix it.. Thanks for your time!!
Ciao Guido

**Comment by voichek** [comment]
Dear Guido,

I am not sure I understand. If you want to compare to a SNP-matrix you need to build one, this has to be done separately from this pipeline. From what you wrote in your massage, it seems you try to build the snps matrix from the k-mers table. I guess there is some miss-understanding here. Please clarify.

Best wishes,
Yoav

**Comment by guidopuccetti** [comment]
Dear voichek,
This is embaracing.. Thanks, for this recap (I am new to bioinformatics) and I have indeed missunderstood the manual at the sentence "This PLINK binary files can then be used as input to SNP-based GWAS program" but I now understand that this sentence is referring only to the .fam file. (Is it correct?).
I have now generated the SNPs matrix starting from the VCF. Nevertheless I am still getting the same error message despite the snps.plink.bim & snps.plink.bed are now originated from the SNPs vcf.

`error! fail to open .bim file: snps/snps/snps.plink.bim
error! fail to open .bed file: snps/snps/snps.plink.bed
Loading snps information
SNPs_plink_files        (snps,samples) = 472042, 151
MAF = 0.05 n_sample = 151
Minor allele count  = 8
Associating phenotypes:.....................................................................................................Average time per phenotype: 0.117931
`
The script running is the following. 

python2.7 $Kmer_GWAS/kmers_gwas.py 
--pheno resistence.pheno 
--dont_run_on_kmers 
--run_on_snps_two_steps 
--snp_matrix SNPs_plink_files 
--snps_number 20000 
--kinship_snps 
--kmer_len 25 
--kmers_table kmers_table 
--gemma_path $external_programs/gemma_0_96 
--outdir snps

**Further information**
I generated the --snp_matrix as follow (plink --const-fid 0 --vcf $subset_SNPs_vcf --make-bed --out SNPs_plink_files).
I then changed the fam file accordingly to the fam generated for the kmer(cp kmer.plink.fam SNPs_plink_files.fam). 
I generated the --kinship_snps as follow (emma_kinship SNPs_plink_files > SNPs_plink_files.kinship).
Once again the arrange and the number of the isolates is the same for the kmer.plink.fam, SNPs_plink_files.fam and for the kmers_table.names.
Accordingly to the error message it seems that the error is due to the SNPs_plink_files.bim and SNPs_plink_files.bed files. Nevertheless I have already used these files for running an independent SNPs based GWAS with gemma and the files are not corrupted and are working fine.
Thanks again for going through these really basic issues!! Since it seems that the error comes from the bim&bed not sure it is your "responsibility" to fix it but a suggestion would be really much appreciated! 
Ciao Guido

**Comment by voichek** [comment]
Can you please send me the directory of this run that fails.

**Comment by guidopuccetti** [comment]
Dear Voichek,
I am sharing with you the directory.  Unfortunatly is too big to be shared
on github.
Ciao
Guido
 snps.tar.gz
<https://drive.google.com/file/d/1XMkZrD4qVQiFLgWkRE84l1uTRZY2vIcZ/view?usp=drive_web>

Il giorno mar 9 ago 2022 alle ore 14:00 Yoav Voichek <
***@***.***> ha scritto:

**Comment by voichek** [comment]
We are on holiday, I will answer in a week when I am back.

sorry for the inconvenience.

**Comment by voichek** [comment]
Hi,

This is a bit weird, the pipeline is making a soft link between your original snp matrix and snps/snps/snps.plink.bim (or bed) and it looks like it doesn't work for some reason.

Can you try to run this [patch](https://github.com/voichek/kmersGWAS/files/9349452/kmers_gwas.py.zip), just unzip it and replace the kmers_gwas.py by this one. I just modified to copy the snp matrix and not use soft links to see if this is the issue.

Let me know how it works.
Best,
Yoav

**Comment by guidopuccetti** [comment]
Dear Voichek,
thanks! Hope you had some nice holidays!
I am now on holiday, I will be back next week and I will let you know!
I will let you know next week!
Ciao 
Guido

**Comment by guidopuccetti** [comment]
Hi, it works, thanks!
