### ISSUE TITLE
how can use kinship table in kmer_gwas command 

### ISSUE THREAD

**Issue by sunnycqcn** [voichek/kmersGWAS#12]
Hello,
This is my command using kmers_gwas.py. But I did not find the parameter about kinship value.
python /isilon/saskatoon-rdc/users/fuf/comDIR/kmersGWAS/kmers_gwas.py --pheno pheno.RLM7 --kmers_table kmers_table --permutations 1000 -l 31 -p 20 --outdir RLM7
Thanks,
Fuyou

**Comment by voichek** [comment]
The pipeline expect to find the kinship matrix in the file `kmers_table.kinship`

You can find an example of the format [here](https://zenodo.org/record/3596255#.XqfMjJMzZhE)

The order of accessions should be the same as in `kmers_table.names`

**Comment by sunnycqcn** [comment]
Hello,
I got the kinship file. I think I did not said my question clearly.  I think I have understood this problem. kinship file will be used in kmers_gwas.py. We do not need set a parameter.
Thanks,
Fuyou

**Comment by voichek** [comment]
Yes, the pipeline needs a kinship to work.
