### ISSUE TITLE
list_kmers_found_in_multiple_samples "Couldn't find file"

### ISSUE THREAD

**Issue by guidopuccetti** [voichek/kmersGWAS#121]
Dear Voichek,

As I previously mention I am interested in testing your pipeline. After a pretest with a subset of the collection (150 individuals), I am now testing the entire collection (1417 individuals). I am running the following script:
`list_kmers_found_in_multiple_samples -l kmers_list_paths.txt -k 25 --mac 5 -p 0.2 -o kmers_to_use
`
 When I try to combine all the kmers canon and non-canon it runs fine for the first 1021 individuals, then  I receive the following error:

`Couldn't find file: /data1/guido/Kmer_GWAS_11_08_2022/individualX/18STF004.3/kmers_with_strand
`
If I copy and paste the directory exist as the file.
If I look at the add_strand.log.out of the dir 18STF004.3 the flags looks fine.
I then removed the file 18STF004.3 and once I run the command again, I received a new error message with the next isolate in the kmers_list_paths.txt, 18STF005.1. This error message is repeated starting from the line 1021 of the kmers_list_paths.txt.
<img width="878" alt="Screenshot 2022-08-24 at 09 13 56" src="https://user-images.githubusercontent.com/57522203/186354890-05970595-0223-4f1f-8c79-adf66e84f661.png">

As a test, I then generated a new kmers_list_paths.txt with the isolates for which I got the error message ( 18STF004.3 etc..). And surprisingly it is now working for the subset! My conclusion is that the path of the files is correct and that this error message is related to the number of individuals that I am testing.

Is it possible that the function list_kmers_found_in_multiple_samples has a limit of number of individuals? Or do you have any suggestion how could I fix this error?
Thanks!
Ciao Guido

**Comment by voichek** [comment]
Dear Ciao,

It sounds like your system has a [limit on the number of open files](https://www.tecmint.com/increase-set-open-file-limits-in-linux/) (which might be 1024).

Maybe this is the case? Can you change this number?

Best,
Yoav

**Comment by guidopuccetti** [comment]
Dear voichek,
thanks it worked!
Best,
Guido!
