### ISSUE TITLE
making binary 0/1 PAV table usable in r

### ISSUE THREAD

**Issue by laurenhamm** [voichek/kmersGWAS#122]
I am using the first half of this method (up to when the PAV table has been generated), and then redirecting the PAV table to be used for GEA analysis. I have successfully generated the NAME_table.table binary file, but am having a difficult time converting this to a usable flatfile format to upload as a dataframe into R without knowing the number of columns and rows. I'm assuming the columns are the individual names in the order they appear in the later generated .fam file, but I have no idea how to determine how many rows (kmers?) to include. 

Is there a suggested method for converting the binary table file into a usable dataframe?

**Comment by voichek** [comment]
Dear Ren,

To convert it from my binary formatting to textual format I suggest going through the PLINK binary file and then converting to VCF.

Best,
Yoav

**Comment by laurenhamm** [comment]
That worked! Thank you.
