### ISSUE TITLE
error while running kmers_gwas.py

### ISSUE THREAD

**Issue by dosshra** [voichek/kmersGWAS#125]
Hi
I am running the following code in conda environment with R and pyhton2.7:
`python2.7 /data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py --pheno  /data/home/distelfeld/ylevmirom/kmers/TA_lines/wildomesticated.pheno --kmers_table /data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table.table -l 31 -p 20 --outdir /data/home/distelfeld/hsela3/gwaskmer3`  

I am getting this output:

> affective MAF = 0.166666666667
Traceback (most recent call last):
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 278, in <module>
    main()
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/data/home/distelfeld/ylevmirom/kmers/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
/data/home/distelfeld/hsela3/gwaskmer3/kmers

What could be the problem?
Thank you, Hanan

**Comment by voichek** [comment]
Dear Hanan,

I think you need to call the `kmers_table` by the prefix that is 
`/data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table` instead of `/data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table.table`.

Can you try this?
Otherwise, I would start by trying to run example 1 just to check everything is configured correctly in your system.

Best wishes,
Yoav

**Comment by dosshra** [comment]
HI
Thank you for the quick response
I tried the path:
`/data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table.table`
but then I get:

> Traceback (most recent call last):
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 278, in <module>
    main()
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 55, in main
    create_dir(args.outdir)
  File "/data/home/distelfeld/ylevmirom/kmers/src/py/functions.py", line 49, in create_dir
    raise Exception(err_msg)
Exception: directory allready exist /data/home/distelfeld/hsela3/gwaskmer5
(py2) [hsela3@bee059 ~]$ python2.7 /data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py --pheno  /data/home/distelfeld/ylevmirom/kmers/TA_lines/wildomesticated.pheno --kmers_table /data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table.table -l 31 -p 20 --outdir /data/home/distelfeld/hsela3/gwaskmer6
Traceback (most recent call last):
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 278, in <module>
    main()
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 74, in main
    acc_order = [x for x in file(args.kmers_table + ".names", "r").read().split("\n") if len(x)>0]
IOError: [Errno 2] No such file or directory: '/data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table.table.names'

I will try running the example.

**Comment by voichek** [comment]
Dear Hanan,

1. Notice that it complained about the output directory already existing.
2. You should try `/data/home/distelfeld/ylevmirom/kmers/TA_lines/kmers_table` (without the .table).

Best,
Yoav

**Comment by dosshra** [comment]
Hello Yoav 
I run it with the A thaliana example: 
`(py2) [hsela3@bee055 ~]$ python2.7 /data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py --pheno  ~/FT10.pheno --kmers_table ~/A_thaliana_1001G_kmers_table/kmers_table -l 31 -p 20 --outdir /data/home/distelfeld/hsela3/gwaskmer1`

and I get the same error:

> affective MAF = 0.05
Traceback (most recent call last):
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 278, in <module>
    main()
  File "/data/home/distelfeld/ylevmirom/kmers/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/data/home/distelfeld/ylevmirom/kmers/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
/data/home/distelfeld/hsela3/gwaskmer1/kmers

Thank you
Hanan

**Comment by dosshra** [comment]
Thank you for the response. See attached results. 
I worked in TAU previously, but before they did this analysis. 
Who was your contact there? Raz? Udi?

Thank you
Hanan  
[gwaskmer2.tar.gz](https://github.com/voichek/kmersGWAS/files/9622289/gwaskmer2.tar.gz)

**Comment by voichek** [comment]
Dear Hanan,

I have discussed with Udi.

You have a problem with the c++ standard libraries, you need to ask around how to load it.
You can see the error in the `associate_kmers.log` in the folder you sent me.
It contains the following errors:
```
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers)
```

It will probably give you the error if you just try to run `/data/home/distelfeld/ylevmirom/kmers/bin/associate_kmers`, which can help you to fix your environment, as you need this program to be able to run for running the pipeline.

Best,
Yoav

**Comment by dosshra** [comment]
HI
We used the right GCC module and got the results. 
Thank you
Hanan
