### ISSUE TITLE
kmers_add_strand_information

### ISSUE THREAD

**Issue by fanmiaowang** [voichek/kmersGWAS#129]
Hi,

I failed in combining kmc_canon and kmc_all when dealing with large files. 
The size of my kmc_canon.kmc_suf is 22G and kmc_all.kmc_suf  is 249G. 

Is it possible to combine such large kmer files by using kmerGWAS tool? By the way, kmers_add_strand_information works well with smaller kmer files. So I think the file size matters.

Thanks.

**Comment by voichek** [comment]
Hi,

This seems much larger than anything I played with, also the ratio between the non-canonized and canonized seems especially high. Just to make sure it make sense, can you give a bit more detail on the samples: (a) This is regular Ilumina short read output? (b) What is coverage of the genome? (e.g. 10X, 100X) (c) what is the number of k-mers counted by the KMC (maybe you paste here the output of the KMC) (d) With what parameters did you run the two KMC commands? (e) do you have similar file sizes for all accessions/strains or is this a special one with super high coverage?

Also, what do you mean failed? what was the error massage ? 

Best,
Yoav

**Comment by fanmiaowang** [comment]
Hi,

Thanks for your reply. 


 (a) This is regular Ilumina short read output? 

No, I am dealing with nanopore sequence, which is long read output. 

(b) What is coverage of the genome? (e.g. 10X, 100X) 
The coverage of the genome is about 50X. 

(c) what is the number of k-mers counted by the KMC (maybe you paste here the output of the KMC) 

I paste the output of the KMC as below:


1st stage: 648.822s
2nd stage: 226.962s
Total    : 875.784s
Tmp size : 48174MB

Stats:
   No. of k-mers below min. threshold :  27481962192
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :  30187603954
   No. of unique counted k-mers       :   2705641762
   Total no. of k-mers                :  49809235826
   Total no. of reads                 :      2364100
   Total no. of super-k-mers          :   3985135451
1st stage: 649.001s
2nd stage: 220.86s
Total    : 869.861s
Tmp size : 48174MB

Stats:
   No. of k-mers below min. threshold :            0
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :  31122781382
   No. of unique counted k-mers       :  31122781382
   Total no. of k-mers                :  49809235826
   Total no. of reads                 :      2364100
   Total no. of super-k-mers          :   3985135451

(d) With what parameters did you run the two KMC commands? 

My code to run KMC commands is as below:

kmc -t32 -ci2 -k31 @S001.txt kmc_canon ./
kmc -t32 -ci0 -k31 -b @S001.txt kmc_all ./

(e) do you have similar file sizes for all accessions/strains or is this a special one with super high coverage?

I have two species: cucumber and eggplant. For all accessions of eggplant, they have similar file size and coverage. I have trouble for all these accessions in combing KMC_canon and KMC_all.

But there is no problem for accessions of cucumber when running KMC and kmerGWAS, because file sizes for cucumber are much smaller than eggplant (the file size of about 1/3 of the file size of eggeplant).  


> Also, what do you mean failed? what was the error massage ?

Below is the error message I had:

/var/gridengine/n07-ib/job_scripts/3077511: 1 line: 24928 Bus Error        (core dump) /lustre/home/wfm/tools/kmersGWAS/bin/kmers_add_strand_information -c kmc_canon -n kmc_all -k 31 -o kmers_with_strand

Core dump is a sign of out of memory? I am doing this job in qsub with 32 threads.


Best,
Fanmiao

**Comment by voichek** [comment]
Dear Fanmiao,

Thanks for the extra information.

1. It is a memory error, but it is not clear it is out of memory or trying to accesses a wrong address in the memory. There is no need to to request 32 threads as this step is run only on one thread. Can you run it with much more memory and see if it solves the issue? 
2. Do the `kmers_add_strand_information` print "Canonized kmers:...." before it crashes? Does it print other things before it crashes? (this will be an indication to which step in the code fails).
3. Regardless of the issue you raised, as the coverage is so high I would recommend to increase the threshold for the number of appearances of a k-mer to be counted (in canonized form), at least to 4-5 to begin with, so `kmc -t32 -ci5 -k31 @S001.txt kmc_canon`. If coverage is very high, especially for nanopore which should have more mutations than Ilumina (I think...), you will start getting randomly the same mutation twice. You can see that the number of canonized k-mers is 2.7B but the genome size is 1.2B, which mean more than 50% of the canon k-mers are probably due to sequences errors. 

Let me know how it goes, and if the increase memory doesn't do the trick I would need the kmc_canon and kmc_all from one accession to fix it or understand what is going on.

Best,
Yoav

**Comment by fanmiaowang** [comment]
Hi Yoav,

> * It is a memory error, but it is not clear it is out of memory or trying to accesses a wrong address in the memory. There is no need to to request 32 threads as this step is run only on one thread. Can you run it with much more memory and see if it solves the issue?

I checked the memoty usage by ulimit -m. It is unlimited. 
 
> * Do the kmers_add_strand_information print "Canonized kmers:...." before it crashes? Does it print other things before it crashes? (this will be an indication to which step in the code fails).

Since I submit the job by qsub. And the "Canonized kmers:...." does not show in my standout or error message.

> * Regardless of the issue you raised, as the coverage is so high I would recommend to increase the threshold for the number of appearances of a k-mer to be counted (in canonized form), at least to 4-5 to begin with, so kmc -t32 -ci5 -k31 @S001.txt kmc_canon. If coverage is very high, especially for nanopore which should have more mutations than Ilumina (I think...), you will start getting randomly the same mutation twice. You can see that the number of canonized k-mers is 2.7B but the genome size is 1.2B, which mean more than 50% of the canon k-mers are probably due to sequences errors.

Thank you very much for your suggestion. I increased the threshold for the number of appearances of a k-mer to 5. The number of canonized k-mers reduced to 0.8B. Then, I tried to combine kmc_canon and kmc_all again by qsub, I still got the same error: core dumped... But, when I submit by nohup, I got the kmers_with_strand output and below is my nohup out.
anonized kmers:        878410514
Non-canon kmers:        31527384906
Non-canon kmers found:  1529108568
flag    0       count is        0
flag    1       count is        108389557
flag    2       count is        119322903
flag    3       count is        650698054
kmers to save:  878410514

So, what do you think of the possible reason?

Thanks,
Fanmiao

**Comment by voichek** [comment]
Dear Fanmiao,

From the information you gave me it is most likely that the memory is limited. The memory is always limited and you can check and compare how much memory was used relative to the memory provided. 

Regardless, I would put the limit in the kmc_canon higher than 2, I would go for 4 or 5.

Yoav

**Comment by voichek** [comment]
Can we close this issue?

**Comment by fanmiaowang** [comment]
Yes, Thank you Yoav.
