### ISSUE TITLE
Error in filter_kmers

### ISSUE THREAD

**Issue by voichek** [voichek/kmersGWAS#13]
Hello,
I still can not run filter_kmers functionality well.  I used command as following:
filter_kmers -t kmers_table -k LePR1/kmers/output/phenotype_value.assoc.txt -o ll1
I got the error is as following:
terminate called after throwing an instance of 'std::logic_error'
  what():  Ilegal kmer
Aborted (core dumped)
I think I should use a wrong associated kmer table. But I can not figure out this table. Coudl you suggest which table is assocated kmers table for parameter -k.
Thanks,
Fuyou

_Originally posted by @sunnycqcn in https://github.com/voichek/kmersGWAS/issues/5#issuecomment-620331148_

**Comment by voichek** [comment]
Dear Fuyou,

I made this a new issue as it is not related to the original thread.

```
bin/filter_kmers  --help
Output the presence/absence patterns of set of k-mers from the k-mers table
Usage:
  filter_kmers [OPTION...]

  -t, --kmers_table arg  k-mers table path
  -k, --kmers_file arg   file with k-mers, each k-mer in a seperate line
  -o, --output arg       output file
      --help             print help
```

You need to input a _k_-mers file with a _k_-mer in each separate line.

This is not the format of `LePR1/kmers/output/phenotype_value.assoc.txt`.

BTW, the _k_-mers found in `...kmers/output/phenotype_value.assoc.txt` are not the   _k_-mers which passed the threshold, but just the _k_-mers filtered in the first step of the pipeline.

Yoav

**Comment by sunnycqcn** [comment]
I got it.
Thanks,
Fuyou
