### ISSUE TITLE
Step 1 issue

### ISSUE THREAD

**Issue by vunguyen1907** [voichek/kmersGWAS#131]
Hi. I am running step 2 "kmc -t2 -k31 -ci2 @input_files.txt output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2" as manual but unsuccessful. 
My data have 49 individuals with paired-end reads (both reverse and forward reads files are about 10 Gb), running on my laptop with 32 GB RAM using the ubuntu subsystem on Win 11. Process & save raw data from an external hard drive of 16 TB.

Every time it runs to the size of each kmc of about 2.5 GB (510 kmcs), the whole system is pending and failed as the RAM is almost 95% used.

I have restarted my lap several times and also use fewer cores, i.e., 10/20 CPU but still does not work.

Are there any suggestions on how to overcome this?

Thanks,
Vu

**Comment by voichek** [comment]
Dear Vu,

I am sorry but I don't think I can help you with that. I would recommend trying to ask in the KMC GitHub page if there are ways to make the KMC less memory intensive.

In general, building the basic k-mers-table is the most memory intensive, so if you find a different machine to do it, then running the GWAS itself will need less resources.

Best,
Yoav

**Comment by vunguyen1907** [comment]
Thanks Yoav
