### ISSUE TITLE
kmers_add_strand_information can not finish

### ISSUE THREAD

**Issue by vunguyen1907** [voichek/kmersGWAS#132]
Hi Yoav,

In previous issues running with kmc, I solved it as:
./kmersGWASv0_3_beta/external_programs/kmc_v3 -k31 -ci2 -sm -fq @input_files.txt output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2
and 
./kmersGWASv0_3_beta/external_programs/kmc_v3 -k31 -ci0 -b -sm -fq @input_files.txt output_kmc_all ./ 1> kmc_all.1 2> kmc_all.2

However I faced another problem when combining them, the log error and photo attached.
This failed after running for around 6 hours.

Any suggestion to overcome this much appreciated.

./kmersGWASv0_3_beta/bin/kmers_add_strand_information -c output_kmc_canon -n output_kmc_all -k 31 -o kmers_with_strand
kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.
Aborted (core dumped)

Vu

![issue_kmerGWAS](https://user-images.githubusercontent.com/79078602/226271565-dbd6b42b-8303-454d-84ad-1c2859eaf9e1.png)

**Comment by vunguyen1907** [comment]
Hi Yoav,

I think so, is there any way to use less memory?

I requested kmersGWAS to be installed on HPC. Can your tools can install on
HPC? Any note how to install it on HPC?

Regards,

Vu

**Comment by voichek** [comment]
Dear Vu,

Not in this steps, at least not without real modifications to the code.

Yes, these tools are intended to use on HPC setup. Of course every system is a bit different. In any case, for this function there is no need for any installation and the executable should work. There is only a dependency on the C++ library in the environment. I would start with just trying to run it in your system and if there is an error ask if you can load a newer gcc library.

Best,
Yoav

**Comment by vunguyen1907** [comment]
Dear Yoav,

I had an error when trying to compile on HPC by myself in the
meantime waiting for HPC staff, not sure if this is an incompatible package
on HPC.

make

mkdir -p build

# The -MMD flags additionaly creates a .d file with

# # the same name as the .o file

g++ -std=c++14 -Wall -O3 -I ./include/ -pthread -msse4.2  -MMD -c
src/kmers_multiple_databases.cpp -o build/kmers_multiple_databases.o

g++: error: unrecognized command line option '-std=c++14'

make: *** [build/kmers_multiple_databases.o] Error 1

Again, I wonder if the compiling codes can be changed a little to make it
work.

Regards,
Vu
ᐧ

**Comment by voichek** [comment]
Hi Vu,

This is what I mentioned before, it requires c++ standard library 14 and above. You don't need to compile as you can use the precompiled release, but you will still need a c++ standard library version 14 or above. Ask your IT for help with this, you might be able to load it with a simple command, but this is system specific.

Best,
Yoav

**Comment by vunguyen1907** [comment]
Dear Yoav,

My problem is solved now as it was installed in the HPC.

Thanks for bearing with me on this.

Regards,

Vu




ᐧ
