### ISSUE TITLE
Can we include population structure data in GEMMA?

### ISSUE THREAD

**Issue by laurenhamm** [voichek/kmersGWAS#133]
I am hoping to increase the quality of my GWAS by including population strucure information, namely PC1 and PC2 coordinates for my dataset. Is there a way to incorporate this information into my kmers_gwas.py GEMMA run?

**Comment by voichek** [comment]
Hi,

First, population structure is being accounted for by the kinship matrix. 

Second, for now you can not add a covariate to the _k-mers_ GWAS, this can be done theoretically, but it needs to be programmed.
