### ISSUE TITLE
issues with kmers_add_strand_information

### ISSUE THREAD

**Issue by vunguyen1907** [voichek/kmersGWAS#134]
HI Yoav,

My error is as below when running kmers_add_strand_information.

[jc944397@ln01:8 kmerGWASv0_3_beta]% kmers_add_strand_information -c output_kmc_canon -n output_kmc_all -k 31 -o kmers_with_strand
kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.
Aborted

After running for long (i.e., one hour) it failed as the above message.

Regards,
Vu

**Comment by voichek** [comment]
Dear Vu,

Can you share the output_kmc... files so I can reproduce this?

- You used the `kmers_add_strand_information` before as I recall, what is different in this run vs. the previous one?
- It is likely that you run out of memory, did you check that ?

Yoav

**Comment by vunguyen1907** [comment]
Hi Yoav,

Before I ran it on my laptop and it did not have enough memory and now I
ran it in HPC system.
I used an interactive terminal to run it, not job submission and the max
resource I can use is up to 40 cores and 380 GBs so I thought it was not an
issue with memory.

I am not sure how to share with you the output_* files as 4 of it is nearly
500 GBs

-rw-rw-r-- 1 jc944397 jc944397  17G Apr 18 15:30 output_kmc_all.kmc_pre
-rw-rw-r-- 1 jc944397 jc944397 339G Apr 18 15:30 output_kmc_all.kmc_suf
-rw-rw-r-- 1 jc944397 jc944397  17G Apr 18 06:11 output_kmc_canon.kmc_pre
-rw-rw-r-- 1 jc944397 jc944397  72G Apr 18 06:11 output_kmc_canon.kmc_suf

It was generated from 49 individuals (24 males, 25 females) having WGRS
data (paired-end reads).

Regards,
Vu

ᐧ

**Comment by voichek** [comment]
Dear Vu,

Just to make sure, you run it on each individual separately, right?

Best,
Yoav

**Comment by vunguyen1907** [comment]
Dear Yoav,

Umh. I think so.

The @input_files contains the list of the path of 2 reads of each sample as
the same as the manual.

Cheers,
Vu





ᐧ

**Comment by voichek** [comment]
Dear Vu,

And for each accession it is 500GB? What is the genome size and coverage more or less?

Best,
Yoav

**Comment by vunguyen1907** [comment]
Dear Yoav,

Genome size is around 1 TB, and the coverage of each sample is around 17X.

The raw data of each sample in fastq file (pair-end) is approx 20-30 Gbs.

Do you think there is an issue with the installation of kmersGWAS on HPC?
If yes I will post the error log for them to investigate or re-install it.

Regards,
Vu



ᐧ

**Comment by voichek** [comment]
Hi Vu,

I guess you mean 10^9 genome? anyway it doesn't sound so extreme. Can you please try to run example 2 in our library to see you are doing everything in the right way.

Also, if you can share with me one of the read files which is smaller I can also try to run this step on it.

Best,
Yoav

**Comment by vunguyen1907** [comment]
Dear Yoav,

Sorry, the genome size is 1 GB,

Will give a try on your example and let you know the outcome

Thanks,
Vu


ᐧ

**Comment by vunguyen1907** [comment]
Dear Yoav,

Yes, you can close this.

I was successfully running the workflow now, using Kmer count on each
individual

Sorry for this confusion.

Regards,

Vu

ᐧ
