### ISSUE TITLE
running SNP gwas with gemma/0.98 fails

### ISSUE THREAD

**Issue by laurenhamm** [voichek/kmersGWAS#136]
I am able to successfully run the kmer GWAS using gemma/0.98 and the updated changes made to kmers_gwas.py. However, once I add in the --run_on_snps_one_step and --snp_matrix parameters, I get the same gcc/r incompatability error that I was receiving without the updated kmers_gwas.py and gemma/0.98 modifications. See below:

------
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: as.matrix -> read.csv -> read.table
Execution halted
Traceback (most recent call last):
  File "/global/scratch/users/laurenhamm/thesis/aim1/software/kmersGWAS_v2/kmers_gwas.py", line 278, in <module>
    main()
  File "/global/scratch/users/laurenhamm/thesis/aim1/software/kmersGWAS_v2/kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: '/global/scratch/users/laurenhamm/thesis/aim1/fastq/GWAS_files/SNPSnKMERS/Bio19/pheno.phenotypes_and_permutations'
---------------

Why is the addition of the snp parameters throwing this error?

**Comment by voichek** [comment]
1. I don't see any GCC error in what you posted.
2. Please post here the exact command you run.

**Comment by laurenhamm** [comment]
1. The gcc error is never explicitly listed, but I hit that same error before with my kmer run, and the solution was to try and fix the gcc/r version incompatibility on my remote server connection. However, the same code which works with kmers doesn't work with snps.
2. sorry! I forgot to include the command. (important info: i am running things on my own installation of gemma/0.98 using the updated files listed on github). See below:

python2.7 /path/to/kmers_gwas.py --pheno /path/to/phenotypes.pheno --kmers_table /path/to/kmers_table -l 31 -p 24 --run_on_snps_one_step --snp_matrix /path/to/rootname/23grandest_filtered --gemma_path ~/GEMMA-0.98.5/bin/gemma --outdir /path/to/outname

**Comment by voichek** [comment]
Please zip the output directory and upload it here.

**Comment by laurenhamm** [comment]
[error_output.tar.gz](https://github.com/voichek/kmersGWAS/files/11456839/error_output.tar.gz)

Here is the output from the failed run that throws the above error

**Comment by laurenhamm** [comment]
I went back and double-checked. The sample names are the same in both files and also in the same order. When I run it, I still get the same error.
Ren

**Comment by voichek** [comment]
Dear Ren,

Given that the primary focus of this library is k-mers-based GWAS, I would advise you to use GEMMA directly for conducting SNP-based GWAS. As the maintainer of this library, I am contemplating the removal of the SNP functionality from the code in the future, as it may not be necessary to support this feature within the scope of this library. In your particular scenario, it appears the best course of action would be to execute GEMMA independently. You should be able to use the existing kinship matrix and modify the phenotype file to match GEMMA's input format.

I apologize if I can't provide more detailed assistance at this moment. It seems that the issue might stem from inconsistencies in accession names or possibly a missing file.

Best wishes,
Yoav
