### ISSUE TITLE
kmers_table_to_bed

### ISSUE THREAD

**Issue by xbarvazx** [voichek/kmersGWAS#138]
Hi,

I am trying to use 'kmers_table_to_bed', the functions worked well with an output split into five.
I found a reference here for using 'plink' to merge the files into one but it seems to be very very slow (with each bed and bim files weighing 40-60Gb), do you have any better way and/or a working example?

`plink --bfile HD_table.output.0 --merge-list plink.list --make-bed --out HD_table_merged`

`HD_table.output.0.bed HD_table.output.0.bim HD_table.output.0.fam`
`HD_table.output.1.bed HD_table.output.1.bim HD_table.output.1.fam`
`HD_table.output.2.bed HD_table.output.2.bim HD_table.output.2.fam`
`HD_table.output.3.bed HD_table.output.3.bim HD_table.output.3.fam`
`HD_table.output.4.bed HD_table.output.4.bim HD_table.output.4.fam`

Ultimately, I would like to extract the P/A matrix for significant kmers.

Best,
Raz

**Comment by voichek** [comment]
Dear Raz,

1. You can put a very large number in the `-b` option in the `kmers_table_to_bed` and it will create one output file.
2. If you only need kmers P/A of significant kmers, you can use the `filter_kmers` with the list of significant kmers from the pipeline.


Hope it helps,
Yoav

**Comment by xbarvazx** [comment]
Hi Yoav,

What could be the reason that the kmers in the list dont match the kmers found by `kmers_table_to_bed`? 
I noticed there was a fix in beta v3 but it does not seem to work in this case.

Best,
Raz

**Comment by xbarvazx** [comment]
Dear Yoav,

`filter_kmers -t $table -k $kmers -o $out`

`$kmers` is 
`AAAGGACCGAGGCAAGGAGATCCACTATCGC`
`AACATTTCGAGCAGTGGTAACAACAAATTGG`
`AAGCATGACGTTTTAGGCATAGTTTTGTTTC`
`AATTGTTTGGATTGAGGAATTTCAATGGGTT`
`AGCCGGGATCTGAGGACAAGTAAGAGTGGTT`
`ATAAGCATGACGTTTTAGGCATAGTTTTGTT`
`GATGTCAAGGAAAATTTTCATGTATCTTCTT`
`TAAGCATGACGTTTTAGGCATAGTTTTGTTT`
`TCGATTCTCGCAACGCCCCATTTTTTGCTTT`
`TCGGATGTCAAGGAAAATTTTCATGTATCTT`

and the output I get is (only the first column from the VCF)
`AAACAAAACTATGCCTAAAACGTCATGCTTA`
`AAAGCAAAAAATGGGGCGTTGCGAGAATCGA`
`AAAGGACCGAGGCAAGGAGATCCACTATCGC`
`AACAAAACTATGCCTAAAACGTCATGCTTAT`
`AACATTTCGAGCAGTGGTAACAACAAATTGG`
`AACCACTCTTACTTGTCCTCAGATCCCGGCT`
`AACCCATTGAAATTCCTCAATCCAAACAATT`
`AAGAAGATACATGAAAATTTTCCTTGACATC`
`AAGATACATGAAAATTTTCCTTGACATCCGA`
`AAGCATGACGTTTTAGGCATAGTTTTGTTTC`

I expected to get the P/A for the kmers in the kmers list I provided in `-k`

The table size is 414G and I am having trouble converting it all to a VCF (and no real need at the moment).

Thanks and let me know if you need any more details.
Raz

**Comment by voichek** [comment]
Dear Raz,

The two lists you posted are the same, just some _k-mers_ are shown in the reverse complement. As explained in the manual we canonize the _k-mers_.

Best,
Yoav

**Comment by xbarvazx** [comment]
Yoav, 
Thanks for the calrification :)
