### ISSUE TITLE
Output file phenotype_value.assoc.txt

### ISSUE THREAD

**Issue by SofiavanMoorsel** [voichek/kmersGWAS#140]
Dear Yoav

I have a question regarding the output that is generated at the end of the pipeline. The phenotype_value.assoc file has column names called like this: chr | rs | ps | n_miss | allele1 | allele0 | af | logl_H1 | l_mle | p_lrt (see attachment).

I could not find an explanation of what these column names mean. I assumed that p_lrt is a p-value. However, in my case, these values are all extremely low (around 8.74E-07) even though the output folders (pass_threshold_5per, pass_threshold_10per) with the significant kmers passing the threshold (which is 5.000, so much higher than any of my p-values) is empty. So I assumed that I don't have any significant kmers. 

Many thanks for your help,
Sofia

[phenotype_value.assoc_car.txt](https://github.com/voichek/kmersGWAS/files/11742092/phenotype_value.assoc_car.txt)

Below the information on the GWAS run
```
##
## GEMMA Version    = 0.98.3 (2020-11-28)
## Build profile    =
## GCC version      = 7.5.0
## GSL Version      = 2.6
## OpenBlas         = OpenBLAS 0.3.9  - OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=128
##   arch           = Zen
##   threads        = 2
##   parallel type  = threaded
##
## Command Line Input = folder/Sofia/kmer/external_programs/gemma_0_96 -bfile output_dir_20230606140225/kmers/pheno.0.phenotype_value -lmm 2 -k output_dir_20230606140225/pheno.kinship -outdir output_dir_20230606140225/kmers/output -o phenotype_value -maf 0.050000 -miss 0.5
##
## Date = Tue Jun  6 14:48:20 2023
##
## Summary Statistics:
## number of total individuals = 179
## number of analyzed individuals = 179
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var = 10001
## number of analyzed SNPs/var = 10001
## REMLE log-likelihood in the null model = 199.191
## MLE log-likelihood in the null model = 204.405
## pve estimate in the null model = 2.99602e-06
## se(pve) in the null model = 0.214028
## vg estimate in the null model = 6.24492e-08
## ve estimate in the null model = 0.00624492
## beta estimate in the null model =   5.42745e-18
## se(beta) =   0.00590659
##
## Computation Time:
## total computation time = 0.0216052 min
## computation time break down:
##      time on eigen-decomposition = 0.000638617 min
##      time on calculating UtX = 0.000834717 min
##      time on optimization = 0.0164597 min
##
```

**Comment by SofiavanMoorsel** [comment]
Dear Yoav
Thank you very much for your quickly reply.
Via this link you can find the output folder: https://www.dropbox.com/scl/fo/qtseosxvl47t732168y1e/h?dl=0&rlkey=97mu66tzuksq441qa4y1xfwxn

Many thanks!

Best wishes
Sofia



On 15 Jun 2023, at 09:19, Yoav Voichek ***@***.***> wrote:



Dear Sofia,

We use GEMMA in the background, and this is an output file generated by GEMMA. You can find details in the GEMMA manual<https://www.xzlab.org/software/GEMMAmanual.pdf>. p_lrt is indeed the p-value, and if the threshold is 5 you should have this k-mers passing it and found in the pass_threshold_10per/5per file.

You have the threshold the program is using in the threshold_* files, this is where you take the 5.00? Can you send me a zip of the output directory of this run to look?

Best,
Yoav

**Comment by voichek** [comment]
Dear Sofia,

Thanks for providing the output directory.
Indeed, something doesn't seem right. 

I see in the output you provided that you used GEMMA version 0.98. Did you change the gemma version in 'external_programs/gemma_0_96' to GEMMA v0.98?

If so, did you use the [patch](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) for version 0.98?

Best,
Yoav

**Comment by SofiavanMoorsel** [comment]
Hi Yoav

Yes, as you suspected, I changed the gemma version, following the approach here: https://github.com/voichek/kmersGWAS/issues/70
"I took the 0.98.3 executable and put it in the 'external_program' folder and change it name to gemme_0_96 (and removed the original)." 

But I didn't also replace the patch files that you indicated. Do you think by replacing these two files in the replacement.zip folder it should work? Or do I have to then return to GEMMA 0.96?

Thanks for identifying the issue!

Best,
Sofia

**Comment by voichek** [comment]
Dear Sofia,

If you change the two python files from replacement.zip the and rerun the pipeline with GEMMA 0.98 it should work. 

Let me know if this solves the issue.

Best,
Yoav

**Comment by SofiavanMoorsel** [comment]
Hi Yoav

I changed the two python files and have also downloaded GEMMA 0.98 again. But, now I'm getting a couple of errors, which both seem to be associated with the files I just exchanged. 

affective MAF = 0.05
Traceback (most recent call last):
  File "/home/svanmo/shares/Sofia/kmer/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/svanmo/shares/Sofia/kmer/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/shares/schuman.geo.uzh/Sofia/kmer/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0

Is there something I still overlooked? 

Thank you,
Sofia

**Comment by voichek** [comment]
Hi Sofia,

Sorry for the late response, we were on holidays.

I would suspect that it cannot find the GEMMA, did you give it exactly the same name as the gemma file had before?

Best,
Yoav

**Comment by SofiavanMoorsel** [comment]
Hi Voichek
I hope your holidays were great!

Yes, it's called gemma_0_96 (but is in reality gemma 0.98.1)

path/Sofia/kmer/external_programs$ ls
gemma_0_96  kmc_v3

But still getting the same error message. I now added the --gemma_path parameter (but not sure if I did it the right way), but this also did not help. I looked at the source code but am definitely not experienced enough to find the issue.

My job file:
python2.7 /home/svanmo/shares/Sofia/kmer/kmers_gwas.py --pheno pheno.txt \
--kmers_table kmers_table -l 31 -p 8 --outdir "$output_dir" --dont_remove_intermediates --gemma_path /home/svanmo/shares/Sofia/kmer/external_programs/gemma_0_96

**Comment by voichek** [comment]
Can you send me the output directory zipped?

**Comment by SofiavanMoorsel** [comment]
Dear Yoav
Sorry for my late reply. Attached is the zipped output directory. Thank you!
Best,
Sofia

[output_dir.zip](https://github.com/voichek/kmersGWAS/files/11914121/output_dir.zip)

**Comment by voichek** [comment]
Dear Sofia,

You get an error (which is found in the associate_kmers.log)
```
/shares/schuman.geo.uzh/Sofia/kmer/bin/associate_kmers: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /shares/schuman.geo.uzh/Sofia/kmer/bin/associate_kmers)
/shares/schuman.geo.uzh/Sofia/kmer/bin/associate_kmers: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /shares/schuman.geo.uzh/Sofia/kmer/bin/associate_kmers)
```

It mean that you don't have an updated enough c++ library (as in [this issue](https://github.com/voichek/kmersGWAS/issues/125#issuecomment-1255585871)). It is peculiar as you were able to run the pipeline before - which mean you changed something in the system you run it. You need to update this in your system, or if you are using a `module load` you might be able to just load a newer GCC library. In any case try to go back to the same configuration you had before.

Best,
Yoav

**Comment by voichek** [comment]
Dear Sofia,

Can we close this issue?

Best,
Yoav

**Comment by voichek** [comment]
I am closing it, feel free to reopen if needed.
