### ISSUE TITLE
Is it usual for kmc_canon.2 and kmc_all.2 to be empty after step 2?

### ISSUE THREAD

**Issue by tommydavies** [voichek/kmersGWAS#141]
Hey there. 

I am running kmersGWAS. After step 2, the kmc_canon.2 and kmc_all.2 files always seem to be empty. Is this usual? 

Here is the command I am running: 
path/to/kmc_v3 -k31 -ci2 @input_files.txt output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2
and 
path/to/kmc_v3 -t2 -k31 -ci0 -b @input_files.txt output_kmc_all ./ 1> kmc_all.1 2> kmc_all.2

No error codes are produced, and the kmc_canon.1 and kmc_all.1 files seem fine (stages 100% complete). Log files from submitting the job on a HPC show no errors. 

I fear that there is something is going wrong which I cannot detect. 

Is this normal?

Thanks in advance, 
Tommy

**Comment by voichek** [comment]
Dear Tommy,

Yes, this is the same behaviour I used to get.
As the `.2` files contain the std-error, if they are not empty might indicate a problem. 

I am closing the issue for now, re-open if there is anything else with this I can help with.

Cheers,
Yoav
