### ISSUE TITLE
question about kmers_add_strand_information

### ISSUE THREAD

**Issue by Lucylalala** [voichek/kmersGWAS#145]
Hello, I have a question about kmers_add_strand_information. 

When I run` nohup kmers_add_strand_information -c R4 -n R4_all -k 31 -o kmers_R4_with_strand &`, after a long time,  the program terminated, the output information in the log file is “kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.”. How to solve this?

**Comment by Lucylalala** [comment]
-rwxrwxrwx 1 pub3114 pub3114  66M Sep 29 04:12 R4.kmc_pre
-rwxrwxrwx 1 pub3114 pub3114  41G Sep 29 04:12 R4.kmc_suf
-rwxrwxrwx 1 pub3114 pub3114  47M Oct  1 16:35 R4_all.kmc_pre
-rwxrwxrwx 1 pub3114 pub3114 110G Oct  1 16:35 R4_all.kmc_suf

**Comment by voichek** [comment]
Do you run the KMC on each sample separately? The file sizes looks extremely large...

**Comment by Lucylalala** [comment]
I ran the KMC on each sample separately. My sample is wheat, and the sequencing depth is 20X.


小太阳?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "voichek/kmersGWAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午3:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [voichek/kmersGWAS] question about kmers_add_strand_information (Issue #145)





 
Do you run the KMC on each sample separately? The file sizes looks extremely large...

**Comment by voichek** [comment]
It probably failed due to running out of memory - did you check if this is the case?

If you have 20x I would recommend increasing the threshold on the number of times a _k_-mer need to appear to be counted in the canonical counts. Maybe change `-ci2` to `-ci4`, it will clean your data as well as decrease the memory load.

Yoav

**Comment by Lucylalala** [comment]
Thank you for your kind reply. I also think that it may be caused by insufficient running memory. I will try again.


小太阳?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "voichek/kmersGWAS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [voichek/kmersGWAS] question about kmers_add_strand_information (Issue #145)





 
It probably failed due to running out of memory - did you check if this is the case?
 
If you have 20x I would recommend increasing the threshold on the number of times a k-mer need to appear to be counted in the canonical counts. Maybe change -ci2 to -ci4, it will clean your data as well as decrease the memory load.
 
Yoav
