### ISSUE TITLE
Error: No such file or directory: 'pheno.phenotypes_and_permutations'

### ISSUE THREAD

**Issue by viannam** [voichek/kmersGWAS#146]
Hi Voichek,
I am running kmers_gwas.py and getting an error. I would appreciate it if you could help. 

My loads:
module load kmc/3.1.1
module load R/4.1
module load gemma/0.98.1
module load gcc/9.3.0
module load bamtools

My command: python2.7 kmers_gwas.py --pheno GER_21.pheno --kmers_table ./kmers_table -l 31 -p 8 -k 100000 --dont_remove_intermediates --maf 0.01 --pattern_counter --outdir ./GER_21
All input files exist and are listed in the same folder.

The error:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: as.matrix -> read.csv -> read.table
Execution halted
Traceback (most recent call last):
  File "kmers_gwas.py", line 278, in <module>
    main()
  File "kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: './GER_21/pheno.phenotypes_and_permutations'

**Comment by voichek** [comment]
Dear Mariana,

1. Are the names in the phenotype file written the same as in the k-mer table?
2. If you send me the output folder of the failed run, I might be able to understand what went wrong.

Best,
Yoav

**Comment by viannam** [comment]
Dear @voichek,

Thank you for getting back to me.
My ID names on accetion_ID of the phenotype file were between quotes. I fixed it and reran it.
However, I got another error. Idk if you preferer that I open another issue, but here it is:
Error file:
/blue/mresende/share/viannam/Kmers/external_programs/gemma_0_96: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "kmers_gwas.py", line 281, in <module>
    main()
  File "kmers_gwas.py", line 250, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/blue/mresende/share/viannam/Kmers/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'

Output file:
cat kmers_16471653.out
Rscript /blue/mresende/share/viannam/Kmers/src/R/transform_and_permute_phenotypes.R ./germ_21/pheno.phenotypes ./germ_21/pheno.kinship 100 ./germ_21/pheno.phenotypes_and_permutations ./germ_21/pheno.phenotypes_permuted_transformed ./germ_21/EMMA_perm.log > ./germ_21/phenotypes_transformation_permutation.log
affective MAF = 0.01

Files generated on the trait outdir:
kmers
log_file
associate_kmers.log
EMMA_perm.log
pheno.phenotypes_and_permutations
pheno.phenotypes_permuted_transformed
pheno.kinship
pheno.phenotypes
phenotypes_transformation_permutation.log

Log file:
 head log_file
Namespace(fn_phenotype='GER_21.pheno', gemma_path='/blue/mresende/share/viannam/Kmers/external_programs/gemma_0_96', kmers_len=31, kmers_pattern_counter=True, kmers_table='./kmers_table', mac=5, maf=0.01, min_data_points=30, n_extra_phenotype_kmers=None, n_kmers=100000, n_permutations=100, n_snps=10001, outdir='./germ_21', parallel=8, remove_intermediate=False, run_kmers=True, run_one_step_snps=False, run_two_steps_snps=False, snps_matrix=None, use_kinship_from_kmers=True)Multiple phenotypes found per accessions -> Averaging
Using kinship calculated on k-mersRUN: python2.7 /blue/mresende/share/viannam/Kmers/src/py/align_kinship_phenotype.py --pheno ./germ_21/pheno.original_phenotypes --fam_file ./germ_21/pheno_for_accessions_order.fam --kinship_file ./kmers_table.kinship --output_pheno  ./germ_21/pheno.phenotypes --output_kinship ./germ_21/pheno.kinship --DBs_list ./kmers_table.names
RUN: Rscript /blue/mresende/share/viannam/Kmers/src/R/transform_and_permute_phenotypes.R ./germ_21/pheno.phenotypes ./germ_21/pheno.kinship 100 ./germ_21/pheno.phenotypes_and_permutations ./germ_21/pheno.phenotypes_permuted_transformed ./germ_21/EMMA_perm.log > ./germ_21/phenotypes_transformation_permutation.log
RUN: mkdir ./germ_21/kmers
RUN: /blue/mresende/share/viannam/Kmers/bin/associate_kmers -p ./germ_21/pheno.phenotypes_permuted_transformed -b pheno -o ./germ_21/kmers -n 100000 --parallel 8 --kmers_table ./kmers_table --kmer_len 31 --maf 0.010000 --mac 5 --pattern_counter 2> ./germ_21/associate_kmers.log
We have 101 phenotypes
RUN: mv ./germ_21/kmers/pheno.0.phenotype_value.fam ./germ_21/kmers/pheno.0.phenotype_value.fam.orig
RUN: cat ./germ_21/pheno.phenotypes_and_permutations | tail -n +2 | awk '{print $1 " " $1 " 0 0 0 " $2}' > ./germ_21/kmers/pheno.0.phenotype_value.fam
RUNG (1/1): /blue/mresende/share/viannam/Kmers/external_programs/gemma_0_96 -bfile ./germ_21/kmers/pheno.0.phenotype_value -lmm 2 -k ./germ_21/pheno.kinship -outdir ./germ_21/kmers/output -o phenotype_value -maf 0.010000 -miss 0.5
RUN: mv ./germ_21/kmers/pheno.1.P1.fam ./germ_21/kmers/pheno.1.P1.fam.orig

It should be 693 individuals. Does kmers_table.names file show the correct order of the genotypes in the kinship?

**Comment by voichek** [comment]
Dear Mariana,

In general, it is better to open a new topic for another problem. But let's close this one here.

It seems that you cannot run the gemma that comes with the library `/blue/mresende/share/viannam/Kmers/external_programs/gemma_0_96`. 
1. You can try running it from the command line with no arguments to make sure this is the problem.
2. I saw before that you load gemma 0.98, you can tell the program to use your gemma (by just telling it the path to it is `gemma`, which is how I assume you are running it from the command line. However, if you want to use gemma 0.98, you need to change the files using a [patch](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) I made in the past.

Let me know if this helps,
Yoav

**Comment by voichek** [comment]
Dear Mariana,

Can you clarify, you tried running just this command: `/blue/mresende/share/viannam/Kmers/kmersGWAS/external_programs/gemma_0_96` 
and it gave the error:
 `error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory` 
after running for 11 hours?

Yoav

**Comment by viannam** [comment]
To clarify,

I ran this command:
python2.7 kmers_gwas.py --pheno GER_21.pheno --kmers_table kmers_table -l 31 -p 8 -k 100000 --dont_remove_intermediates --maf 0.01 --pattern_counter --outdir test_germ

After copying the kmersGWAS library to my folder again. Now, gemma_0_96 is listed on external_programs folder:
[viannam@login10 kmersGWAS]$ ls external_programs/
gemma_0_96  kmc_v3

I got this error:

/blue/mresende/share/viannam/Kmers/kmersGWAS/external_programs/gemma_0_96: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./kmers_gwas.py", line 278, in <module>
    main()
  File "./kmers_gwas.py", line 247, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/blue/mresende/share/viannam/Kmers/kmersGWAS/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'

I guess this message "/blue/mresende/share/viannam/Kmers/kmersGWAS/external_programs/gemma_0_96: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory" repeated through all individuals and that is why it took 11 hours. But also, it should be 693 genotypes, and not only 101 as listed in the log file.

My genotypes ID (accession_ID column on the pheno file) should be in the same order as the kmers_table.names file?

**Comment by viannam** [comment]
If I load the modules like this:
module load kmc/3.1.1
module load R/4.1
module load gcc/9.3.0
module load bamtools
module load libgfortran

I get this error:
Lmod is automatically replacing "R/4.1" with "libgfortran/3.0.0".

sh: Rscript: command not found
Traceback (most recent call last):
  File "kmers_gwas.py", line 278, in <module>
    main()
  File "kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'test_germ_02/pheno.phenotypes_and_permutations'

**Comment by voichek** [comment]
Dear Mariana,

I am sorry, but I just missed this last comment from you. Is it still an issue for you?

Sorry,
Yoav

**Comment by voichek** [comment]
I will close this issue, please reopen if needed.

**Comment by viannam** [comment]
Dear Dr. Voichek,
I installed gemma 0.98 and used the [patch](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) that you recommend and I was able to run the GWAS. Thank you very much.
Best,
