### ISSUE TITLE
Subset genotypes for Kinship matrix

### ISSUE THREAD

**Issue by nirwan1265** [voichek/kmersGWAS#147]
Hi Yoav,

I am trying to run a kmergwas on 15,000 genotypes. Is there a way I could subset the genotypes that is used for the kinship calculation?

**Comment by voichek** [comment]
Hi Nirwan,

I don't have experience working with that many individuals (never got past 2,000). Out of curiosity, did you manage to create the k-mers table? did you encounter any challenges?

Regarding calculating kinship matrix on a subset of individuals, the implementation doesn't have that option now. I would guess that the easiest option to implement would be a functionallty that will subset the k-mers-table itself (this would mean going into the C++ code). One solution, if you have a SNP-based kinship (you can also create this with this library) is to provide this kinship matrix (just make sure you keep the same order of individuals and format).

Best,
Yoav
