### ISSUE TITLE
no significant k-mer from flowering_time_arabidopsis

### ISSUE THREAD

**Issue by yiwenwang25** [voichek/kmersGWAS#149]
Hi Yoav,

I tried my own dataset and the example (flowering_time_arabidopsis) but couldn't get any significant k-mer output from kmers_gwas.py. 
I only added --gemma_path to Gemma v.0.98.5. The script finished fine without any errors, but both threshold_5per and threshold_10per were 0.000000 and best_pvals were all 0.

Do you have any suggestions to troubleshoot this?

Thank you!

**Comment by voichek** [comment]
Hi,

It seems this is an issue with the GEMMA version compatibility with the _k_-mers-GWAS.
Please try to rerun with the [patch](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) I made for GEMMA 0.98.

Let me know if it fixes the issue.
Yoav

**Comment by yiwenwang25** [comment]
Hi Yoav,

The patch fixed the issue. Thanks a lot!

**Comment by DavideGue** [comment]
Hi Yoav,
I'm getting the same problem. I Tried wit gemma_96/98.1/98.5 with and without patches. However, the threshold_5per and threshold_10per were 0.000000 and best_pvals were all 0. The pass_threshold files are both empty. On the other end in the output folder I found gzipped archive containing the phenotype_value.assoc.txt file with kmers and p_value. Is this behaviour of the pipeline correct?

**Comment by voichek** [comment]
Hi Davide,

If the threshold_10per is 0 it means something is wrong by how the gemma output is read. 

Make sure that you use the GEMMA version you think, can you try to run it with GEMMA 0.96 and look at the file `output_dir/kmers/output/phenotype_value.log.txt` and see you indeed use version 0.96? 
(try this after downloading the library again to make sure you do not use the patch...)

Best,
Yoav

**Comment by DavideGue** [comment]
Hi Yoav,
I followed your suggestions and got the following errors:
/home/v0_3_beta/external_programs/gemma_0_96: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/v0_3_beta/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/v0_3_beta/kmers_gwas.py", line 247, in main
    th_5per = get_threshold_from_perm(res, "P", args.n_permutations, 0.05)
  File "/home/v0_3_beta/src/py/functions.py", line 110, in get_threshold_from_perm
    pvals.append(best_pvals[prefix + str(i)])
KeyError: 'P1'
I'm working on Ubuntu22.04, which does not support  libgfortran.so.3 anymore, this is why I tried to use newer versions of gemma.
Below the content of phenotype_value.log.txt when running using gemma98.1/.5:
**gemma98.1**
##
## GEMMA Version    = 0.98.1 (2018-12-10)
## Build profile    = 
## GCC version      = 8.2.0
## GSL Version      = 2.5
## Eigen Version    = 3.3.5
## OpenBlas         = OpenBLAS 0.3.2  - DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=6
##   arch           = Haswell
##   threads        = 6
##   parallel type  = threaded
##
## Command Line Input = /home/davide/Programmi/kmergwas/external_programs/gemma-0.98.1 -bfile output_dir/kmers/pheno.0.phenotype_value -lmm 2 -k output_dir/pheno.kinship -outdir output_dir/kmers/output -o phenotype_value -maf 0.050000 -miss 0.5 
##
## Date = Mon Feb 26 11:17:08 2024
##
## Summary Statistics:
## number of total individuals = 492
## number of analyzed individuals = 492
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var = 10001
## number of analyzed SNPs/var = 10001
## REMLE log-likelihood in the null model = -1523.38
## MLE log-likelihood in the null model = -1521.04
## pve estimate in the null model = 0.999958
## se(pve) in the null model = 0.000774337
## vg estimate in the null model = 149.931
## ve estimate in the null model = 0.00149931
## beta estimate in the null model =   -7.63151e-14
## se(beta) =   0.00174568
##
## Computation Time:
## total computation time = 0.0516619 min 
## computation time break down: 
##      time on eigen-decomposition = 0.00747965 min 
##      time on calculating UtX = 0.00998482 min 
##      time on optimization = 0.0201722 min 
##
**gemma98.5**
##
## GEMMA Version    = 0.98.5 (2021-08-25)
## Build profile    = /gnu/store/8rvid272yb53bgascf5c468z0jhsyflj-profile
## GCC version      = 7.5.0
## GSL Version      = 2.6
## OpenBlas         = OpenBLAS 0.3.9  - OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY SkylakeX MAX_THREADS=128
##   arch           = SkylakeX
##   threads        = 20
##   parallel type  = threaded
##
## Command Line Input = /home/davide/Programmi/kmergwas/external_programs/gemma_0_98_5 -bfile output2_dir/kmers/pheno.0.phenotype_value -lmm 2 -k output2_dir/pheno.kinship -outdir output2_dir/kmers/output -o phenotype_value -maf 0.050000 -miss 0.5 
##
## Date = Mon Feb 26 12:41:12 2024
##
## Summary Statistics:
## number of total individuals = 492
## number of analyzed individuals = 492
## number of covariates = 1
## number of phenotypes = 1
## number of total SNPs/var = 10001
## number of analyzed SNPs/var = 10001
## REMLE log-likelihood in the null model = -1523.38
## MLE log-likelihood in the null model = -1521.04
## pve estimate in the null model = 0.999958
## se(pve) in the null model = 0.000774337
## vg estimate in the null model = 149.931
## ve estimate in the null model = 0.00149931
## beta estimate in the null model =   -9.92181e-14
## se(beta) =   0.00174568
##
## Computation Time:
## total computation time = 0.109711 min 
## computation time break down: 
##      time on eigen-decomposition = 0.038614 min 
##      time on calculating UtX = 0.00736945 min 
##      time on optimization = 0.0349777 min 
##
Davide

**Comment by voichek** [comment]
Dear Davide,

In your previous message you said you tried also with GEMMA 0.96, this is why I asked it.

If you cannot use GEMMA 0.96, use the 0.98 with the patch. From you original message it seemed you used GEMMA 0.98 without the patch. Can you try this again and tell me if it does not work?

Best,
Yoav

**Comment by DavideGue** [comment]
Hi Yoav,
I'm sorry for the misunderstanding.
What I wanted to say is that:
1) I tried with gemma96 without the patch and go the error message just reported;
2) I tried gemma98 with patches and got threshold_10per and 5per 0.000000.
3) right now I run with gemma98.1 + patch again and  still got threshold_10per and 5per 0.000000; however in the file phenotype_value.assoc.txt I can see associated kmers as below:
chr     rs      ps      n_miss  allele1 allele0 af      logl_H1 l_mle   p_lrt
0       AAAAAAAAAAAGAAAAGAAAAGTAGGTACCT_6945    0       0       0       1       0.917   -1.511584e+03   1.000000e+05   1.362255e-05
0       AAAAAAAAAAAGAAAGAATATTCTCTCGGTT_3606    0       0       0       1       0.937   -1.508901e+03   1.000000e+05   8.292473e-07
0       AAAAAAAAAAAGTGTCTGGCTGGCTGGCATC_3893    0       0       0       1       0.904   -1.501251e+03   1.000000e+05   3.137128e-10
0       AAAAAAAAAAGCCGAGACTCTCTCGGACCAA_1155    0       0       0       1       0.266   -1.502257e+03   1.000000e+05   8.791603e-10
0       AAAAAAAAAAGTGTCTGGCTGGCTGGCATCT_3938    0       0       0       1       0.900   -1.501714e+03   1.000000e+05   5.040191e-10
0       AAAAAAAAAGCATCTCAATTATAAGCGATGT_6627    0       0       0       1       0.815   -1.506974e+03   1.000000e+05   1.127276e-07
0       AAAAAAAAAGCCGAGACTCTCTCGGACCAAT_410     0       0       0       1       0.262   -1.499918e+03   1.000000e+05   8.016926e-11
0       AAAAAAAAAGCTGTACAAGTGAAACAATACA_9768    0       0       0       1       0.776   -1.509063e+03   1.000000e+05   9.813350e-07
0       AAAAAAAAAGTGTCTGGCTGGCTGGCATCTC_7702    0       0       0       1       0.892   -1.504142e+03   1.000000e+05   6.088442e-09

**Comment by voichek** [comment]
Dear Davide,

This behaviour fits with the patch not being in place. Just to make sure can you tell me what did you do with the files from the patch?

Best,
Yoav

**Comment by DavideGue** [comment]
Hi Yoav,
I downloaded the replacement.zip folder, unzipped it and moved the kmergwas.py to the maindirectory, then I moved function.py to maindirectoy/src/py. However I ignored the files in the subdirectory named _MACOSX assuming they are for Mac OS
Davide

**Comment by voichek** [comment]
Dear Davide,

This sounds right.

What do you get when you run:
 `cat phenotype_value.assoc.txt | tail -n +2 | cut -f10 | awk '$1 < 0.001' | sort -g | head -n1` 
(this is the command that is run to get the highest p value from python)?

And you are sure that the patch `function.py` is replacing the previous one, right? (I am sorry I am just confused by this).

Best,
Yoav

**Comment by DavideGue** [comment]
Hi Yoav,
running that command I get nothing. Yeas function.py is replacing the previous one. It is a strange behaviour. However if I run simply zcat phenotype_value.assoc.txt.gz | tail -n +2 | cut -f10 I get the following
1.362255e-05
8.292473e-07
3.137128e-10
8.791603e-10
5.040191e-10
1.127276e-07
8.016926e-11
9.813350e-07
6.088442e-09
7.912783e-09
Thanks for your time.
Davide

**Comment by DavideGue** [comment]
Hi Yoav,
after a few attempts, I can say that my awk does not recognize numbers written in scientific notation (i.e. 1.234e-8).
When I run the command "man awk", the output says that my awk is actually mawk. Could that be the problem?
Thanks,
Davide

**Comment by voichek** [comment]
Yes, it can definitely be a problem.
I am surprised that there is variation in the way awk works, what operation system do you use?

What do you get for this commands:
1. `awk 'BEGIN { print 1.234e-8 + 0 }'`
2. `awk --version`

Best,
Yoav

**Comment by DavideGue** [comment]
Here the commands and the outputs:
davide@administrator:~$ awk 'BEGIN { print 1.234e-8 + 0 }'
1,234e-08
davide@administrator:~$ awk --version
awk: not an option: --version
I'm working on Linux - Ubuntu 22.04
I'm also trying to run kmergwas.py with LC_NUMBER=C. Until now it was setted to en_US.UTF-8 and this may affect the way my system read the decimal separator.
Sorry for wasting your time. I will update you once the run end.
Best,
Davide

**Comment by DavideGue** [comment]
The run finished and the thresholad are:
10_per: 9.208990 (However it lacks exponential, it is right?)
5_per:  9.636610 (same as above)
The output of the command `zcat phenotype_value.assoc.txt.gz | tail -n +2 | cut -f10 | awk '$1 < 0.001' | sort -g | head -n1` is 2.490859e-19
Best,
Davide

**Comment by voichek** [comment]
Now it looks good! and it seems that you have k-mers which pass the threshold.

Can we close this issue now? 

Best,
Yoav

**Comment by DavideGue** [comment]
Yes you Can!
Bests,
Davide
