### ISSUE TITLE
Using 51mer dump files generated by jellyfish

### ISSUE THREAD

**Issue by dosshra** [voichek/kmersGWAS#150]
Hello
We have generated  51mer dump files using jellyfish for a different project. Can this data be used somehow in kmersGWAS pipeline?
Thank you
Hanan

**Comment by voichek** [comment]
Dear Hanan,

No, this pipeline need a k-mers count file created by KMC, and k-mer length has to be <=31. This are very straight forward to make as explained in our manual.

Hope it helps,
Best,
Yoav
