### ISSUE TITLE
How to extract reads base on kmer sequences

### ISSUE THREAD

**Issue by dzaccook** [voichek/kmersGWAS#16]
Hi,
I followed the question previous and use RiDiCulousFilter to extract reads, but the result seem to be wrong, the result contain all raw reads and not be filtered. The command is "RiDiCulous kmer -c kmer.txt -f sample.fq.gz >kmer.fq".
Can you upload your program to do this?
Thank you!

**Comment by voichek** [comment]
Thanks for the interest in our work!

I can not support RiDiCulousFilter. I have no experience with this package, from reading its description it seems to be able to fetch reads containing a set of k-mers.

As a few people have asked already, I have now [uploaded the small program](https://github.com/voichek/fetch_reads_with_kmers) I have written.

I hope it will help you.

Yoav

**Comment by dzaccook** [comment]
Thank you very much!
