### ISSUE TITLE
Combine and filter lists of ​k​-mers to one file

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#18]
Dear author, I would like to ask why I will create the strand to run, the result of the output of the kmers to use is empty, and no error, I can not proceed to the next step, can you remind me how to deal with, resulting in I can not form a 0.1 kmer——table.

**Comment by voichek** [comment]
1. Can you post here the exact command you run?
2. Can you paste here the "kmers_path_list.txt" you used? (or send it to me by mail)
3. Did the program write anything back?
4. Did you try to run example 2 (e coli) to see it works?

**Comment by voichek** [comment]
I am just wondering, on how many individuals are you trying to build the _k_-mers table? Maybe you have less than 5 and you still use the original filtering parameters that requires _k_-mers to appear in at least 5 individuals?
