### ISSUE TITLE
Is the PLINK binary format created from the k-mers table conversion step useful for popgen

### ISSUE THREAD

**Issue by jelber2** [voichek/kmersGWAS#2]
I am interested in using this pipeline/set of tools for non-GWAS analysis (actually popgen analysis for an organism without a reference genome) and was wondering of the usefulness of the PLINK binary format file generated from the k-mers table for downstream popgen analysis (at least Principle Component Analysis, not sure about estimating diversity with expected heterozygosity, observed heterzygosity, and allelic richness as you say k-mers will be coded as present or absent as two homozygous variants, so perhaps heterozygosity can't be estimated).

**Comment by voichek** [comment]
I haven't tried it, but as you said, at least Principle Component Analysis should work.

I would just try it, as creating the k-mers table shouldn't take to much time/resources.

**Comment by voichek** [comment]
@jelber2 - there also other methods for this type of analysis which might be useful.
Many can be found in this paper:
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1755-7

**Comment by jelber2** [comment]
Thanks for your help!
