### ISSUE TITLE
produces kmer_to_user

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#21]
![image](https://user-images.githubusercontent.com/58722433/82744039-e37ce800-9da5-11ea-8efd-ab29483f023b.png)
When I kmer_with_strands to generate the kmer_to_user, the result appears above error, I am very confused, how to solve? 
![image](https://user-images.githubusercontent.com/58722433/82744123-dc0a0e80-9da6-11ea-9539-25c644b9db97.png)
 this is the code that I use the example script in your githup, that is, reporting errors at this point

**Comment by voichek** [comment]
I can not help you without you sending me more details:
1. Please send the exact commands you run **in all steps** prior to creating the kmers_to_use, with the exact parameters.
2. Please run example two with the e coli data, this example should work. 

This is likely one of the two: 1. input parameters that filtered all the k-mers or you didn't build the separate k-mers list correctly.

**Comment by duhuipeng** [comment]
This is where I convert kmer_table using kmers_table_to_bed to generate output_file: bed,fim,ped files, but the resulting reports are like this
![image](https://user-images.githubusercontent.com/58722433/82750343-1fce3980-9de2-11ea-81cd-7869112459c1.png)
I checked the memory size of the output file and the result was
![image](https://user-images.githubusercontent.com/58722433/82750419-9a975480-9de2-11ea-860c-8553fb63df0e.png)
I'd love to know why it's like this. Is there something wrong with me? I'm based entirely on manul.pdf
I used three samples of individuals to run

**Comment by voichek** [comment]
It seems that there is a miss understanding in how to use this library.

First, from your first question, your kmers_to_use file is empty, therefore your kmers_table is empty and I don't understand why you try to convert it plink binary file, which will also be empty.

Until you send the exact commends you used to create all the files until this point I can not help you understand why youy kmers_to_use file is empty. 
Please run the example script with the e coli data as provided to see everything works.

Until you have done this two things (as I asked before) I can not help you. I am closing this thread, if after you run the first example you still have problems, please re-open it.
