### ISSUE TITLE
what is 5000????

### ISSUE THREAD

**Issue by spongeboy12138** [voichek/kmersGWAS#23]
Hello!I read your paper and arouse interest a lot. Subsequently I read your  supplemental file of "manual.pdf".I had created the "kmers_with_strand"(you mentioned),y I read your supplemental file of "manual.pdf".I had created the "kmers_with_strand"(you mentioned),but I failed in the next step which to creat the file kmers_to_use.No error is mentioned during this procedure but there is nothing in the output file ( kmers_to_use ).It  confuses me a lot .

**Comment by voichek** [comment]
Thank you, I am happy you found interest in our work.

I can not help you without you sending me more details:
1. Please send the exact commands you run, with the parameters.
2. Please run example two with the e coli data, this example should work. 

This is likely input parameter that filtered all the k-mers or you didn't build the separate k-mers list correctly.

**Comment by voichek** [comment]
I am just wondering, on how many individuals are you trying to build the _k_-mers table? Maybe you have less than 5 and you still use the original filtering parameters that requires _k_-mers to appear in at least 5 individuals?

**Comment by spongeboy12138** [comment]
For facility limitation I creat kmer-table with 8 individuals.Only if I take the - -mac in 1 and      the result could be exported. Thanks a lot.
