### ISSUE TITLE
kmers_gwas.py

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#24]
I didn't run out when I ran the GWAS with the kmers_gwas.py script you provided, and the file it generated shown below
![image](https://user-images.githubusercontent.com/58722433/82754616-a5f97880-9e00-11ea-90c6-b0ecfca69451.png)
![image](https://user-images.githubusercontent.com/58722433/82754621-af82e080-9e00-11ea-8a4b-0bc778060fc6.png)
I'm confused now. How can I solve this problem now

**Comment by voichek** [comment]
It is written that the .../plant/att/gwas_results directory already exist.
The script created the directory, do the output directory should not exist before.
