### ISSUE TITLE
KMC_kmers

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#25]
Hello, the above is all my code, excuse me where my error is, how should solve.
 
Code:
 
![image](https://user-images.githubusercontent.com/58722433/82870625-de18cc80-9f62-11ea-8be8-fc1ded31eadd.png)
![image](https://user-images.githubusercontent.com/58722433/82870676-f1c43300-9f62-11ea-82d4-d6197a174b85.png)
![image](https://user-images.githubusercontent.com/58722433/82870705-ff79b880-9f62-11ea-8c81-00e428f8caa1.png)
![image](https://user-images.githubusercontent.com/58722433/82870756-11f3f200-9f63-11ea-8de0-b2cdf8032d90.png)
![image](https://user-images.githubusercontent.com/58722433/82870798-1cae8700-9f63-11ea-917b-3628f4d416e0.png)
Because I have an individual, the first step I look out

He gave me the wrong message:
![image](https://user-images.githubusercontent.com/58722433/82871028-76af4c80-9f63-11ea-8f77-e75d697dd145.png)
Looking forward to your reply

**Comment by voichek** [comment]
From this it seems you had a problem to run GEMMA which is a program that the pipeline uses. Gemma is found in external_programs/gemma_0_96, it writes that you are missing libgfortran.so.3: version `GFORTRAN_1.4
"/home/Duhuipeng/LZF/kmers_proj/KMC/external_programs/gemma_0_96: /usr/lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/Duhuipeng/LZF/kmers_proj/KMC/external_programs/gemma_0_96)"

You have to make gemma run as the pipeline is dependent on it, can you install the correct version of libgfortran.so? You can inquire more in the gemma github page.
