### ISSUE TITLE
kmers---plink

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#26]
I'm using the Gemma run or the mistake I told you before, and I see this line of code on your manul.pdf,
 
bin/kmers_table_to_bed -t kmers_table -k 31-p phenotypes.pheno --maf 0.05--mac 5-b 10000000-o output_file, can use plink for subsequent GWAS association analysis, and I generate the following files:
![image](https://user-images.githubusercontent.com/58722433/82894558-57c1b200-9f85-11ea-888c-1771e6baabe2.png)
then used plink analysis commands:
plink --blife output_file.0 --assoc --out assoc_results
Nevertheless, when his result comes out p the full value NA, can not draw a Manhattan map, what is the jie of this value

Looking forward to your reply

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/82895130-4b8a2480-9f86-11ea-8cdc-d58063f734d6.png)
P value worthwhile results

**Comment by voichek** [comment]
I am not sure what is the problem with plink as I never used it to run associations. I can only help with the creation of the PLINK binary file. I usually used GEMMA to run associations on the plink binary file.
