### ISSUE TITLE
kmer_gwas.py

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#29]
Hello, I have communicated with you in the last step of the error, you gave me the statement that there is a library not installed in, I now installed in, from the new run, but still reported wrong, excuse me, what is the reason, I do not understand very well

![image](https://user-images.githubusercontent.com/58722433/83087419-dcb2e580-a0c3-11ea-91f6-9bb0ad5db7dc.png)
Here's the log file I opened, and the error I' ve prompted, I'm totally following the code you provided, and I' m curious as to why I gwas_result that this directory already exists, and I can't read the other two
Looking forward to your reply

**Comment by voichek** [comment]
You are trying to give the script an output directory which already exist. Remove the old directory or give it another directory which does not exist.
