### ISSUE TITLE
Problems with kmers_table_to_bed (Segmentation fault)

### ISSUE THREAD

**Issue by jelber2** [voichek/kmersGWAS#3]
Hi, I am having problems with the `kmers_table_to_bed` binary , below is what I did, and I have included a link to download all but the contents of the `individual` folders and the raw and adapter trimmed reads. Any help would be greatly appreciated.

    cd /genetics/elbers
    mkdir kmersGWAS
    cd kmersGWAS/
    wget https://github.com/voichek/kmersGWAS/releases/download/v0.1-beta/v0_1_beta.zip
    unzip v0_1_beta.zip
    
    cd /genetics/elbers
    wget https://github.com/refresh-bio/KMC/releases/download/v3.1.1/KMC3.1.1.linux.tar.gz
    tar xzf KMC3.1.1.linux.tar.gz 
    
    cd /genetics/elbers/kemps/
    mkdir -p kmers
    
    
    cd /genetics/elbers/kemps/fastq2
    mkdir -p ../trimmed-kmers/
     
    ls *-R1.fastq.gz|perl -pe "s/-R1.fastq.gz//g" > ../samples
    
    while read i;do
    /genetics/elbers/bbmap-38.73/bbduk.sh threads=75 in1=${i}-R1.fastq.gz in2=${i}-R2.fastq.gz out1=../trimmed-kmers/${i}-trim-R1.fq.gz \
    out2=../trimmed-kmers/${i}-trim-R2.fq.gz \
    ref=/genetics/elbers/bbmap-38.73/resources/adapters.fa ktrim=r k=23 mink=11 hdist=1 tpe tbo qtrim=f 2> ../trimmed-kmers/${i}-trim.log
    done < ../samples
    
    cd /genetics/elbers/kemps/kmers
    
    while read i;do
    cd /genetics/elbers/kemps/kmers
    mkdir -p ${i}
    cd ${i}
    echo -e "/genetics/elbers/kemps/trimmed-kmers/${i}-trim-R1.fq.gz\n/genetics/elbers/kemps/trimmed-kmers/${i}-trim-R2.fq.gz" > input_files.txt
    /genetics/elbers/kmc -t75 -k31 -ci2 @input_files.txt output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2
    /genetics/elbers/kmc -t75 -k31 -ci0 -b @input_files.txt output_kmc_all ./ 1> kmc_all.1 2> kmc_all.2
    /genetics/elbers/kmersGWAS/bin/kmers_add_strand_information output_kmc_canon output_kmc_all 31 kmers_with_strand 1>kmers_with_strand.1 2>kmers_with_strand.2
    rm output_kmc_all.kmc_suf output_kmc_canon.kmc_suf
    done < ../samples
    
    cd /genetics/elbers/kemps/kmers
    while read i;do
    echo -e "/genetics/elbers/kemps/kmers/${i}/kmers_with_strand\t${i}" >> kmers_list_paths.txt
    done < ../samples
    
    /genetics/elbers/kmersGWAS/bin/list_kmers_found_in_multiple_samples kmers_list_paths.txt kmers_to_use 5 31 1000000 0.2 1>list_kmers_found_in_multiple_samples.1 2>list_kmers_found_in_multiple_samples.2
    
    /genetics/elbers/kmersGWAS/bin/build_kmers_table kmers_list_paths.txt kmers_to_use kmers_table 31 1>build_kmers_table.1 2>build_kmers_table.2
    
    /genetics/elbers/kmersGWAS/bin/emma_kinship_kmers kmers_table 31 0.01 > kmers_table.kinship 2>emma_kinship_kmers.2
    
    echo -e 'test <-read.table("kmers_table.kinship")' > kinship-summary.R
    echo -e 'summary(test[test != 1])' >> kinship-summary.R
    
    Rscript kinship-summary.R
    #   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
    # 0.5785  0.6507  0.6998  0.7026  0.7447  0.8562
    # kinship values seem reasonable (i.e., not too high and not too low)
    
    while read i;do
    echo -e "${i}\t1" >> phenotype.pheno
    done < ../samples
    sed -i '1i accession_id\tphenotype_value' phenotype.pheno
    
    /genetics/elbers/kmersGWAS/bin/kmers_table_to_bed -t kmers_table -k 31 -p phenotypes.pheno --maf 0.05 --mac 5 -b 10000000 -o plink_input
    using Segmentation fault (core dumped)
    
    /genetics/elbers/kmersGWAS/bin/kmers_table_to_bed -t kmers_table.table -k 31 -p phenotypes.pheno --maf 0.05 --mac 5 -b 10000000 -o plink_input
    using Segmentation fault (core dumped)

     # zip up output (zip file is ~475MB)
    zip elbers-kmersGWAS-output.zip kinship-summary.R kmers_* phenotype.pheno list_kmers_found_in_multiple_samples.* build_kmers_table.*

    # make md5sum
    md5sum elbers-kmersGWAS-output.zip > elbers-kmersGWAS-output.zip.md5sum

    # Not sure what I am doing wrong here, so here are links to download the output and md5sum for the output
    wget https://www.dropbox.com/s/onbshntqyet9y4o/elbers-kmersGWAS-output.zip
    wget https://www.dropbox.com/s/51x5w2jgnspkcx3/elbers-kmersGWAS-output.zip.md5sum

    # checking download integrity
    md5sum --check elbers-kmersGWAS-output.zip.md5sum

**Comment by voichek** [comment]
I think this is because you wrote the phenotype file name wrong (phenotypes.pheno instead of phenotype.pheno) - let me know if it solves it.

I am sorry for this, I will add a check for files used (everything is pretty new here).

**Comment by jelber2** [comment]
Okay, well that is pretty embarrassing. Thanks for catching that. It is running as we speak.  I think the manual says `mers_table_to_bed` instead of `kmers_table_to_bed`, which is a minor typo.

**Comment by voichek** [comment]
Note: (1) In general kinship values are lower for k-mers relative to SNPs (though highly correlated)
(2) you can put the -b 10000000 higher to get all the matrix in one PLINK binary file

**Comment by jelber2** [comment]
Thanks, that would be very useful indeed.

**Comment by voichek** [comment]
In the new release (v0.2-beta) I am now checking that all files relevant exist, so this will not happened anymore.
