### ISSUE TITLE
Index error from kmers_gwas.py

### ISSUE THREAD

**Issue by jkreinz** [voichek/kmersGWAS#30]
Hi Yoav,

Thanks for making your method so reproducible! I've gotten to the GWAS step without issue.

I ran the following command to perform a k-mers-based GWAS with permutation based-threshold and get an index error:

` python2.7 /ohta/julia.kreiner/software/kmergwas/kmers_gwas.py --pheno test --kmers_table kmers_table -l 25 -p 10 --outdir output_dir`

```
Traceback (most recent call last):
  File "/ohta/julia.kreiner/software/kmergwas/src/py/align_kinship_phenotype.py", line 83, in <module>
    main()
  File "/ohta/julia.kreiner/software/kmergwas/src/py/align_kinship_phenotype.py", line 71, in main
    create_new_relatedness_matrix(args.fn_kinship, args.fn_out_kinship, index_kinship)
  File "/ohta/julia.kreiner/software/kmergwas/src/py/functions.py", line 20, in create_new_relatedness_matrix
    m = cut_ind(m, indices)
  File "/ohta/julia.kreiner/software/kmergwas/src/py/functions.py", line 18, in cut_ind
    return [x[ind[i]] for i in range(len(ind))]
IndexError: list index out of range
```

I've made sure my phenotype file is properly formated - any help troubleshooting would be great!

**Comment by voichek** [comment]
Dear Julia,

Thanks for the interest in our work!

Can you please share with me the following files:
1. test - the phenotype file 
2. kmers_table.names - which contain the names of the accessions
3. kmers_table.kinship - which contain the kinship table

Can you send it to my mail? - yoav.voichek at gmi.oeaw.ac.at
I will just use it for debugging and delete the files.

**Comment by voichek** [comment]
kinship matrix was missing.
(will add a normal error massage in next release)
