### ISSUE TITLE
kmers-GWAS

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#31]
I've been talking to you before,I have been using kmers_gwas.py scripts to run the last step, however,it is wrong, and I' ve never solved it, and I've seen your manul.pdf refer to converting kmers_table into ped,bim,bed files, which were meant to be used to rebuild the affinity matrix, which can be constructed with Gemma to run, but the GWAS that running is strange, no chromosomes, no physical distance, no way to draw GWAS, Because when I draw a Manhattan map, it say my chromosomes don' t exist. What's the cause? How do I solve this problem?
![image](https://user-images.githubusercontent.com/58722433/83267025-39162200-a1f6-11ea-93e3-a1d715db798a.png)

**Comment by voichek** [comment]
The idea with the _k_-mers gwas is that you do not look at the genome at all. You did not input the genome at any point to the program so it can not output indices on the genome.

How to proceed from having the _k_-mers to have genomic context is dependent on the user, and can take different forms. We explain this in detail in our manuscript.
