### ISSUE TITLE
error in kmers_gwas.py

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#34]
when I run kmers_gwas.py ,the error is present in below.

Traceback (most recent call last):
  File "/home/Duhuipeng/LZF/kmers_proj/KMC/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/Duhuipeng/LZF/kmers_proj/KMC/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/home/Duhuipeng/LZF/kmers_proj/KMC/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
gwas_result/kmers

**Comment by voichek** [comment]
Can you please send the exact command line you run the pipeline with? and show the input phenotype file as well as the kmers_table.names file?

You can send me the files to yoav.voichek at gmi.oeaw.ac.at or upload to some public space.

**Comment by voichek** [comment]
Can you please send only the files I asked for and not the full matrix to the e-mail I provided here and not to my MPI mail.

**Comment by zhoudreames** [comment]
three files (script，phenoty and kmers_table.names )


[file.zip](https://github.com/voichek/kmersGWAS/files/4709723/file.zip)
