### ISSUE TITLE
kmer_gwas.py

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#36]
My dear author, I am very interested in your article and feel that it is based on the fastest operation on the kmer_gwas, but I still told you the problem of running GWAS before, but now the error is like this, I do not quite understand where my error occurred, please advise
![image](https://user-images.githubusercontent.com/58722433/83344441-9a92d980-a339-11ea-9a04-eef5fed75749.png)
![image](https://user-images.githubusercontent.com/58722433/83344448-ac747c80-a339-11ea-9de3-88151f081e34.png)
 Looking forward to your reply,
Best wishes for you

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/83350431-abaa0d80-a36e-11ea-9f80-15a4f5b6e2a7.png)
The reason for the last problem is that, after taking the Arabidopsis data you provided in the githup and running to the last gwas, his error is like this, can you tell me this is very cause, I do not know how to change this code

**Comment by voichek** [comment]
Can you please send the full log files for this run including the exact command you run and the input phenotype file as well as the kmers_table.names file?

You can send me the files to yoav.voichek at gmi.oeaw.ac.at or upload to some public space.
