### ISSUE TITLE
error in kmers_gwas.py 

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#37]
when I run kmers_gwas.py ,the error is present in below.I send your three files about pheno,table.names and script,thanks for your help!
[file.zip](https://github.com/voichek/kmersGWAS/files/4715507/file.zip)

Traceback (most recent call last):
  File "/home/Duhuipeng/zm/Biosoft/v0_2_beta/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/Duhuipeng/zm/Biosoft/v0_2_beta/kmers_gwas.py", line 165, in main
    run_gemma_cmd(cur_cmd, args.parallel, gemma_handles, f_log)
  File "/home/Duhuipeng/zm/Biosoft/v0_2_beta/src/py/functions.py", line 64, in run_gemma_cmd
    g_handles.append(subprocess.Popen(shlex.split(cmd)))
  File "/home/Duhuipeng/zm/Biosoft/Python-2.7.9/Lib/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/Duhuipeng/zm/Biosoft/Python-2.7.9/Lib/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by voichek** [comment]
I do not understand, you now report a different problem then the one you asked before.
Are you and duhuipeng the same user? I am not really sure what you are trying to do.

**Comment by zhoudreames** [comment]
I am so sorry for the inconvenience,before the problem might be the environment variable problem, and then I modified it to the latest erro. I am dream zhou  and my friends is Duhuipeng ,we want to use your method for my object ,so we will present in there together.  I will close old question

**Comment by zhoudreames** [comment]
Thank you for helping me so much, and hope you can help me solve this final problem.

**Comment by laurenhamm** [comment]
I'm hitting the exact same error, and myself and our hpc team can't figure out where the problem is coming from. zhoudreames, what fixed this error for you and your team?

**Comment by laurenhamm** [comment]
It seems to be a problem with running the gemma executable, which I'm not sure how to fix
