### ISSUE TITLE
Step 3 generated an empty "kmers_to_use" file

### ISSUE THREAD

**Issue by Haoran-Xue** [voichek/kmersGWAS#38]
Hello,

I'm running kmersGWAS with my NGS data (60 samples, each of them has ~10 Gb of data, the genome size is around 610 Mb). The parameters I used are the same as what is in the manual, e.g. -k31. Everything seemed to be fine until step 3.

When I ran step 3, it generated an empty "kmers_to_use" file (the other output files are not empty). The last few lines of the screen output are:
> 4999 / 5000     :       0011111111111100101110010010001110100010100111000111111111001010        unique kmers: 13564
> 5000 / 5000     :       0100000000000000000000000000000000000000000000000000100000110000        unique kmers: 18103
> 5001 / 5000     :        0100000000000011010001101101110001011101011000111001000010010110        unique kmers: 0
> kmers lower than MAC:   0
> passed kmers:   0
> passed MAC bot not pass strand filter:  982026980

I tried with "--mac 3" and "-p 0.1" but got the same error. Do you know what the problem might be? Should I try with a smaller k?

Best regards,
Haoran

**Comment by voichek** [comment]
Dear Haoran,

It is not an issue of the k length. I suspect that it was due to something in the previous step. Can you please provide the following information:
1. Is the data WGS or some reduce representation ? (e.g. rad-seq)
2. Do you have the textual output from a run of the kmers_add_strand_information in the previous step? (Only from one sample)
And also the exact command line you run.
3. Can you copy the exact commend line you run for the two kmc runs from one of the samples?

Best,
Yoav

**Comment by Haoran-Xue** [comment]
Dear Yoav,

Thank you!

1. Yes, it's WGS data

2. Here is a textual output from a run of the kmers_add_strand_information:
Canonized kmers:        743636172
Non-canon kmers:        1397237969
Non-canon kmers found:  743636172
flag    0       count is        0
flag    1       count is        743636172
flag    2       count is        0
flag    3       count is        0
kmers to save:  743636172

3. The two kmc runs:
kmc -t10 -k31 -ci2 @P3-001/input_files.txt P3-001/output_kmc_canon P3-001 1> P3-001/kmc_canon.1 2> P3-001/kmc_canon.2
kmc -t10 -k31 -ci0 @P3-001/input_files.txt P3-001/output_kmc_all P3-001 1> P3-001/kmc_all.1 2> P3-001/kmc_all.2

Best regards,
Haoran

**Comment by voichek** [comment]
Thanks.

You can see from step 2 that all k-mers have flag 1 which mean all were in the canon form.

It seems that something went wrong with how the kmc were inputted in the kmers_add_strand_information step. Can you paste the command you run? Maybe you Inputted the same kmc DB twice or in the wrong order?

Best,
Yoav

**Comment by Haoran-Xue** [comment]
Thanks!

The command I ran is:
pathto/kmersGWAS/bin/kmers_add_strand_information -c P3-001/output_kmc_canon -n P3-001/output_kmc_all -k 31 -o P3-001/kmers_with_strand

Best,
Haoran

**Comment by voichek** [comment]
OK, now I see. You forgot the "-b" in the second KMC command, should be like this:
kmc -t10 -k31 -ci0 **-b** @P3-001/input_files.txt P3-001/output_kmc_all P3-001 1> P3-001/kmc_all.1 2> P3-001/kmc_all.2

Let me know if it fixes it, you can try with one sample and see that not all k-mers will have flag 1.

Yoav

**Comment by Haoran-Xue** [comment]
Yes, it works if I add the "-b"!

> Canonized kmers:	743636172
> Non-canon kmers:	2093730832
> Non-canon kmers found:	1440129035
> flag	0	count is	0
> flag	1	count is	23670949
> flag	2	count is	23472360
> flag	3	count is	696492863
> kmers to save:	743636172

Sorry, I was not careful enough.

Thank you so much!

**Comment by voichek** [comment]
Good :) it seems you have a good coverage.

Hope something will come up in the GWAS.

**Comment by Haoran-Xue** [comment]
Thank you! I hope so :)
