### ISSUE TITLE
Question regarding running time

### ISSUE THREAD

**Issue by miguel-correa92** [voichek/kmersGWAS#4]
Hello, I'm not sure if this is the right place to ask, but what is the running time for this kind of analysis?  For example, how long did it take to run the analyses presented in the paper?
Also, do you have any recommendations on what kind of computer might be needed to run the pipeline?

Thanks in advance

Best

**Comment by voichek** [comment]
I don't have any accurate measurements, but I will try to give estimates for a general feeling for now and maybe try to measure this accurately in the future.

I used a AMD Opteron(tm) Processor 6376 CPU. Running the GWAS for flowering time on ~900 _A. thaliana_ accessions and a _k_-mers-table of 430 million k-mers took less than 5 hours on one CPU. You can also use threads to lower the running time. I didn't record the amount of RAM used (I think it was less than 15G), but this can be controlled by reading the k-mers table is smaller chunks.

Regarding building the k-mers table, which you do only once, there are a few steps:
1. **Creating list of k-mers per individual** - here I don't have  information regarding the memory and it took less than an hour per individual (also here KMC can use threads to lower running time).
2. **Creating a general list of k-mers** & **building the table** - A few hours to run each and also here memory usage can be controlled by setting the size of loaded chunks if needed.

One step that did take time was calculating the kinship matrix, it took a few days to run. If needed this can be optimized, but for now I didn't see a reason to do so.

Hope it helps and hopefully accurate measurement will follow t some point.

**Comment by voichek** [comment]
For more accurate and complete measurements of resources, I have done the following:

Measurements were done on AMD Opteron(tm) Processor 6376 using up to 16 cores. I quantified the resource usage for two test cases. First, I used an _E. coli_ published dataset with sequence data on 241 strains, previously used in the HAWK paper (Earle et al. 2016, Rahman et al. 2018). In the second test case I took 300 accessions from the 1,008 A. thaliana data set and randomized a phenotype for them with 50% as case/control.

I report running time as reported by “Elapsed (wall clock) time”, RAM usage as reported by “Maximum resident set size” and the total size used in the hard disk of the _k_-mer dataset, that is the _k_-mer table.

| Category | _E. coli_ | _A. thaliana_ |
| ------------- | ------------- | ------ |
| #individuals | 241 | 300 |
| Average number of reads per sample | 3,022,528 (150 bp eace) | 52,308,224 (100 bp each) |
| Pre-processing | 2h 46m (453 MB RAM) | 36h 26m (9.98 GB RAM) |
| Disk space of _k_-mers table | 829 MB | 15.6 GB |
| Run GWAS | 5m (1.2 GB RAM) | 19m (1.6 GB RAM) |

The **Pre-processing** step takes into account counting of _k_-mers, creation of the _k_-mers table, and calculation of the relatedness matrix (MAF>0.05).

Most of the **Pre-processing** is done on each sample separately and thus can be run in parallel, to reduce running times.

The timing for GWAS include the permutation-based-threshold calculation (thus effectively running the GWAS x101 times)
