### ISSUE TITLE
Comparing k-mer and SNP kinship matrix

### ISSUE THREAD

**Issue by atwiersma** [voichek/kmersGWAS#41]
As you did in your paper, I would like to compare my k-mer kinship matrix with an equivalent SNP kinship matrix. Is the EMMA calculation that you implement with emma_kinship_kmers equivalent to the GEMMA centered genotype matrix for SNPs?

./gemma -bfile [prefix] -gk 1 -o [prefix]

If it is not equivalent, how would you recommend calculating an equivalent kinship matrix for SNPs?

**Comment by voichek** [comment]
It is not equivalent to the GEMMA, it is the same as the calculation done in the original EMMA paper. 

There is an equivalent implementation inside the library which takes as input the bfile, just use:
bin/emma_kinship prefix_bfile_name > kinship_file

**Comment by atwiersma** [comment]
Okay, excellent. Thank you for the clarification, and for making that option available!
