### ISSUE TITLE
 kmers_add_strand_information crashes

### ISSUE THREAD

**Issue by mscharmann** [voichek/kmersGWAS#43]
Hello, 
I'm trying out your pipeline, but for some of my samples, kmers_add_strand_information crashes with the output pasted below. Using a locally compiled version. Maybe the fastq data was too much?

kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.

**Comment by mscharmann** [comment]
I found out it was caused by the hard memory limit of the job scheduler; issue closed.

**Comment by voichek** [comment]
Sounds right, sorry for not responding earlier.
