### ISSUE TITLE
the problem about kmers filter

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#44]
what is the difference between the minor allele count (MAC) and minor allele frequency (MAF) in kmers filter step？

**Comment by voichek** [comment]
In `bin/filter_kmers` there is no filtering according to maf/mac.

In general, MAF and MAC are indeed redundant. That is, if you have 100 individuals and MAF of 5% is the same as MAC of 5. The two options are given for convenience - for example, we wanted MAF of 5% but if we had less than 100 individuals we didn't want to use less than MAC of 5, so putting MAF of 5% and MAC 5 gave me this logic without looking how many individuals I have in each phenotype.
