### ISSUE TITLE
issue about filter kmers

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#46]
in your article .The k-mers will be filtered according to two criteria,First, a k-mer needs to appear in at least X (e.g. X=5) individuals. Second, a k-mer have to appear in each canonized/non-canonized form in at least P percent (e.g. P=20%) of individuals from which it appeared in.
How to determine the parameters about the X=5 and P=20% ？

**Comment by voichek** [comment]
This parameters can be set as explained in step 3 in the manual
