### ISSUE TITLE
How to retrieve source reads of a specific k-mer ?

### ISSUE THREAD

**Issue by clementmo** [voichek/kmersGWAS#49]
Hi Yoav,

After I finished all the associated analysis between k-mers and phenotypes, how to retrieve the highly associated k-mers from the  k-mers table? Because the k-mers table is in binary style and I don't know how to view it and search the k-mers.

By the way, for k-mers alignment to the genome, can I directly input the 31bp k-mers in fastq file? As for allotetraploid genomes, is it better to use the retrieved sequencing reads for genome mapping? 

Look forward to hearing from you. Thank you so much.

**Comment by voichek** [comment]
Dear Clement,

If you get k-mers that pass the threshold you will get them in the textual file. You need to k-mers table if you want to know what is the presence/absence of them in the population. If you want to see this pattern there is a function that does that, as explained in the manual.

Yes you can map the k-mers directly to the genome, if it works this is great, if not retrieving the reads and then mapping is a very powerful approach.

Yoav
