### ISSUE TITLE
question re: trimming

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [voichek/kmersGWAS#50]
Hi,
As we get started with this. We were wondering if you recommend trimming the Illumina reads first. I could not find anything in the paper or manual about it (might have missed it).

Thanks!
Benjamin

**Comment by voichek** [comment]
Dear Benjamin,

Thanks for the interest in our work.

We have not trimmed the reads, we just took the data as it is for the databases. If I am not mistaken, at least, the _A. thaliana_ 1001G project trimmed the reads before uploading the data to SRA. Our approach was to try and make the minimum amount of decisions and processing. However, trimming reads should give a cleaner dataset. 

Therefore, I think the method should be robust to it, but trimming the reads can create a "cleaner" k-mer DB.

Hope it helps,
Yoav
