### ISSUE TITLE
How to code phenotype missing data

### ISSUE THREAD

**Issue by grafau** [voichek/kmersGWAS#52]
What is the correct way to code missing data for phenotype.pheno file?

My NA and "NA" return the following error:

Error in if (dLL[1] < esp) { : missing value where TRUE/FALSE needed
Calls: emma.REMLE
Execution halted
Traceback (most recent call last):
  File "/home/rg187/bin/INSTALLS/kmeras/kmers_gwas.py", line 278, in <module>
    main()
  File "/home/rg187/bin/INSTALLS/kmeras/kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'test/pheno.phenotypes_and_permutations'

When I substitute NAs with mock data, it works without an error.

Based on gemma documentation NA should work:

3.2.2 Phenotype File
This file contains phenotype information. Each line is a number indicating the phenotype value for
each individual in turn, in the same order as in the mean genotype file. Notice that only numeric
values are allowed and characters will not be recognized by the software. Missing phenotype
information is denoted as NA.

Many thanks for your help!

**Comment by voichek** [comment]
Hi,

[Look here](https://github.com/voichek/kmersGWAS/issues/11)

As this came up for the second time, I will add it to the manual in the next release.

Best,
Yoav

**Comment by zhoudreames** [comment]
@grafau  hi ！Can you show me the missing values in the phenotype file？
