### ISSUE TITLE
kmers_add_strand_information memory

### ISSUE THREAD

**Issue by c5sire** [voichek/kmersGWAS#54]
Hello,

I am trying to run the tools on an HPC with a Sun Grid Engine (SGE) but it seems there is too much memory usage.
The program suite compiles normal. Running the ecoli resistance data with a subset of 6 also works. However, trying to run the program on the SGE results in an 'Illegal instruction' error along with a core dump. Reading some other issues reported here, it seems that the program needs too much memory and there maybe a hard limit on the SGE (where I am not the admin). 
So, as recommended in a comment to issue #48, I replaced KmerUint64Hash with KmerUint64SparseHash and tried to recompile.
However, it does not compile. A key error message part seems to be: 
error: ‘KmerUint64SparseHash’ {aka ‘class google::sparse_hash_map<long unsigned int, long unsigned int, Hash64>’} has no member named ‘set_empty_key’; did you mean ‘set_deleted_key’?

What did I miss?

How to compile for lower memory usage?

Thank you!

**Comment by voichek** [comment]
Dear Reinhard,

You did not miss anything, thanks for checking before in the older issues.

You should make two changes:
Change `KmerUint64Hash` to `KmerUint64SparseHash` in the three places in the file where they appear (you changed only the first place).
You should remove the line after the hash constructor:
`kmers.set_empty_key(NULL_KEY);`

It complies with a warning but I think it should be ok. 

Let me know if it works for you.
Best,
Yoav

**Comment by c5sire** [comment]
Dear Yoav,

thanks for the quick reply.
I adjusted the code, recompiled, and rerun the example on the local SGE but still get the same error message and core dump.

Best,

Reinhard

**Comment by voichek** [comment]
Dear Reinhard,

If it is indeed a memory issue, I do not have a quick fix for this. As I mentioned in the previous issue, this is the most memory intensive step in the pipeline as in all other steps we can load the k-mer list in parts.

I am sorry for not being more helpful. I will try to find a fix for this in the future once I will do another round of improvements to the code.

Best,
Yoav

**Comment by voichek** [comment]
Dear Reinhard,

Just to make sure it makes sense, can you tell me the size of the genome, the coverage and the limitation in memory (or what is the memory usage before it crashes).

Best,
Yoav

**Comment by c5sire** [comment]
Dear Yoav,

Thanks anyway. 
Is it possible to skip that step?
The target genome has a size of 840MB. Coverage varies between 15x and 70x with a median around 50x. Memory on the SGE is about 10GB/slot. 
To clarify: the eco test data with 6 did not run either on the SGE.

Best,

Reinhard

./run_example.sh: line 65: 49083 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050846/kmc_canon -n ./example_dir/samples/SRR3050846/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050846/kmers_with_strand > ./example_dir/samples/SRR3050846/add_strand.log.out
./run_example.sh: line 65:  3077 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050847/kmc_canon -n ./example_dir/samples/SRR3050847/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050847/kmers_with_strand > ./example_dir/samples/SRR3050847/add_strand.log.out
./run_example.sh: line 65:  6130 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050848/kmc_canon -n ./example_dir/samples/SRR3050848/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050848/kmers_with_strand > ./example_dir/samples/SRR3050848/add_strand.log.out
./run_example.sh: line 65:  9363 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050853/kmc_canon -n ./example_dir/samples/SRR3050853/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050853/kmers_with_strand > ./example_dir/samples/SRR3050853/add_strand.log.out
./run_example.sh: line 65: 12514 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050854/kmc_canon -n ./example_dir/samples/SRR3050854/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050854/kmers_with_strand > ./example_dir/samples/SRR3050854/add_strand.log.out
./run_example.sh: line 65: 15543 Illegal instruction     (core dumped) ../..//bin/kmers_add_strand_information -c ./example_dir/samples/SRR3050855/kmc_canon -n ./example_dir/samples/SRR3050855/kmc_non_canon -k 31 -o ./example_dir/samples/SRR3050855/kmers_with_strand > ./example_dir/samples/SRR3050855/add_strand.log.out
./run_example.sh: line 83: 15549 Illegal instruction     (core dumped) ../..//bin/list_kmers_found_in_multiple_samples -l ./example_dir/kmers_list_paths.txt -k 31 --mac 5 -p 0.2 -o ./example_dir/kmers_to_use
./run_example.sh: line 88: 15550 Illegal instruction     (core dumped) ../..//bin/build_kmers_table -l ./example_dir/kmers_list_paths.txt -k 31 -a ./example_dir/kmers_to_use -o ./example_dir/kmers_table

**Comment by voichek** [comment]
Dear Reinhard,

I understood from your first message that the e. coli did run. If it did not then it is a different issue.

Can you try to compile the code on the same computer you got the problem? Does it compile? If you compile it there do you still get the illegal instruction error? 

In any case you can not skip this step.

**Comment by c5sire** [comment]
Dear Yoav,

Thanks for your comments.
I had compiled and recompiled the code on the same machine/HPC with the problem. It does compile - only shows one warning as you indicated. 
Repeated it again.

Running the modified version with the reduced memory footprint on the HPC front it runs ok with both the eco and my own minimal dataset of 2 genotypes. Indeed, memory consumption is much less. For my dataset it reaches about 31G Memory.

Still get the illegal instruction error when running on the SGE. 

Thanks again,

Reinhard
