### ISSUE TITLE
Export kmers_to_use as textual list?

### ISSUE THREAD

**Issue by c5sire** [voichek/kmersGWAS#55]
Dear Yoav,

Is there a way to export the kmers_to_use list from its binary to a text format?

Best,

Reinhard

**Comment by voichek** [comment]
Dear Reinhard,

You can not export directly the `kmers_to_use` using the current implementation, but you can export the full `kmers_table` to text format (using `kmers_table_to_bed`). All the _k_-mers in `kmers_to_use` will be part of the `kmers_table`.

Best,
Yoav

**Comment by c5sire** [comment]
Dear Yoav,

thanks for the pointer.

Best,

Reinhard
