### ISSUE TITLE
 To add additional kmers_with_strand to the kmers_to_use

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#56]
![image](https://user-images.githubusercontent.com/54714639/90944291-69193e00-e450-11ea-8810-56f20c16b925.png)
 What if I additional sequencing data, how do I add kmers_with_strand files to kmers_to_use files

**Comment by voichek** [comment]
Hi,

I am not sure exactly what you are trying to do. 
If you want to add a new sample and update the kmers_to_use and then the kmers_table - you will need to build the kmers_to_use and kmers_table from the beginning. As the filtering in kmers_to_use looks at the entire population, it can not be updated with a new sample.

I am closing the issue, please re-open it if my answer did not address your issue, and please elaborate.

Best,
Yoav
