### ISSUE TITLE
How to prepare the input file for Manhattan Plot ?

### ISSUE THREAD

**Issue by clementmo** [voichek/kmersGWAS#57]
Hi Yoav,

After I finished all the associated analysis between k-mers and phenotypes, I found that the output number of kmers in pass_threshold_10per/pass_threshold_5per is no more than 1001.  What is the problem?

I have 12 phenotypes, as shown in the following is the list of the output of kmer-GWAS folder
```
[lqiao@mn02 kmer_GWAS]$ ls
log_file  phe10  phe11  phe12  phe13  phe2  phe3  phe4  phe5  phe6  phe7  phe8  phe9
```

Using phe12 as an example, which containning most associated kmers.
**lh  /phe12/kmers**
1.2K	        Jun  19	10:30	best_pvals
8.0K	        Jun	19	10:30	output
771K	Jun	19	10:30	pass_threshold_10per
771K	Jun	19	10:30	pass_threshold_5per
518K	Jun	19	10:23	pheno.0.phenotype_value.bed
458K	Jun	19	10:23	pheno.0.phenotype_value.bim
7.1K	        Jun	19	10:23	pheno.0.phenotype_value.fam
5.5K     	Jun	19	10:01	pheno.0.phenotype_value.fam.orig
10	        Jun	19	10:23	pheno.tested_kmers
9	        Jun	19	10:30	threshold_10per
9	        Jun	19	10:30	threshold_5per

```
wc -l pass_threshold_10per pass_threshold_5per pheno.0.phenotype_value.bim
10002 pass_threshold_10per
10002 pass_threshold_5per
10001 pheno.0.phenotype_value.bim
30005 total
```
Is any fixed settings in the python script?

By the way, I am a little confused about how to draw the map of Manhattan Plot using the output results. Actually after I mapped the kemrs to the reference genome (which is an allotetraploid), one kmer can match with more than one position, how could I chose the right position for this kmer? And how can I list the chr, position, p-value information for all the kmers to prepare the input file for Manhattan Plot?  Or only those kmers passed 10% threshold be mapped on the genome? 

Look forward to hearing from you. Thank you so much.

Best wishes,
Clement

**Comment by voichek** [comment]
Dear Clement,

Sorry for the delay in the response.

Regarding your first question, the pipeline work in two steps which are relevant to the number of k-mers you get in the pass_threshold files. First it filters some defined N k-mers using an approximated score, and then in the second step it gives this N k-mers an exact score. After the threshold is defined using the permutations the subset of the N k-mers that pass the threshold are put in the pass_threshold.. files. You can read more about this in the method section of the paper, and there is also an extended data figure illustrating the pipeline.

The default N of the pipeline is 10,001, so in your case you did not change the default and the all the best N k-mers pass the threshold (+1 of header you get a 10002 file). Again, you can read the criterion we used to define N in our paper, but in general I recommend a regime where the number of k-mers which pass the threshold is much lower than N. Therefore, in your case I would recommend to rerun the pipeline with much larger N, maybe 1,000,000.


Regarding positioning the k-mers, there is no one way to do this. You can look at the examples in our paper, where we tried different things. To summarise I would say, first option is to map k-mers, second would be to find the reads from which the k-mer of interest originated and map the reads, and finally if the previous two didn't work, you can assemble all reads which are linked to the same k-mer and then try to find the assembled fragment position. As this method is not reference dependent in some case the k-mers could just not map to the reference, which are the most interesting cases.

Hope it helps,
Yoav

**Comment by clementmo** [comment]
Hi Yoav,
Thank you for your patience. 
I tried to find the default N  (10,001) settings in the pipeline but didn't find in which script can I set it. According to the complete process in you manual, there is no parameter to set this number.  Sorry to disturb you again. Looking forward to your answer. Thanks a lot !

**Comment by voichek** [comment]
Dear Clement,

When you run the `kmers_gwas.py` pipeline you can set the number of _k_-mers which pass the first step by the parameter `--kmers_number`.  In general you can run `python2.7 kmers_gwas.py --help` to get all parameters.

A (not so important) note regarding the 10,00**1** number,  there is [a bug in some version of GEMMA](https://github.com/genetics-statistics/GEMMA/issues/182) (not the default 0.96 version which comes with the release of our library)  that have a problem running a multiplication of 20,000, so I started the habit of always taking number of _k_-mers which is a multiplication of 1000 plus 1.  This is as the second stage of the pipeline runs with GEMMA.

Best,
Yoav
