### ISSUE TITLE
Why use  reverse-complement form to filter？

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#6]
papaer content：k-mers are further filtered to retain only those present in at least 5 accessions, and ones that are also found in their reverse-complement form in at least 20% of accessions they appear in。
What is the basis for using reverse-complement form filtering

**Comment by voichek** [comment]
Thank you for your interest in our work.

The idea of this filtering is to remove _k_-mers that tend to appear only in one form (e.g CCT) and not in the reverse-complement (e.g in the previous example: AGG). If, for example, you have a _k_-mer that appears in 100 accessions and in all cases you just get one form and not its rev-comp it is a sign of some sequencing artefact. This can be due, for example, sequence originating in adaptors.

If you are not interested in this filter you can just set the threshold to 0%, as explained in the manual.
