### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by zhoudreames** [voichek/kmersGWAS#60]
accession_id    phenotype_value
s5617   -0.142866773577041
s5619   -0.71606633615972
s5647   -0.169816858372104
s5666
s5694
s4074   -0.366542460510935
s4224   1.16146460227836
....
this my phenotype file, Only reserved accession for missing values.but there have error below:

Error in if (dLL[1] < esp) { : missing value where TRUE/FALSE needed
Calls: emma.REMLE
Execution halted
sh: warning: setlocale: LC_ALL: cannot change locale (en_CN.UTF-8)
Traceback (most recent call last):
  File "/home/Duhuipeng/zm/Biosoft/v0_2_beta/kmers_Mz_skin_gwas.py", line 283, in <module>
    main()
  File "/home/Duhuipeng/zm/Biosoft/v0_2_beta/kmers_Mz_skin_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]

**Comment by zhoudreames** [comment]
@voichek

**Comment by voichek** [comment]
Look [here](https://github.com/voichek/kmersGWAS/issues/11)
