### ISSUE TITLE
Problems with parameters filter_kmers (textual output)

### ISSUE THREAD

**Issue by annevogel** [voichek/kmersGWAS#62]
Dear Yoav, 

I read your paper and I think your approach is very useful! I am currently trying to apply this pipeline to my own data. I followed the manual and I managed to create the files kmers_table.table and kmers_table.names as mentioned in step 4 (page 5).

For further analysis I need a textual output of the binary presence/absence table. I tried using the command found under heading **Textual output of k-mers presence/absence pattern** (page 7 of the manual): 

_user@server:kmers_proj$ <KMERS-GWAS-PATH>/bin/filter_kmers -t  kmers_table -k kmers_list.txt -o output.txt_ 

When I use this command (adapted to my own paths), it only indicates that it cannot find the file kmers_list.txt. I am not very experienced yet in this kind of analysis, so it might be that I misunderstood something. 

About -k: There is no file kmers_list.txt, nor is it generated somewhere. In the help it says: file with k-mers, each k-mer in a seperate line. How do I create this file?
About -t: the help indicates that this is "k-mers table prefix path" so I assumed the path to the kmers_table.table file, but this also does not seem to work. 

I checked the provided examples, but could not find an example of usage of this command to create a textual output. 

Could you explain how to use the k and t parameters correctly? It is probably something really simple I do not understand, but I tried different solutions and none seem to work. 

Thank you in advance! 
Anne

**Comment by voichek** [comment]
Dear Anne,

First, thanks for the interest in our work.

`filter_kmers` is supposed to be used with a set of k-mers of interest. Therefore, you need to specify in the file `kmers_list.txt` which k-mers you want to get the presence/absence pattern for.

The format of the file is just a list of k-mers, each in its own line. For example, a file with two k-mers can look like this:
```
TCAGAAAAGGAGGGTGAGGGACGACGATTTG
CAAATCGTCGTCCCTCACCCTCCTTTTCTGA
```
So you need to create and input this file.

It seems that you want the full table in a textual format (which might be a huge file). For this you can use the `kmers_table_to_bed` functionality to convert it to PLINK binary and then take from the the list of k-mers, or just keep working with the Plink format if it fits your need.

Hope it helps,
Yoav

**Comment by annevogel** [comment]
Dear Yoav,

Now I understand why it did not work! I indeed need a fill table in textual format. I will use the PLINK binary conversion, that does sound like what I was looking for!

Thank you for your explanation!
Best,
Anne
