### ISSUE TITLE
How to specify which phenotype value to use for association mapping?

### ISSUE THREAD

**Issue by ritatam** [voichek/kmersGWAS#63]
Dear Yoav,

Thanks for creating this useful tool! :) Just a quick question here: 

Since we are interested in mapping avirulence genes I am wondering if it is possible to specify one phenotype from the two distinct phenotype values (1 and 0 for a binary trait) for the kmerGWAS pipeline to run upon, for example choosing 0 to generate kmers associated with avirulence.
We think switching the phenotype values the other way round may work but just wondering if this is a possibility. Thanks! 

Best regards,
Rita

**Comment by voichek** [comment]
Hi Rita,

I am happy that you find interest in this library!

I am not sure I fully understand, you want to put a binary phenotype (e.g. dead/alive)? If so, first I don't think it matters if you would swap what is 0 and what is 1. The pipeline will work, and we have used it for such phenotypes in our work.

Hope it helps,
Yoav

**Comment by ritatam** [comment]
Hi Yoav,

Thanks for your prompt response!

We are looking for a fungal avirulence gene by testing its virulence on different host strains; so in our case 1 = virulence (infection takes place) and 0 = avirulence (no infection). But we are only interested in avirulence genes.
If we run the pipeline based on these phenotype values, because we don't specify which phenotype to use beforehand we are not sure if it will associate kmers with the virulence phenotype and hence map to virulence genes. As the avirulence genes we are looking for are extremely diverse we want to make sure the kmers are associated with avirulence only. So we are thinking of swapping the phenotype values between the two. Hope that clears it up a bit!

Much thanks,
Rita

**Comment by voichek** [comment]
Dear Rita,

As in associations you only look for linear relationship between genotype and phenotype, swapping the zeros and ones should not make a difference. You can try to run the pipelines both ways just to see you get the same results.

Bests,
Yoav
