### ISSUE TITLE
kmers_gwas.py error

### ISSUE THREAD

**Issue by douwetb** [voichek/kmersGWAS#64]
Dear Yoav Voichek,

Thank you for the interesting paper. I've tried to run the program on our own dataset. I manged to get the kmercounts, which kmers to use etc. Currently I'm trying to run the kmers_gwas.py script for a small test-dataset. After troubleshooting several errors I can't get passed the following error. 

- What I run: 
# run GWAS
gwas_outdir="$base_dir/gwas_results"
CMD="python2.7 $library_dir/kmers_gwas.py --pheno ordered.phenotype.lettuce. --kmers_table $kmers_table_prefix -l $K -p $THREADS --outdir $gwas_outdir >>$base_dir/gwas_run.log.txt 2>&1"
echo "$CMD"; eval $CMD

echo "k-mers passing 5% threshold are found in $gwas_outdir/kmers/pass_threshold_5per"

- The phenotypes_transformation_permutation.log is empty afterwards.
- The gwas_run.log.txt file contains the following error:

Traceback (most recent call last):
  File "/home/douwe/kmer_GWAS/src/py/align_kinship_phenotype.py", line 83, in <module>
    main()
  File "/home/douwe/kmer_GWAS/src/py/align_kinship_phenotype.py", line 56, in main
    phenotype_val = get_column(args.fn_phenotype, 1)[1:] # Phenotypes values
  File "/home/douwe/kmer_GWAS/src/py/functions.py", line 14, in get_column
    return [line.split(sep)[index] for line in file(fn,"r").read().split("\n")[:-1]]
IndexError: list index out of range
Error in file(file, "rt") : cannot open the connection
Calls: read.csv -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/home/douwe/kmer_GWAS/examples/lettuce_samples/gwas_results/pheno.phenotypes': No such file or directory
Execution halted
Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: '/home/douwe/kmer_GWAS/examples/lettuce_samples/gwas_results/pheno.phenotypes_and_permutations'

The phenotype and kinship table are changed to .txt file in order to be uploaded here. 
[ordered.phenotype.lettuce.txt](https://github.com/voichek/kmersGWAS/files/5658556/ordered.phenotype.lettuce.txt)
[gwas_run.log.txt](https://github.com/voichek/kmersGWAS/files/5658545/gwas_run.log.txt)
xt)
[kmers_table.kinship.txt](https://github.com/voichek/kmersGWAS/files/5658324/kmers_table.kinship.txt)

I was wondering whether you could help. Thank you.

**Comment by voichek** [comment]
Hi,

Thanks for the interest in our work!

Did you try to run example 1 from this repository? If not, please do, as this will help me understand if the issue is in the files you created or something in running the library in your environment.

Another question, the phenotype file you uploaded has only ~20 samples, is this supposed to be this low? or it only a partial file.

Best,
Yoav

**Comment by douwetb** [comment]
Hi Yoav,

Thank you for the fast reply. I/we already fixed the error I messaged you for, so for now I don't need your help.  
I also had some trouble running the E.coli test dataset at the start, but yesterday I got it running.  I also received the same error as https://github.com/voichek/kmersGWAS/issues/53. But I also updated the Gemma program as suggested, Thanks for now.
