### ISSUE TITLE
Error in running GWAS

### ISSUE THREAD

**Issue by ytguojian** [voichek/kmersGWAS#66]
Hi Yoav Voichek,

We are trying to running GWAS " python /public/home/guojian/software/kmersGWAS-master/kmers_gwas.py --pheno phenotypes.pheno --kmers_table kmers_table -l 31 -p 8 --outdir output_dir"
But get error message : 
Traceback (most recent call last):
  File "/public/home/guojian/software/kmersGWAS-master/kmers_gwas.py", line 278, in <module>
    main()
  File "/public/home/guojian/software/kmersGWAS-master/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/public/home/guojian/software/kmersGWAS-master/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
output_dir/kmers

How could we resolve this?

Thank you!

Jian

**Comment by voichek** [comment]
Hi Jian,

I am on vacation until the second week of January, I can try to help more then.
I would recommend to try running example 1 to see there is no system problems.

Best wishes and happy holodays,
Yoav

**Comment by ytguojian** [comment]
Hi Yoav,

Thanks for your qucikly reply. I will try to perform GWAS using the bed file with another optional GWAS tools.
If it does not succeed, I will contact you after vacation
Happy holidays.
Jian

**Comment by U-di-Lan** [comment]
Hi Yoav,
I am also getting this error when trying to run the arabidopsis example.
Its seems that the kmer folder is empty.
Have a nice vacation.
Udi

**Comment by voichek** [comment]
Dear Jian, 

Do you still need help with this issue? What is the status now?

Dear Udi,
Can you please open a new issue for this, as this is likely a different problem. In there can you explain if the folder for the GWAS run was created and there were no files at all in it?

Best wishes,
Yoav

**Comment by ytguojian** [comment]
Hi Yoav,

Thank you for your reply.
Now I have no problem in k-mer-based GWAS.
I have used your protocal to generate a bed file, and then I use the tool EMMAX to perform GWAS, but not the python script in your protocal（kmers_gwas.py）. 

Cheers,
Jian
