### ISSUE TITLE
Possible to run list_kmers_found_in_multiple_samples in parallel?

### ISSUE THREAD

**Issue by phil-grayson** [voichek/kmersGWAS#67]
Hi!

I just ran your program on a small test data set and was able to get it to run smoothly, export the tables for PLINK and get the answer I expected!  For that small test set of 30 samples, the list_kmers_found_in_multiple_samples only took about 10 minutes. Now, I'm trying to run on a much larger dataset of 266 samples and after 12 hours the list_kmers_found_in_multiple_samples has completed 29/5000.  If it continues at this pace, I'm expecting nearly 3 months for that step to run (which is longer than my cluster allows jobs to run for).  I can prune down to a smaller data set, but I would like to be able to include as many samples as possible.  Thanks!

**Comment by voichek** [comment]
Dear Phil,

Happy new year. I am on vacation for another week and can answer in more depth afterwards.

The times you report seem much too long, this step shouldn't be so long. Can you say what is the range of number of unique k-mers per sample you have (you get it from the KMC reports)? My first guess would be a limit on memory - maybe it start to use the hard-disk for memory after it used all the RAM it can? I would try to run with more memory allocated to the run. 

I can try to solve this with you once I am back, but in any case it should not take so long.

Best,
Yoav

**Comment by phil-grayson** [comment]
Dear Yoav,

Happy new year to you too and thanks for the quick reply!  Please enjoy the rest of your holiday.  I'm trying it out on a bunch of subsets at the moment to see if there are any that are problematic.  As far as I can tell, the memory is not an issue (working on a SLURM system which indicates that it only takes about 1-2 Gb for this job and I'm providing 20 Gb).  For the small test data, I was getting around 350 million "kmers to save" for each sample at the end of the "kmers_add_strand_information" step.  For my bigger run, the samples have about 3x that (around 950 million to over 1 billion), but my smallest test subset (n=12) completed in just 44 minutes, so it seems to be on the right track.  I have 6 other subsets running ranging in size from 27-62 and when you get back from holiday I  can let you know how they ran. For the record, here's what I'm running just in case I've missed a flag that should have been included. I'm supplying the path list with `$1` and a name for the outfile with `$2`.

`~/programs/kmerGWAS/bin/list_kmers_found_in_multiple_samples -l $1 -k 31 --mac 5 -p 0.2 -o $2`

**Comment by phil-grayson** [comment]
Quick update - super interesting result with the memory request.  The SLURM software is telling me that the job uses a maximum of less than 2 Gb, but I just ran the same subset of 27 samples with either 10 Gb or 100 Gb allocated to it and the 100 Gb job finished in 46 minutes, while the 10 Gb job took over 6x longer to complete.  Going to try running the full dataset (266 samples) with 186 Gb of memory and see if it finishes quickly.  Thanks for the suggestion!

**Comment by voichek** [comment]
Dear Phil,

First, your command looks ok to me. 
Second, this is really interesting and I would suspect that there is something different in how your k-mers are distributed than the examples I worked with. The 186 Gb is much more than what should be necessary, the 5000 steps it separation of the k-mers space to 5000 (far from equal in size) groups and loading each group to the memory separately. So if we indeed see that increasing the memory help, we should change the 5000 to some higher number (e.g. 50K). The number of steps can only be changed now in the code, but I can add it to the command line when I am back to work at the end of the week.

Let me know if giving the program 186 Gb made it better.

Best,
Yoav

**Comment by phil-grayson** [comment]
Dear Yoav,

Yes it is odd! As I mentioned in the first message, I initially tried to run 266 samples with 20 Gb of memory and after 12 hours the job was killed (timeout) and the out/err file had 29/5000.  Over the weekend, my 266 sample 186 Gb job started up (and completed!).  I requested a week and it completed in 2 days (almost exactly).  The scheduler says:

`seff 58496235
Job ID: 58496235
Cluster: cedar
User/Group: pgrayson/pgrayson
State: COMPLETED (exit code 0)
Cores: 1
CPU Utilized: 07:45:07
CPU Efficiency: 16.14% of 2-00:01:04 core-walltime
Job Wall-clock time: 2-00:01:04
Memory Utilized: 9.72 GB
Memory Efficiency: 5.23% of 186.00 GB`

here's the original attempt with 20 Gb that hit the 12 hour wall and timed out
`seff 58457376
Job ID: 58457376
Cluster: cedar
User/Group: pgrayson/pgrayson
State: TIMEOUT (exit code 0)
Cores: 1
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 11:59:26 core-walltime
Job Wall-clock time: 11:59:26
Memory Utilized: 1.29 GB
Memory Efficiency: 6.43% of 20.00 GB
`
I also ran a quick test of k-mers kept vs fastq size (as proxy for read number) for all my samples and got a strong correlation as expected (Pearson's product-moment correlation was 0.968644 (t = 63.347, df = 264, p-value < 2.2e-16).
![Screen Shot 2021-01-04 at 9 56 25 AM](https://user-images.githubusercontent.com/7772591/103553587-43c32480-4e73-11eb-8993-abb450c7c0a2.png)

The few libraries that have much larger fastq files are from 5 individuals that we sequenced much more deeply 50-60x compared to 10-20x for the majority of the samples, but these ones did not seem to have much of an effect on the run time of the subsamples (that seemed to be pretty correlated with sample size).  With 10Gb of memory, the following subsamples completed during my testing on Friday:
1. 12 samples in 00:44:10
2. 27 samples in 04:42:59
3. 30 samples in 04:32:09
4. 30 samples in 04:36:40
5. 36 samples (including all deep-seq individuals) in 05:23:02
6. 38 samples in 05:21:49
7. 47 samples in 06:20:11
8. 62 samples in 08:24:37

These subsamples cover all of the 266 samples with only a few repeated between the 36 sample and 62 sample run (otherwise all samples appear once).  Hopefully this info all helps!  Let me know if you need anything else and I'll let you know if I run into any problems with the downstream scripts (the jobs to create the kmer tables are currently running).

**Comment by voichek** [comment]
Dear Phil,

First, if I understand correctly running it with more memory solved your problem, right?

In general it make no sense that one will need so much memory for running this step as it can be partitioned into sub steps as much as needed. For this, I just need to let the number of steps be defined from the command line in the future as this is proportional to the memory usage of the program. I think something is special in your case, at least relative to datasets I worked with, as I wouldn't expect a need for so much memory from the k-mer numbers. The steps just separate the _k-mer_ space to equal size ranges, and this ranges in reality do not contain similar number of _k-mers_. The first few steps tend to have the most _k-mers_ in them. So it might be that the first ranges in your case have much more _k-mers_ and this is what requires the extra memory. 

Regarding the fact that the reported memory does not reach the limit but we still see a large effect on performance when increasing it. I do not understand this, but it is some decision of the system on how it manage the memory (RAM vs. HD).

I am closing this issue for now, let me know if you want to reopen it and in general if the next steps went smoothly.

Best wishes,
Yoav

**Comment by phil-grayson** [comment]
Dear Yoav,

You are correct, I was able to get the job run by requesting much more memory than SLURM was reported to use.  Following that, I ran build_kmers_table on the 265 file (there were 266 libraries, but 2 of them were deep and low coverage for the same sample, so they've been combined at this point):
`~/programs/kmerGWAS/bin/build_kmers_table -l kmers_clean_list_path.txt -k 31 -a kmers_to_use -o kmers_table`
 and then converted the table to bed with kmers_table_to_bed:
`~/programs/kmerGWAS/bin/kmers_table_to_bed -t kmers_table -k 31 -p pheno_lamprey_all.txt --maf 0.05 --mac 5 -b 10000000000 -o plink_lamprey`
and finally, ran plink 1.07 on this file:
`plink --noweb --bfile plink_lamprey.0 --allow-no-sex --assoc --out lamprey_kmers_plink`

This process worked on my test dataset from a different species (n=27) and provided 198 k-mers that included the fixed variant between the populations. The F_A and F_U (frequency of the k-mer in the affected and unaffected samples) from plink were 0 and 1 for that site.  I'm now running into (maybe) a strange issue with my larger data set.  It could be behaving as expected, but I'm curious to hear what you think.  The plink run seems to complete without issues, but the highest possible F_A or F_U it reports is 0.656.  There are just over 1 billion k-mers in this analysis I would expect that at least some of them would be present at a frequency > 0.656 in at least one of my populations.

I ran a lot of tests over the weekend to try to pin this down.  From the 265 sample k_mer table, I extracted my same subpopulations that I had used previously for the memory tests and ran them through the kmers_table_to_bed (via different -p options) and then through the plink association test.  Attached is an image of a table from this test.  I reported the total sample number, the number that are labeled as phenotype 1, the number labeled as phenotype 2, and the ratio of pheno1 and pheno2, as well as the maximum F_A and F_U values reported by the plink output and the total k-mers analyzed in that plink run.  This table includes both the entire >1billion kmers for the 265 set run in a single plink run (lamprey_kmers_plink_all.0.assoc) as well as the same 265 set run in 5 batches (plink_lamprey_parallel.0-plink_lamprey_parallel.4).  As you can see from those runs, the k-mer number going into plink doesn't seem to matter nearly as much n.  I'm curious if these F_A and F_U values make sense, or if there might be something putting an artificial cap on this frequency in either your program or the plink run?  In all my plink logs, each sample included in the run has a properly assigned phenotype.  Happy to provide anything else that might help with this!  Thanks!

![Screen Shot 2021-01-12 at 10 46 10 AM](https://user-images.githubusercontent.com/7772591/104345000-700a2100-54c3-11eb-9069-1dc733edcee0.png)

**Comment by voichek** [comment]
Dear Phil,

I am not sure I understand, I will rewrite what I understood and correct me. You run associations analysis between your phenotype and the _k-mers_ presence\absence (in plink, which I never used). This gives you the frequency of _k-mers_ presence inside the samples defined as affected (or unaffected) and you take the most extreme frequency (close to 1 or 0) and plot it. Right? So if for example we look at the row with `lamprey_kmers_plink` (which is the full k-mers-table), we have 125 samples which are marked as affected. From this 125 samples, there is a k-mer which is present in 125*0.6429 ~= 80 and not present in 45 samples, right? and this is the most extreme k-mer found from all 1 billion k-mers?. And you are surprised by this as you would expect even in a random separation of affected and unaffected to find a k-mer like this?

If this is the case, maybe a simple calculation assuming binomial distribution of each k-mer to be present or absent for each individual can be use to get a feeling if this can be? That is X ~ B(125,0.5) and what is the probability P(X>=80).
P(X>=80) ~= 10^-3 so indeed you should something more extreme with 10^9 k-mers. I am not sure what is the exact test plink is doing so don't know how good an estimate it is to get a feeling for the numbers (or maybe I didn't get you at all).

Regarding the technical issue, I would look for the k-mers you know the probability for in a subpopulation and extract them directly from the k-mers-table to see you get what you expect. 

Maybe also try to run the associations using the GWAS in the library, if you don't want to include the population-structure you can just input the identity matrix.

Another idea, maybe you can add the unique flag when you create the Plink binary file so you will now the number of effective k-mers.

Let me know if I got you completely wrong,
Hope it helps,
Yoav

**Comment by phil-grayson** [comment]
Hi Yoav,

You've understood correctly and I'm glad to see that my intuition seems correct (we should see something more extreme than 0.6429.  I will try what you've suggested and get back to you! 

Thanks and all the best!

Phil

**Comment by phil-grayson** [comment]
Hi Yoav,

If I don't want to create the kinship matrix, what does the "identity matrix" look like?  I have my kmers_table files (.names and .table) and the phenotypes.pheno file, but I'm getting an error that says:
`IOError: [Errno 2] No such file or directory: 'kmers_table.kinship'`
So I'm assuming that I need to create a file to replace the .kinship if I don't want to run the kinship process for this test.

Thanks!

**Comment by voichek** [comment]
Dear Phil,

Identity matrix matrix is just a matrix with 1 in the diagonal and 0 everywhere else. 
So you need to create a file named kmers_table.kinship in the same directory where you have your kmers_table with an identity matrix. In this file you should have n lines and n columns, columns separated by tabs ("\t") , where n is the number of individuals in your kmers_table (i.e. 265).  
You can see an example in the table I've uploaded:
https://zenodo.org/record/3596255#.YAqQQXdKhhE

I am not sure this way would be the final thing you want to do, but for sure it doesn't account for population structure as we give it kinship with no structure and it will give an indication regarding the source of the issue you have raised.

Best,
Yoav

**Comment by voichek** [comment]
Dear Phil,

Did you have any progress with this problem? Should we keep this issue open?

Best wishes,
Yoav
