### ISSUE TITLE
How do i add again flag2 data 

### ISSUE THREAD

**Issue by qazwsx1995** [voichek/kmersGWAS#68]
![image](https://user-images.githubusercontent.com/65820716/103870460-b26be080-5106-11eb-8964-8d2ee6adcbd6.png)
How do i remove flag 0

**Comment by qazwsx1995** [comment]
this is  metagenome database (Removed host，Paired-end sequencing)   ，Intersection with NCBI bacterial kmer canonical and non-canonical databases，and then i used "kmers_subtract" to filter .

**Comment by qazwsx1995** [comment]
Establish the intersection of kmer canonical and non-canonical databases using -ci1 and -ci0 -b respectively

**Comment by qazwsx1995** [comment]
@voichek

**Comment by voichek** [comment]
Hi,

I am sorry, but I do not understand fully what you are trying to do.

The fact you do not get any k-mers with flag 2 (01) means that you are missing k-mers which are found only in the non-canonical form. If you are manipulating the k-mers and not just counting them I guess you did something wrong along the way.

Best,
Yoav

**Comment by voichek** [comment]
Dear qazwsx1995,

It is the second time you ask a question and then do not answer follow ups.
I am closing this issue for now.

Yoav
