### ISSUE TITLE
kmers folder empty

### ISSUE THREAD

**Issue by Udi-Lan** [voichek/kmersGWAS#69]
Dear Yoav,

We at TAU are planning to use your work to analyze our data.
I am excited to try it and convince we will get interesting results.
Meanwhile I am trying to run the Arabidopsis example on my machine. (later I`ll also try it on the cluster).
The error I got is:
Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/home/.../kmersGWAS-master/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0
run_GWAS_FT10/kmers

The 'run_GWAS_FT10' folder was created and in it 10 files and the kmers folder, however the kmers folder is empty.
Thank you for your support.
I hope to have a chance to get your assistant in some general question we have regarding the resources we need to run the analysis.

Best,
Udi

**Comment by voichek** [comment]
Dear Udi,

Thanks for opening a new issue and I am happy you found interest in this approach! hope it will provide some interesting results.

Can you please send me the folder content (zip it and it here, it should be relatively small).

Best,
Yoav

**Comment by Udi-Lan** [comment]
Dear Yoav,
Thank you for the quick reply
Folder attached.
Udi

[run_GWAS_FT10.zip](https://github.com/voichek/kmersGWAS/files/5787744/run_GWAS_FT10.zip)

**Comment by voichek** [comment]
Hi,

From the log files it seems to not be able to find:
/home/udi/Documents/TAU/ICCI/kmersGWAS-master/bin/associate_kmers

which is weird as it finds the other files? did you download the release or cloned the the repository (and then you need to compile)?

Yoav

**Comment by Udi-Lan** [comment]
mmm.. didn't compile.. sorry for the that.

**Comment by voichek** [comment]
No problem, just take the release if you want to avoid the compilation step.

Shabat shalom,
Yoav

**Comment by Udi-Lan** [comment]
OK
תודה ושבת שלום
