### ISSUE TITLE
gfortran3 ubuntu 20.04

### ISSUE THREAD

**Issue by Udi-Lan** [voichek/kmersGWAS#70]
Hi Yoav,
I have ubuntu 20.04 and got this error:
/home/.../kmer_gwas/external_programs/gemma_0_96: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
Its look like gemma needs gfortran3 but it is no longer available in this version (they switched to gfortran5)
Best,
Udi

**Comment by voichek** [comment]
Can you try to download the newer version of gemma (0.98) and see if you can run it?
https://github.com/genetics-statistics/GEMMA/releases
(I tried with 0.98.1, but probably it is interchangeable with 0.98.3).

If so, I wrote a small patch so you can run with the newer gemma version, you can get it here:
https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460

**Comment by Udi-Lan** [comment]
I took the 0.98.3 executable and put it in the 'external_program' folder and change it name to gemme_0_96 (and removed the original). Its running now. i`ll update tomorrow. Thank you and good night

**Comment by Udi-Lan** [comment]
worked. tnx
