### ISSUE TITLE
LD between SNP and K-mer

### ISSUE THREAD

**Issue by ytguojian** [voichek/kmersGWAS#73]
Hi Yoav,

We are performing the k-mer-based GWAS in peach using your kmersGWAS tools. We generated the bed file of k-mers, and used EMMAX to carry out GWAS. Because we got error in GWAS when running the kmers_gwas.py ,showing below.

"Traceback (most recent call last):
  File "/public/home/guojian/software/kmersGWAS-master/kmers_gwas.py", line 278, in <module>
    main()
  File "/public/home/guojian/software/kmersGWAS-master/kmers_gwas.py", line 153, in main
    fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
  File "/public/home/guojian/software/kmersGWAS-master/src/py/functions.py", line 10, in get_file_type_in_dir
    raise Exception("File count not = 1 %s %d\n%s"  % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0"

Therefore, we used EMMAX tool to perform GWAS. However, in the GWAS results, there were no position for the significant k-mers. So how to get the position, and how could we get the LD between SNP and K-mer. And how could we plot the fig in your NG article (such as,Fig. 1c, Fig. 4e,f)

we appreciate for that if you can help to solve the kmers_gwas.py error.

Thanks 

Jian

**Comment by voichek** [comment]
Dear Jian,

With which of the problem do you want help?

1. Regarding the error, did you try to run example 1 and did it work for you?
2. **LD** - to calculate LD between _k_-mers and SNPs you just need the population presence/absence patterns of your associated _k_-mers and SNPs.  For the _k-mers_ - you can get those by using the `/bin/filter_kmers` functionality. Then you can use any LD measure you want.

Best,
Yoav

**Comment by voichek** [comment]
Can we close this issue?

**Comment by ytguojian** [comment]
yes, thank you. 发自我的华为手机-------- 原始邮件 --------发件人： Yoav Voichek <notifications@github.com>日期： 2021年1月28日周四 16:06收件人： voichek/kmersGWAS <kmersGWAS@noreply.github.com>抄送： ytguojian <ytguojian@163.com>, Author <author@noreply.github.com>主    题： Re: [voichek/kmersGWAS] LD between SNP and K-mer (#73)
Can we close this issue?
