### ISSUE TITLE
Kinship matrix error

### ISSUE THREAD

**Issue by jkreinz** [voichek/kmersGWAS#74]
Hi Yoav,

I'm trying to produce the kinship matrix from the kmer table:
`/ohta/julia.kreiner/software/kmergwas/bin/emma_kinship_kmers -t kmers_table -k 21 --maf 0.05
`
but I get the following error:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  size of file not valid
Aborted (core dumped)
```
I've made sure the kmer_table.names and kmers_table.table files are present and non zero.

Thanks for your help,
Julia

**Comment by voichek** [comment]
Dear Julia,

This is weird, didn't get this error before.

Do other functionalities from the library work for this kmers_table? like converting it to bed/bim file?
Does it cruse immediately or after some time?

Will I be able to look at the kmers_table to recreate the error? 

Best,
Yoav

**Comment by voichek** [comment]
Can we close this issue?

**Comment by voichek** [comment]
I am closing this issue for now, please reopen if this is still an issue.
