### ISSUE TITLE
follow up to: Possible to run list_kmers_found_in_multiple_samples in parallel?

### ISSUE THREAD

**Issue by phil-grayson** [voichek/kmersGWAS#76]
Hi, 

I just wanted to follow up on my closed issue in the subject.  I posted a new message there, but haven't heard back and wasn't sure if you were notified since it's closed. 

Thanks!

Phil

**Comment by voichek** [comment]
Thanks, indeed I was not notified. Maybe it only notify if you reopen it. 
I will try to read and answer tomorrow.

Best,
Yoav

**Comment by phil-grayson** [comment]
Thanks so much :)

On Jan 19, 2021, at 1:56 PM, Yoav Voichek <notifications@github.com<mailto:notifications@github.com>> wrote:

Caution: This message was sent from outside the University of Manitoba.


Thanks, indeed I was not notified. Maybe it only notify if you reopen it.
I will try to read and answer tomorrow.

Best,
Yoav
