### ISSUE TITLE
Unable to build kmersGWAS with make

### ISSUE THREAD

**Issue by ryandamen** [voichek/kmersGWAS#78]
Hello,

I am trying to build your tool but am running into some issues when running make.

After running make I receive the following error [error message.txt](https://github.com/voichek/kmersGWAS/files/6003385/error.message.txt)

Any ideas on how to fix this?
Many thanks,
Ryan

**Comment by voichek** [comment]
Hi Ryan,

1. Just to make sure, did you clone with the submodules?
2. Do you have problem using the release as well? (or is this the reason you are trying to compile?)

Best,
Yoav

**Comment by ryandamen** [comment]
1. Yes I did clone all the submodules in the include folder 
2. Indeed I am trying to use the current release

**Comment by voichek** [comment]
But the release is already compiled, the compiled files work for you?
I am asking as there might be some library that is missing in your system and then also the pre-compiled will have a problem.

**Comment by ryandamen** [comment]
I am currently using the files form the git page if I understand correctly those are pre-compiled right?

**Comment by voichek** [comment]
If you just clone it is not pre-compiled if you download the [release](https://github.com/voichek/kmersGWAS/releases/download/v0.2-beta/v0_2_beta.zip
) It will be pre-compiled.

Let me know if the pre-compiled work for you.

Best,
Yoav

**Comment by ryandamen** [comment]
Yes the pre-compiled version works!
I had previously used that one but because the file structure looked similar I had mistaken one for the other.

Thanks for the help!
