### ISSUE TITLE
How to run kmer pipeline for already downloaded sequences?

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#79]
Hello,
Thank you for creating such a great library to run GWAS. I am trying to implement the method with my samples but facing some problems in the initial stage.
I have trimmed .fastq.gz (R1 and R2) files for 150 samples. I have created 10 folders for 10 samples with both fastq files just to test the pipeline. I used the example codes given in the E.coli folder. I replaced the Arabidopsis SRA numbers with my sample names and did not change anything else. So, I ran the following part of the example code:
`library_dir=/data1/anik/Kmer_Gwas/`
`base_dir=/data1/anik/Kmer_Gwas/examples/resistence_e_coli/`
`THREADS=8`
`KMC=$library_dir/external_programs/kmc_v3 `
`K=31`
`THRESHOLD_COUNT=2`
`samples_dir=$base_dir/samples`
`line_index=0`
`while read name value`
`do`
`if [ $line_index -gt 0 ]`
`then`
`echo Working on sample #$line_index : $name`
`sample_dir=$samples_dir/$name`
`mkdir -p $sample_dir`
`input_file=$sample_dir/input_files.txt `
`ls -l $sample_dir/*.fastq.gz | awk '{print $NF}' > $input_file `
`kmc_canon=$sample_dir/kmc_canon`
`kmc_non_canon=$sample_dir/kmc_non_canon`
`$KMC -t$THREADS -k$K -ci$THRESHOLD_COUNT @$input_file $kmc_canon $sample_dir > $sample_dir/kmc_canon.log.out`
`$KMC -t$THREADS -k$K -ci0 -b @$input_file $kmc_non_canon $sample_dir > $sample_dir/kmc_non_canon.log.out`
`$library_dir/bin/kmers_add_strand_information -c $kmc_canon -n $kmc_non_canon -k $K -o $sample_dir/kmers_with_strand > $sample_dir/add_strand.log.out`
`fi`
`((line_index++))`
`done < resistence.pheno`

The code runs for only 2 samples and outputs everything. But why it does not produce anything for the other samples?

Also, I get the following error while creating a K-mer list per sample:
`awk: cmd. line:1: {printf \"$samples_dir/%s/kmers_with_strand\\t%s\\n\",\$1,\$1}
awk: cmd. line:1:         ^ backslash not last character on line
awk: cmd. line:1: {printf \"$samples_dir/%s/kmers_with_strand\\t%s\\n\",\$1,\$1}
awk: cmd. line:1:         ^ syntax error`

Can you please help me with this issue?

I am very new to bioinformatics. Sorry if the issues are naive.
Thank you.

**Comment by voichek** [comment]
Hi,

Did you first try to run the e. coli example without changing it at all? 

Best,
Yoav

**Comment by DuttaAnik** [comment]
Yes, I tried the codes but I only get SRR individual folder without any downloaded sequence. That is why I used my own data that are already available. When I used to run the code with the e.coli, in the individual accession folder I get an error "SRR... command not found" in log file.

**Comment by DuttaAnik** [comment]
Hello Yoav,
Ok, now I have re-run the first half of the example e.coli code without changing anything. Now it ran as I have updated the sratools to run fasterq-dump.
However, the same problem still persists. For example, I have 10 accessions in the .txt file. But the script goes over the first 9 samples and outputs the results. 
The last sample is not being included in the analysis. 
Do you have any idea what might be going wrong?

**Comment by DuttaAnik** [comment]
Hi Yoav,
You can close this issue now. I have solved it and everything is working fine.
Thanks a lot.

Cheers
Anik
