### ISSUE TITLE
Heritability estimation during Kmer GWAS

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#80]
Hello Yoav,
After running the GWAS, I found an estimate of the heritability of the trait in the Emma.log file. Is this heritability estimated by including the kinship matrix as a random effect in the model? Is it like the additive effects of all the Kmers represented by the kinship among the samples?
If yes, then it is a very good output for me. Although I can use the kinship matrix from kmer itself to estimate kmer-based heritability similar to SNP-based heritability.
Thanks.

Cheers 
Anik

**Comment by voichek** [comment]
Dear Anik,

I think it is exactly that, to be sure you can see the code for this estimate here:
https://github.com/voichek/kmersGWAS/blob/master/src/R/transform_and_permute_phenotypes.R

which is basically these lines:
```
null <- emma.REMLE(phenotypes$phenotype_value,as.matrix(x = rep(1, n_acc),dim = c(n_acc,1)),K)
herit <- null$vg/(null$vg+null$ve)
```

Where `phenotypes$phenotype_value` are the phenotype values and `K` is the kinship that you input into the pipeline.

`emma.REMLE` is taken from the EMMA original publication.

Hope it helps,
Yoav
