### ISSUE TITLE
How to produce a single plink binary bed file and issues with Kmer GWAS.

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#81]
Dear Yoav,
I am using the following code to convert the kmer table to plink binary bed format:
`/data1/anik/Kmer_Gwas/bin/kmers_table_to_bed -t $kmers_table_prefix -k 25 -p resistence_anik.pheno --maf 0.05 --mac 5 -b 10000000 -o plink_binary`

But this code is producing 6 plink_binary.bed, .bim and .fam files.
Is there any way to only get one plink bed file to use for some analysis in Plink?

I have another query. I am running Kmer GWAS for 50 traits but constantly failing to obtain any significant association. I estimated heritability based on the kinship matrix estimated from the kmers. I see that most of the traits have high heritability (around 0.7 to 0.89). So I expected at least some associations considering such high heritability. Previously, I used SNP-based GWAS that produced many significant associations for a trait like Fungicide resistance. Even for this particular trait, I have not obtained any significant Kmer. Other than the polygenic nature of the trait, is there anything else that can describe the failure of Kmer GWAS to detect any significant association despite explaining a lot of phenotypic variation? Is there anything in the scripts that can be improved or tweaked to see what is going on? Like setting a number for filtering the Kmers in the initial step? Some suggestions or explanations would be great.
Thank you.
Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

First, for two different issues please open two issues. This is useful for people to search afterwards and to organize the different issues.

Regarding the first question, you can see in the manual 
`-b - maximal number of variants in each PLINK bed file
(separate to many files)`

So by increasing the number in the `-b` parameter you can get one file (e.g. `-b 500000000`).


Regarding your question, if you have found a SNP association based on the same raw data I would expect to find also a k-mer association, at least most of the time. One possibility is that the threshold for k-mers is more stringent than the one for SNPs, how did you define the threshold for significant for SNPs? what is the difference to the k-mers threshold? You can also look at the top k-mers and not only on the ones that pass the threshold (in kmers/output/phen...).

**Comment by DuttaAnik** [comment]
Hi Yoav,
Sorry for not opening two different issues. I will do that the next time. Thank you for resolving the plink issue. It worked now.

Regarding the GWAS, yes for the trait Fungicide resistance I obtained over 100 SNPs above the Bonferroni threshold at 5% which was estimated as (0.05 / 707619 (no. of SNPs)). Using this threshold I get a good result in GWAS. 
However, I do not know where to look for the difference between the k-mers threshold and SNP threshold. Is it by following the above formula? Because in your paper, it is mentioned that the K-mer threshold is 35 fold higher than the SNP threshold. If it is the case here, then is there any way to lower the k-mer threshold in my analysis? Does it increase the no. of false positives if you lower the threshold here?
One more query, where can I find the information on what is the total number of Kmers used in the GWAS from all of my samples?

**Comment by voichek** [comment]
Dear Anik,

The threshold is set depending on permutation of the phenotype and I guess it is much higher than the threshold you defined for your SNPs. It might also be the case that if you define a threshold for SNP using the same methodology you would also not get any SNPs. To see the threshold the method used you can look at this file:
`kmers/threshold_5per` - which contain the (-log10) threshold for 5% family-wise error rate.

You can look at the top k-mers in this file 
`kmers/output/phenotype_value.assoc.txt`
* It is output from GEMMA, so you can look there for more info on how it is built.
There you can see if you get k-mers which pass your SNP based threshold and see what are the k-mers with best scores.

Regarding number of k-mers used in each GWAS, you can add the flag `--pattern_counter` when running the pipeline and this will create a new file in the GWAS results folder with the effective number of unique presence/absence patterns of k-mers, which is a good estimate of number of unique k-mers.

**Comment by DuttaAnik** [comment]
Ok, thank you for the explanation. I will look into it. 
However, I was thinking about whether or not it is possible to use the plink binary files containing the Kmer information for running a GWAS following an MLM method in PLINK without any permutation. Do you think it is a valid approach or permutation-based threshold is a must thing for running Kmer GWAS?

**Comment by voichek** [comment]
- Yes, you can move to PLINK binary file and use any software for GWAS.
- Notice that the permutations only define the threshold, and as you have the top associated k-mers with their score in `kmers/output/phenotype_value.assoc.txt` you define your own threshold here as well.
- The numbers you report on the `kmers/threshold_*per` files seems weird. Would you mine sharing the directory with the results from the GWAS so I will take a look? (you can send to my email).
- I don't think it is completely valid to use the SNP based threshold for the k-mers, but it is a good indication. As you say you got SNPs and not k-mers, one would expect you will have also k-mers passing the SNPs threshold. We discuss this issue also in the paper.

**Comment by DuttaAnik** [comment]
Dear Yoav,
Thank you for the explanation. How would you define the threshold in `kmers/output/phenotype_value.assoc.txt` as they already contain the p-values? 
Also, is there any option to filter Kmers by setting up a Genotyping call rate e.g. 80%, which is usually followed in SNP calling and filtering?

I have sent you an email with my GWAS outputs. Please have a look. 
Thank you.

**Comment by voichek** [comment]
Hi,

1. You can just filter the `kmers/output/phenotype_value.assoc.txt` by taking everything that pass some threshold level.
2. I am not sure what do you mean by call rate. The filters for k-mers are the number of appearances in one sample, the number of appearances in the population and the filter for reverse-complement vs. the canonical form.
3. You would expect to get more or less the same number of flag 1 and 2. 

Thanks for sending me the GWAS output. It is clear something is not right in the result. I see you use GEMMA 0.98, the library isn't suppose to work with GEMMA 0.98 but with 0.96. I think this is the reason why you don't get any significant k-mers. Please run it with GEMMA 0.96 or if you can not in your system use the patch for GEMMA 0.98 [from here](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460).

Best,
Yoav

**Comment by voichek** [comment]
Dear Anik,

The thresholds and the output looks right.

As this is reference free we do not know if a k-mer is missing or just not present in a sample so this kind of filtering can not be done. The idea is that you might loose some of your k-mers because this type of partial statistics, but due to the high level of redundency you should find some k-mer that will be able to tag your variant of interest.

Regarding the different number of k-mers, it should be more or less similar. The number of flag 1 and 2 should be on the same magnitude, what are the absolute numbers you see?

Practically this infrastructure will not work with k>31 (=31 is ok). In all cases I checked k=31 or k=25 gave same results and I think it is the right range of k to use. As we look for presence/absence of exact matches you do not want to take k to be too high because then sequencing errors will be more of a problem and also SNPs which are close by will also be a problem as they will fall in the same k-mer. From the other side of this argument even for k=25 the space is really large, 2^50=~10^15. From the number of k-mers in your k-mers-table it seems that you are working with a small genome, which will make me even more sure that k should not go higher.

Hope it helps,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Thank you very much for the answer. Yes, the confusion is clear now regarding the genotyping call rate.

Regarding the number of Kmers, I get the following output for one sample:
```
Canonized kmers:	34359196
Non-canon kmers:	74571011
Non-canon kmers found:	68251361
flag	0	count is	0
flag	1	count is	233038
flag	2	count is	233993
flag	3	count is	33892165
kmers to save:	34359196
```
So, in every sample, I have such differences in Flag 1 and 2.
Ok, I understand your point regarding the k-mer length. I am working with a fungal genome that has a genome size of ~40 Mb. At the moment, I am using 25bp kmer length.

**Comment by voichek** [comment]
Dear Anik,

1. I do not think there is a reason to worry about the redundancy as long as you take it into account while setting the threshold for calling significant k-mers. One option is the permutation based threshold as is used now, another is the to take the number of unique patterns the pipeline is reporting (for Bonferroni based threshold).
2. Regarding the flags, it looks really good as there is only a small different between flag 1 and 2 (less than 0.5%). Also almost all your k-mers appear in both forward and reverse which is really good.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Dear Yoav,
Thank you very very much for answering all the questions and resolving the key issues. Very much appreciated.

One last question then you can close this thread.

Is the Bonferroni threshold in the pipeline estimated by dividing 0.05 by the number of unique K-mers found?

**Comment by voichek** [comment]
Dear Anik,

Sorry for the late reply. 

There is no Bonferroni threshold in the pipeline, but as it reports the number of unique present absence patterns, you can use it to define a threshold by yourself.

Best,
Yoav
