### ISSUE TITLE
How to run the K-mer GWAS for many phenotypes simultaneously?

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#82]
Hi Yoav,
Is it possible to run the following K-mer GWAS command for multiple phenotypes?
`python2.7 /data1/anik/Kmer_Gwas/kmers_gwas.py --pheno resistence_anik.pheno --kmers_table kmers_table -l 25 --maf 0.05 --pattern_counter -p 8 --outdir run_gwas`

At the moment, the code runs for a single phenotype that is present in the phenotype file. I have 50 traits and was wondering whether the command can be looped to run on all the phenotypes. Will I need to create the phenotype file separately or I can put all the phenotype in one file?
Thank you.

Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

You will need to create a file per phenotype.

Best,
Yoav
