### ISSUE TITLE
How to perform LD analysis on significantly associated Kmers?

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#83]
Dear Yoav,
I have found some significant Kmers for which I obtained the population presence/absence pattern using the `filter_kmers` option. Now, I want to do a LD analysis and generate plots like in your paper. Should one use this presence/absence output file of the significant Kmers along with the binary Kmer table to perform LD analysis? Because the positioning of the K-mers are not known beforehand. In SNP-based LD analysis, one can define a window of the region in the genome, but here we do not have that luxury. So, I was wondering how it should be done.

Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

Indeed, you do not have a proximity like you have for SNPs. I have shown in the paper the LD between all k-mers which were found to be associated with a phenotype. I think this is useful to see if you have one set of k-mers which represent one variant or more than one. Do you want to do this analysis from different reasons?

Best,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Yes, I saw that you did the LD analysis for significant Kmers. That is exactly what I want to do. I have created a presence/absence pattern for the significantly associated Kmers and I suspect that multiple K-mers are tagging one or two specific loci. That is why I want to do a LD analysis. Also in some cases, some significant K-mers have low frequency (i.e. present in few individuals). So before going deep into the region these K-mers are originating, I want to have a measure of the LD among them.
Now, I have created a .txt files with my significant Kmers and then feed that into plink to measure the LD only among those Kmers. But in the output, I am not getting the R2 value of all the Kmers that are listed in the input file. I am not sure if I am doing it in the correct way. 
In another post, I saw that you mentioned to obtain a presence/absence pattern table of the significant Kmers and then use it for LD analysis.
So, I got confused about what approach you followed for the LD analysis.
It would be nice if you can share how you did it.

Thanks.
Anik

**Comment by voichek** [comment]
Dear Anik,

I just load the text file of presence absence into R and calculate the pairwise LD as explained in my method section "Calculation of linkage disequilibrium". 

Best,
Yoav

**Comment by DuttaAnik** [comment]
Dear Yoav,
You mean a file like this below?
```
kmer	Individual_1	Individual_2	Individual_3	Individual_4
AACCACCACGACCAATGGCCCACAG	0	0	1	1
ACAACCACCACGACCAATGGCCCAC	0	0	1	1
ACCACCACGACCAATGGCCCACAGG	0	0	1	1
ACCACGACCAATGGCCCACAGGGAC	0	0	1	1
ACGACAACCACCACGACCAATGGCC	0	0	1	1
```

**Comment by DuttaAnik** [comment]
Hi Yoav,
I think you can close this issue now. I have used a list of significant Kmers and use that in PLINK to get the LD values. It worked fine.

Regards
Anik

**Comment by zhoudreames** [comment]
> Hi Yoav, I think you can close this issue now. I have used a list of significant Kmers and use that in PLINK to get the LD values. It worked fine.
> 
> Regards Anik

Hi, can you tell how to get the LD value by using plink?

**Comment by voichek** [comment]
I don't have any experience with this.
