### ISSUE TITLE
Assertion `table' failed while runningkmers_add_strand_information

### ISSUE THREAD

**Issue by xinbeibei** [voichek/kmersGWAS#84]
Hi Yoav,

When I ran kmers_add_strand_information by using the complied excutable program in v0_2_beta.zip, the following error information kept occuring, with different data set. Do you know how to solve this problem? 

Thank you very much,
Bei
```
kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::clear_to_size(google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type) [with Value = std::pair<const long unsigned int, long unsigned int>; Key = long unsigned int; HashFcn = Hash64; ExtractKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SelectKey; SetKey = google::dense_hash_map<long unsigned int, long unsigned int, Hash64>::SetKey; EqualKey = std::equal_to<long unsigned int>; Alloc = google::libc_allocator_with_realloc<std::pair<const long unsigned int, long unsigned int> >; google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, EqualKey, Alloc>::size_type = long unsigned int]: Assertion `table' failed.
Aborted
```

**Comment by voichek** [comment]
Can I close this issue?

**Comment by ylevmirom** [comment]
Hey Yoav, 

I'm getting the same error. 
I tried running `bin/kmers_add_strand_information -help` and it does show me the options. 
any idea how to solve it? 

About the downloading process, I'm using a pretty old HPC system, the glibc library used is glibc-2.14.1. 
i hade to run make for the kmc to get running but I'm getting the error above. 
hope this information is useful, I'm pretty new to Linux. 

Thanks a lot, 

Yael

**Comment by voichek** [comment]
Dear Yael,

Just to be sure:

1. when you run `bin/kmers_add_strand_information`  on your sample you get the error massage `kmers_add_strand_information: ./include/sparsehash/internal/densehashtable.h:788: void google::dense_hashtable<Value, Key, HashFcn, ExtractKey, SetKey, Equ....` ?
2. But when you run `bin/kmers_add_strand_information -help` you get the right help massage?
3. Did you try to run the e. coli example?

Best,
Yoav

**Comment by ylevmirom** [comment]
thanks for your quick answer, 
1. Yes
2. Yes
3. i tried and got this error: 
/data/home/distelfeld/ylevmirom/kmers/examples/resistence_e_coli
bee063.haifa.ac.il
Tue Aug 16 13:34:11 IDT 2022
Working on sample #1 : SRR3050845
/ebio/abt6/yvoichek/smallproj/programs/sratoolkit.2.9.2-ubuntu64/bin/fasterq-dump SRR3050845 --outdir ./~/kmers/examples/resistence_e_coli/example_dir/samples/SRR3050845 --temp ./~/kmers/examples/resistence_e_coli/example_dir/samples/SRR3050845 --threads 20 --split-files >>./~/kmers/examples/resistence_e_coli/example_dir/samples/SRR3050845/fasterq-dump.log.out 2>&1
Couldn't download sequencing file, wait two minutes and try again(#2)

Thanks
Yael

**Comment by voichek** [comment]
Dear Yael,

You need to to tell the script (line 11) where is your own copy of the sratoolkit to use.

Best,
Yoav

**Comment by voichek** [comment]
Dear Yael,

Can we close this issue?

Best,
Yoav

**Comment by ylevmirom** [comment]
Yes,
Thank you very much.
Yael

**Comment by ylevmirom** [comment]
well it's still open so ill ask here, 
the second step now works fine (kmers_add_strand_information).
i noticed that also with the example on e.coli, the kmc_canon.2 and kmc_all.2 are empty, is that ok? 

thanks, 

yael

**Comment by voichek** [comment]
Dear Yael,

I see this files are also empty in my folder, it seems ok.

In general it is better to open new issues for different questions, so it will be easier for people to search when they have similar questions in the future.
Best,
Yoav
