### ISSUE TITLE
error while running & k-mer positions & LD calc.

### ISSUE THREAD

**Issue by MuBulut** [voichek/kmersGWAS#85]
Hi there, 
we were trying to run the example on the flowers....
unfortunately, we get the error of 
File "/home/KMC/kmers_gwas.py", line 278, in
main()
File "/home/KMC/kmers_gwas.py", line 153, in main
fam_fn = get_file_type_in_dir(paths["kmers_associations_dir"], "%s.fam" % p_name)
File "/home/KMC/src/py/functions.py", line 10, in get_file_type_in_dir
raise Exception("File count not = 1 %s %d\n%s" % (type_suffix, len(fns), dir_name))
Exception: File count not = 1 phenotype_value.fam 0

the error in the kmer_accession.log is the following:

Effective minor allele count:   44
terminate called after throwing an instance of 'std::logic_error'
  what():  size of file not valid
Aborted (core dumped)

thanks in advance

**Comment by voichek** [comment]
Dear MuBulut,

It seems that the k-mers table the script, downloaded from Zenodo is corrupted. What is the size of the k-mers table you get after it is de compressed ?

You can also try to download it manually from here:
https://zenodo.org/record/3596255#.YFDQ_mRKhhE

and see you get the same thing.

Best,
Yoav

**Comment by MuBulut** [comment]
Hi Yoav,
thanks for the link, we managed somehow to get rid of the error.
Sorry for bothering you.
Cheers,
Mustafa

**Comment by MuBulut** [comment]
Hi and sorry again for bothering, 
now we are facing another issue........
The pipeline in itself works now, but we observe that the pipeline stops after 1 trait.
Is there any indication/line that we might need to change, which limits the numbers of traits or do we need to provide it in a given input format (we basically used to example run and added more columns in the phenotype file)?
Thanks again.
Cheers,
Mustafa

**Comment by voichek** [comment]
Dear Mustafa,

For next time, please open a new issue for every different question/bug report as it will help others to find issues related to their problem.

1. The pipeline works on one phenotype each time, so you will need to separate your phenotypes to different files and run each one individually.
2. The information on how to identify the position of k-mers in the genome is explained in our method section. We do not have a table of position of each k-mer in the genome, first as it is impossible, some k-mers can not be positioned on the genome. Second, if this is not an easy task (that is a match found by an aligner) you have to check this manually as described in the methods.
3. The same is true for LD between SNPs and k-mers, I have done it for the specific set of SNPs and k-mers reported in the paper, as described in the method. You basically take your SNP of interest and extract their population pattern from the 1001G SNP matrix and your k-mers presence/absence from the k-mers table and calculate LD between them.

Best,
Yoav

**Comment by MuBulut** [comment]
Thanks a lot for the reply. I adjusted the issue accordingly for those who might have the same questions.
Cheers,
Mustafa
