### ISSUE TITLE
Multiple locations of a K-mer in the genome

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#86]
Hi Yoav,
I am using the first approach which is mapping the significant K-mers directly to the reference genome. Using that method, I found that some K-mers have multiple locations in the genome. 

Do you think in such cases one should try assembling the reads from where the K-mer originated and then align the assembly to the reference genome? Will this approach change the result?

Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

First, I am happy you found significant associations and I hope you could make sense of them, I think this is the fun part.

I guess if a k-mer really maps to multiple places in the genome, it is not likely that your variant (relative to the reference) changed in all these places, but rather in only one. I would start by retrieving the reads that have this exact k-mer for strains which it is "present" and try to map the reads. And look at the mapping (e.g. using IGV) of this reads and the specific location of the k-mer in the reads. You can also map all the reads from strains which the k-mer was absent and look at the same region, to understand what the k-mer presence/absence really represent. If this is still not conclusive you can assemble the retrieved reads, the local assembly sometimes gives this extra information needed, but I would use this approach just after looking at the mapping by eye and trying to solve the riddle didn't help.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Thanks a lot for the reply. Yes, I was really surprised to see that where the SNP-based GWAS completely failed, K-mer GWAS reported so many significant associations. And the majority of them are in high LD among themselves. By directly mapping the K-mers to the reference, I could get the location of them in the genome easily. However, some K-mers could not be mapped by this approach.

When you say "map the reads", do you mean to assemble the paired-end FastQ files (R1 and R2) and then map them onto the reference or I can just map the extracted paired-end reads (i.e. by using `fetch-reads`) to the reference without assembling them? Do you think one should do this for every individual in which the Kmer was present? Is there any assumption that if the reads containing a K-mer are extracted from one individual then all the other individuals will output the same reads? 
Actually, I just extracted the reads from which a significant K-mer originated and when I tried to assemble them with SPades, I could not obtain an assembly because there were non-overlapping reads in the R1 and R2 files. So, I thought about whether it will change if I use another individual in which the K-mer will be present.

Best,
Anik

**Comment by voichek** [comment]
Dear Aink,

You can map the fetched reads with your favourite aligner program (e.g. Bowtie2) to the genome as a first step. I would do this for a few individuals to start, if things seems similar combine reads from all accessions. You would need to play with this... 

For assembly I would combine all reads from all individuals that had the k-mer, just to get higher coverage. 

A general comment, as you mentioned you do not get any associations with SNPs but do get them with k-mers. I would plot the qq-plot for all k-mers associations just to see there is no inflation in p-values for some reason for k-mers.

**Comment by DuttaAnik** [comment]
Hi Yoav,
Thank you for your comment and suggestions.

Which file do you normally use to see the qq-plot? Is it the `phenotype_value.assoc.txt` in the output folder that contains the 10001 Kmers that passed the initial filtering during the GWAS?

**Comment by voichek** [comment]
Dear Anik,

The file that you used contains only the best 10k scored k-mers so it should look like what you plotted.

To create the qq-plot you have to run the full model on all your k-mers. For that you can convert all your k-mers table to PLINK binary file and run with a GWAS program, like GEMMA, to get the p-value for all k-mers. Another option is to just give the pipeline when you run, a much higher number of k-mers to pass to the second stage which will contain all your k-mers table. The latter can be done by setting `--kmers_for_no_perm_phenotype` to be higher than the number of k-mers in your full k-mers table (this will of course take a while to run, dependent on the number of k-mers in your full table).

Best,
Yoav

**Comment by DuttaAnik** [comment]
Thanks a lot, Yoav for your comments and support.

You can close this issue now.

Regards
Anik

**Comment by voichek** [comment]
BTW, you can close issues yourself :)
