### ISSUE TITLE
Running multiple phenotypes, with varying size, on the same k-mer table. 

### ISSUE THREAD

**Issue by douwetb** [voichek/kmersGWAS#88]
Dear Yoav,

First of all, thanks for everything regarding the kmerGWAS since it is running smoothly and questions are answered fast.

I want to run multiple phenotypes, with varying sample size because of missing information, on one k-mer table (Due to the time and memory it costs to constantly make a new k-mer table for every phenotype).

For instance, say that I ran a phenotype with 100 samples, built the k-mer table, did the GWAS etc. 
But now I have a phenotype with 98 values/samples and 2x NA. Previous comments by you mentioned that the NA's should be removed from the lettuce.pheno file. But my question is then, Is it possible to run the GWAS for 98 samples with the k-mer table that was made from 100 samples? Or should I re-run the entire pipeline, because the order of the kmer_table.table, kmer_table.names and kmer_table.kinship does not match the order of my lettuce.pheno file?

I'm looking forward to your answer.

Kind regards,
Douwe

**Comment by voichek** [comment]
Dear Douwe,

You can use the full k-mers-table and just remove the lines of accessions you don't have data for.
The pipeline will just run the GWAS on accessions that you have data for. There is no need to redo the k-mers-table again. The pipeline will reduce the kinship and the k-mers-table by itself, this is transparent to the user side.

Best,
Yoav

**Comment by douwetb** [comment]
Dear Yoav,

That is amazing to hear. Thank you again and keep the nice work.

Cheers,
Douwe
