### ISSUE TITLE
Running the K-mer pipeline for SNP GWAS

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#90]
Hi Yoav,
I am trying to run the K-mer GWAS pipeline for SNP GWAS. I used the following codes:
`python2.7 /data1/anik/Kmer_Gwas/kmers_gwas.py --pheno resistence_anik.pheno --dont_run_on_kmers --run_on_snps_two_steps --snp_matrix IPO323 --snps_number 20000 --kinship_snps IPO323.kinship --outdir snps`

But it prints an error like: `kmers_gwas.py: error: argument --kmers_table is required`

Can you tell me what is going wrong here?

Also, is it possible to add Principal components as covariates in the `k-mer` GWAS one-liner with the `-c `option from GEMMA?

Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

1. This script is built for k-mers GWAS so even if it doesn't really run the GWAS on k-mers it expect to get it. This is not the ideal behaviour, but this is how it is for now. Input also the k-mers table, and make sure the order of accessions in the SNP matrix is the same as the one in the k-mers table. Also, the `--kinship_snps` parameter is a flag (False/True) so you fo not need to provide the kinship, but it will expect to find it in IPO323.kinship (SNPs table name + .kinship).
2. For now you can not add a covariate to the k-mers GWAS, this can be done theoretically, but it needs to be programmed.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Thanks a lot for the clarification, Yoav.

Cheers
Anik
