### ISSUE TITLE
Effect size estimates of significant K-mers

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#91]
Hi Yoav,
I was trying to run the Kmer GWAS script for estimate the effect size of each significantly associated K-mers. With the `-lmm 2` in GEMMA, it produces the p-values based on the likelihood ratio test and does not output the beta value of each marker along with standard error.

So, in the `kmers_gwas.py` I changed the `-lmm 2` to `-lmm 1` which performs Wald test and output the marker effect and SE for each K-mer. But I receive the following warnings in the log file:
```
awk: cmd. line:1: (FILENAME=- FNR=2) warning: log: received negative argument -28.8416
awk: cmd. line:1: (FILENAME=- FNR=3) warning: log: received negative argument -27.5147
awk: cmd. line:1: (FILENAME=- FNR=4) warning: log: received negative argument -26.5116
awk: cmd. line:1: (FILENAME=- FNR=5) warning: log: received negative argument -26.3441
```
It keeps going until the 10002 Kmers. Also in the `threshold_5per`, no value is printed. So, in the end there is a file with 10002 kmers with all the other GWAS statistics.

Is the script designed only for the likelihood ratio test using `-lmm 2` option from GEMMA?

Regards
Anik

**Comment by voichek** [comment]
Dear Anik,

I would guess it is an issue of the output format you get from gemma, the script assumes the p-value is in a specific column and I think for -lmm 1 it is in a different column. Is this the case?

I previously wrote a "patch" so the [kmers_gwas.py](https://github.com/voichek/kmersGWAS/issues/53#issuecomment-698876460) will work with gemma 0.98 and not 0.96 and there it was exactly the same situation (different column had the p-value). If I remember correctly you use this patch. So, if it is indeed a column issue, you can try to do a diff with the patch and change it yourself. Let me know if this does the job.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Indeed, I used the "patch" version because the original script was not running with GEMMA 0.98. 
Yes, with gemma -lmm 1 you two extra columns. But if the issue is with the columns, then why does it produce all the values and keep them in the same column?
Anyways, if I need to change something in the patch, what would that be? Can you please be a bit more specific? Like which file should I make the changes in?

Thanks. 
Anik

**Comment by voichek** [comment]
Dear Anik,

I will add this as a parameter which one can set from the command line.
I have a lot to do in the next few days but hopefully I will be able to program this on Friday.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Dear Yoav,
Thank you very much for taking this into consideration. Looking forward to that.

Cheers
Anik

**Comment by voichek** [comment]
Dear Anik,

First, I thought about what you want to do, and just notice that the k-mers are filtered before running the GEMMA according to an approximation to a LMM. Therefore, maybe some assumption are not met, it is still likely to give you the best k-mers but just keep this in mind.

I improved the patch I wrote before, (at some point I will just add this to the official release).
Download this: [replacment_path_20210521.zip](https://github.com/voichek/kmersGWAS/files/6524648/replacment_path_20210521.zip)
Replace the three files for the ones coming with the release.
Now you can indicate in the command line what is the column from GEMMA output to use, using the parameter `--gemma_output_pval_column`. So the default is `--gemma_output_pval_column 9` and works with GEMMA 0.96 and if you want to use GEMMA 0.98.1 you will just need to input `--gemma_output_pval_column 10`. And you can change this to the relevant column for your current need.

Hope this will do the trick,
Yoav

**Comment by DuttaAnik** [comment]
Thank you very much, Yoav.
I will test this one and let you know if it works by the end of this week.

Regards
Anik

**Comment by DuttaAnik** [comment]
Hi Yoav,
Sorry for the delay. But it worked!! :)
Thank you very much.
