### ISSUE TITLE
Why the kmers/output/*.assoc.txt has only 10000markers

### ISSUE THREAD

**Issue by laserhsu** [voichek/kmersGWAS#94]
Dear Voichek,
Thanks for your awesome scripts. I run anythings well, but stll have some problem.
In last step for gemma GWAS, why the kmers/output/*.assoc.txt has only 10000markers?
Looking forward to your reply.

Sincerely,
Xu Han.

**Comment by voichek** [comment]
Dear Xu Han,

The number of k-mers in the *.assoc.txt files are the one I filter in the first round (you can read more on the two steps process in our paper).  This number can be changed from the command line by using `--kmers_number`. In any case, these files are intermediate files. You should be interested in the `pass_threshold_5p` (or `pass_threshold_5p`) files, which have the associations of all the _k-mers_ which pass the permutation based threshold.

Best,
Yoav

**Comment by laserhsu** [comment]
Dear Voichek,
Thanks for your reply in time. Sorry for that actually I haven't read carefully on the papers. And just now, I find the procedure depict in your paper at Extended Data Fig.3. Excellent work!
But If I want plot QQ-plot how should I get P-value file of all the marker?

Sincerely,
Xu Han.

**Comment by voichek** [comment]
Dear Xu Ham,

For a QQ plot you will need to run the full model on all k-mers with a GWAS program (i.e. GEMMA). You can get the full presence/absence matrix in plink binary format (compatible with GEMMA) using `kmers_table_to_bed` functionality.

Best,
Yoav

**Comment by laserhsu** [comment]
Dear Voichek,
Thanks so much bro.
But honestly, I can't figure out the `-b` parameter of `kmers_table_to_bed` . It's just a deliberate number in order to separate to many files for convenience of lowering the calculating ?
If so, I need run all the separate bfiles to gain the output.


Sincerely,
Xu Han.

**Comment by voichek** [comment]
Dear Xu Han,

Yes, exactly, you can put this number to very high if you want them in one file, otherwise you will need to combine the input to create a QQ-plot.

Best,
Yoav

**Comment by laserhsu** [comment]
Dear Voichek,
Thanks for your answer. What an effecient and pleasure communication!

Best,
Xu Han
