### ISSUE TITLE
how to control the false negative rate in the gwas first step

### ISSUE THREAD

**Issue by BlueIsTheWarmestColor** [voichek/kmersGWAS#97]
Dear Voichek:

It's me again, sorry to bother you. 

I get about 800 kmers using --kmers_number 100000, but I don't know if I miss any real kmers. In your paper, you introduced an approach to avoid it, but I don't know how to get the information about the first approximate calculation. 

Hope to be tought how to get the first filtering step information. 

Looking forward to your reply.

Sincerely,
Simon.

**Comment by voichek** [comment]
Dear Simon,

The way I checked if the number of k-mers in the first steps is large enough works as follows: in the _k-mers_ which pass the threshold file, every _k-mer_ has a name like this (kmer)_(number), e.g. ACGA...CACA_**125**. The number is the position from the order in the first filtering step. From all the _k-mers_ which pass the threshold I find the _k-mers_ with the highest number, and check if this number is smaller than 0.5*(number of _k-mers_ taken in the first step), in your case check if it smaller than 50,000. If it is not smaller, I run the full pipeline passing more _k-mers_ in the first steps (x10 more or x100 more). If it is smaller I just use these _k-mers_ as taking more _k-mers_ in the first step will very very likely will not give you more _k-mers_ which pass the threshold.

Best,
Yoav

**Comment by BlueIsTheWarmestColor** [comment]
Dear Voichek:

Thanks for your reply, I get your message and will check later. 

Sincerely,
Simon.
