### ISSUE TITLE
Error in running my samples & examples

### ISSUE THREAD

**Issue by orangelc1221** [voichek/kmersGWAS#98]
Dear Voichek,

I have been testing the kmersGWAS pipeline on my samples (thank you for your great job!). But I got an error when I run the kmers_gwas.py  To figure out whether it is a problem of my environment or so, I run the example code in /flowering_time_arabidopsis as well. And the same error popped out, which says:

Rscript execution error: No such file or directory
Traceback (most recent call last):
  File "../../kmers_gwas.py", line 278, in <module>
    main()
  File "../../kmers_gwas.py", line 107, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'run_GWAS_FT10/pheno.phenotypes_and_permutations'

Do you have any thoughts on what might be the issues? I tried to check the previous issues from the others but didn't see the same error. Thank you!

Best,
cl

**Comment by voichek** [comment]
Dear cl,

My first guess is that the libraries that should work in R don't. Can you check this?

If this is not the case, can you send me a zip of the gwas run directory of the flowering time so I can check which step didn't work.

Best,
Yoav

**Comment by voichek** [comment]
Dear cl,

Did this suggestion solved your issue? Can this issue be closed?

Best,
Yoav

**Comment by orangelc1221** [comment]
Dear Yoav,

Many thanks for your suggestion, it works! It seems that the R package "Mvnpermute" "matrixcalc" was not installed in my environment. After installing them, I was able to run the pipeline - both on the flowering time example and my samples. 

And sorry for my late reply -  I was on fieldwork past few days and just continued the trial on the pipeline. Thanks again for your support!

Best,
cl
